const fs = require('fs');
const path = require('path');

const enDir = path.join(__dirname, 'web', 'src', 'locales', 'en');

const replacements = [
  // Mangled suffix patterns from automatic dictionary
  ['Energand', 'Energy'], ['energand', 'energy'],
  ['Communitand', 'Community'], ['communitand', 'community'],
  ['Assembland', 'Assembly'], ['assembland', 'assembly'],
  ['assemblys', 'assemblies'], ['Assemblys', 'Assemblies'],
  ['Treasurand', 'Treasury'], ['treasurand', 'treasury'],
  ['Categorand', 'Category'], ['categorand', 'category'],
  ['Currencand', 'Currency'], ['currencand', 'currency'],
  ['moneand', 'money'], ['Moneand', 'Money'],
  ['Tandpe', 'Type'], ['tandpe', 'type'],
  ['calculatesdora', 'calculator'], ['Calculatesdora', 'Calculator'],
  ['calculatesstor', 'calculator'], ['Calculatesstor', 'Calculator'],
  ['unordades', 'units'], ['Unordades', 'Units'],
  ['onland', 'automatically'], ['Onland', 'Automatically'],
  ['Sandstem', 'System'], ['sandstem', 'system'],
  ['Andes', 'When'], ['andes', 'when'],
  ['andou', 'you'], ['Andou', 'You'],
  ['sgove', 'serves'], ['Sgove', 'Serves'],
  ['tecnorco', 'technical'], ['Tecnorco', 'Technical'],
  ['per ejemplo', 'for example'], ['Per ejemplo', 'For example'],
  ['per', 'by'], ['Per', 'By'],
  ['Fgost', 'First'], ['fgost', 'first'],
  ['andml', 'yml'], ['Andml', 'YML'],
  ['andugabandtedb2', 'yugabytedb2'], ['Andugabandtedb2', 'Yugabytedb2'],
  ['volumenes', 'volumes'], ['Volumenes', 'Volumes'],
  ['changesndo', 'changing'], ['Changesndo', 'Changing'],
  ['copandndo', 'copying'], ['Copandndo', 'Copying'],
  ['calculatedtes', 'calculated'], ['Calculatedtes', 'Calculated'],
  ['se vincula', 'is linked'], ['se vinculan', 'are linked'],
  ['tiene su factor', 'has its factor'],
  ['tiene', 'has'], ['Tiene', 'Has'],
  ['is updatedn', 'are updated'], ['se updated', 'is updated'],
  ['Tambien', 'Also'], ['tambien', 'also'],
  ['especificar', 'specify'], ['un factor', 'a factor'],
  ['amplificacion', 'amplification'], ['adicional', 'additional'],
  ['dificiles', 'difficult'], ['easier', 'easier'],
  ['lo normal', 'normal'], ['lo considera', 'they consider'],
  ['necessarand', 'necessary'], ['needs', 'needs'],
  ['hacer', 'do'], ['hacer calculos', 'do calculations'],
  ['No needss', 'no need to'], ['no needss', 'no need to'],
  ['ingresa', 'enter'], ['dos prices', 'two prices'],
  ['that es', 'what is'], ['That es', 'What is'],
  ['que es', 'what is'], ['Que es', 'What is'],
  ['ES la', 'is the'], ['es la', 'is the'], ['Es la', 'Is the'],
  ['es el', 'is the'], ['Es el', 'Is the'],
  ['Are not Accounts', 'There are no separate accounts'],
  ['separadas', 'separate'], ['sola Account', 'single account'],
  ['a sola', 'a single'], ['sola', 'single'],
  ['receives the Taxes', 'receives taxes'],
  ['Taxes and', 'taxes and'], ['Taxes', 'taxes'], ['taxes', 'taxes'],
  ['usando', 'using'], ['cualquiera', 'any'],
  ['estos 3', 'these 3'], ['these 3 names', 'these 3 names'],
  ['All llegan', 'all go to'], ['llegan', 'go to'],
  ['la misma', 'the same'], ['misma Account', 'same account'],
  ['Each hour', 'Each time'], ['each hour', 'each time'],
  ['hace', 'makes'], ['Automatic', 'automatic'],
  ['va a parar', 'goes to'], ['parar', 'go'],
  ['transfieren', 'transfer'], ['se transfieren', 'are transferred'],
  ['Nadie', 'Nobody'], ['nadie', 'nobody'],
  ['depositar', 'deposit'], ['manualland', 'manually'],
  ['se acumula', 'accumulates'], ['acumula', 'accumulates'],
  ['with el usage', 'with usage'],
  ['destina', 'allocated'], ['se destina', 'is allocated'],
  ['infraestructura', 'infrastructure'],
  ['publicos', 'public'], ['Publicos', 'Public'],
  ['Mutual aid', 'mutual aid'], ['mutual', 'mutual'],
  ['proandectos', 'projects'], ['proyectos', 'projects'],
  ['aprobados', 'approved'],
  ['No can', 'Cannot'], ['no can', 'cannot'],
  ['spendse', 'be spent'], ['spend', 'spend'],
  ['libremente', 'freely'], ['Expenors', 'expense'],
  ['required Approval', 'requires approval'], ['required', 'requires'],
  ['collective', 'collective'],
  ['For spend', 'To spend'], ['for spend', 'to spend'],
  ['there are that', 'you must'], ['Create a Proposal', 'create a proposal'],
  ['distribucion', 'distribution'],
  ['indicando', 'indicating'], ['Recipient', 'recipient'],
  ['Amount and la Reason', 'amount and the reason'],
  ['votan In favor', 'vote in favor'], ['votan', 'vote'],
  ['In favor o Against', 'in favor or against'],
  ['se approve', 'is approved'], ['approve', 'approved'],
  ['can be Execute', 'can be executed'], ['Execute', 'executed'],
  ['se transfiere', 'is transferred'], ['transfiere', 'transferred'],
  ['individualmente', 'individually'],
  ['Balance es visible', 'balance is visible'],
  ['pero', 'but'], ['expenses', 'expenses'],
  ['se realizan', 'are made'], ['realizan', 'made'],
  ['through voting', 'through voting'],
  ['garantiza', 'guarantees'],
  ['No pueda', 'cannot'], ['pueda', 'can'],
  ['mal utilizado', 'misused'], ['utilizado', 'used'],
  ['sola person', 'single person'],
  ['integridad', 'integrity'],
  ['Service', 'service'], ['service', 'service'],
  ['New Service', 'new service'], ['new Service', 'new service'],
  ['hostname', 'hostname'], ['ports', 'ports'],
  ['se mide', 'is measured'], ['mide', 'measured'],
  ['material', 'material'], ['El', 'The'], ['el', 'the'],
  ['A that', 'To which'], ['a that', 'to which'],
  ['pertenece', 'belongs'], ['this Parameter', 'this parameter'],
  ['Parameter', 'parameter'], ['parameter', 'parameter'],
  ['needss a Categorand New', 'need a new category'],
  ['createsla', 'create it'], ['Button', 'button'],
  ['New Categorand', 'New category'], ['new Categorand', 'new category'],
  ['Vincula', 'Link'], ['vincula', 'link'],
  ['this Work', 'this work'], ['this work', 'this work'],
  ['a la Tariff', 'to the tariff'], ['a la', 'to the'],
  ['recalculates', 'is recalculated'], ['recalculate', 'recalculate'],
  ['factores', 'factors'], ['factor', 'factor'],
  ['Cuanta', 'How much'], ['cuanta', 'how much'],
  ['representa', 'represents'], ['a Hour', 'an hour'],
  ['fijo', 'fixed'], ['No is updated', 'is not updated'],
  ['Considera', 'consider'], ['considera', 'consider'],
  ['vincularlo', 'linking it'], ['Tandpe of effort Up', 'effort type'],
  ['Multiplicador', 'Multiplier'], ['multiplicador', 'multiplier'],
  ['about el', 'on the'], ['about', 'on'],
  ['without Change', 'no change'], ['Usalo', 'Use it'],
  ['mas dificiles', 'more difficult'], ['mas', 'more'],
  ['menos', 'less'], ['lo normal', 'normal'],
  ['su Categorand', 'its category'],
  ['aliases', 'aliases'], ['son aliases', 'are aliases'],
  ['Andou can', 'You can'], ['andou can', 'you can'],
  ['use cualquiera', 'use any'],
  ['Does not exist', 'does not exist'], ['does not exist', 'does not exist'],
  ['creates a Account', 'create an account'], ['creates', 'create'],
  ['ubename', 'username'], ['with ubename', 'with username'],
  ['Select la', 'Select the'], ['select la', 'select the'],
  ['receivea', 'receives'], ['appearsn', 'appear'],
  ['validas', 'valid'], ['of the Node', 'of the node'],
  ['se distribugoa', 'is distributed'], ['distribugoa', 'distributed'],
  ['Debe be', 'Must be'], ['debe be', 'must be'],
  ['greater that', 'greater than'], ['No superar', 'not exceed'],
  ['superar el Balance', 'exceed the balance'], ['superar', 'exceed'],
  ['available', 'available'],
  ['El DEX', 'The DEX'], ['el DEX', 'the DEX'],
  ['tiene a', 'has a'], ['Tiene a', 'Has a'],
  ['in Cash', 'in cash'], ['Cash', 'cash'],
  ['Se registra', 'It registers'], ['se registra', 'it registers'],
  ['se compro', 'was bought'], ['compro', 'bought'],
  ['how much', 'how much'], ['a that Price', 'at what price'],
  ['Price in Currencand', 'price in currency'],
  ['salio el moneand', 'the money came from'],
  ['salio', 'came from'], ['el moneand', 'the money'],
  ['se seedio', 'was sold'], ['seedio', 'sold'],
  ['seedie', 'sold'], ['se seedie', 'was sold'],
  ['entro el moneand', 'the money went to'], ['entro', 'went to'],
  ['Department of Commerce Exterior', 'External Commerce Department'],
  ['department of Commerce Exterior', 'external commerce department'],
  ['Su Function', 'Its function'], ['su Function', 'its function'],
  ['connect la economia', 'connects the economy'],
  ['economia interna', 'internal economy'], ['economia externa', 'external economy'],
  ['moneand real', 'real money'], ['real', 'real'],
  ['Un Producer', 'A producer'], ['un Producer', 'a producer'],
  ['le seede', 'sells'], ['le seede su Product', 'sells their product'],
  ['le paid', 'pays them'], ['paid in TQ', 'pays in TQ'],
  ['With ese moneand', 'With that money'], ['ese moneand', 'that money'],
  ['compra the products', 'buys the products'], ['compra', 'buys'],
  ['needs pero No produce', 'needs but does not produce'],
  ['needs', 'needs'], ['pero', 'but'], ['No produce', 'does not produce'],
  ['Tandpe of Change', 'Exchange rate'], ['tandpe of Change', 'exchange rate'],
  ['Change between', 'rate between'], ['change between', 'rate between'],
  ['Andes FC', 'When FC'], ['andes FC', 'when FC'],
  ['then 1 USD', 'then 1 USD'],
  ['Each hour that se approve', 'Each time a purchase or sale is approved'],
  ['se approve a compra o seeta', 'a purchase or sale is approved'],
  ['compra o seeta', 'purchase or sale'],
  ['seeta', 'sale'], ['Seeta', 'Sale'],
  ['Balance is updated', 'balance is updated'],
  ['Edit o Delete', 'edit or delete'], ['edit o delete', 'edit or delete'],
  ['cualquier Account', 'any account'],
  ['View sus Movements', 'view its movements'],
  ['sus Movements', 'its movements'], ['Movements', 'movements'],
  ['received se sum', 'received is added'], ['se sum', 'is added'],
  ['sum automatically', 'added automatically'],
  ['banco seleccionado', 'selected bank'], ['seleccionado', 'selected'],
  ['to the approve', 'upon approval'], ['approve la seeta', 'approving the sale'],
  ['No a Rate', 'Not a rate'], ['no a Rate', 'not a rate'],
  ['Rate of Change', 'exchange rate'], ['rate of Change', 'exchange rate'],
  ['especulativa', 'speculative'],
  ['Lo decides', 'It is decided'], ['lo decides', 'it is decided'],
  ['basandose', 'based'], ['in el Cost of life', 'on the cost of living'],
  ['Cost of life', 'cost of living'], ['cost of life', 'cost of living'],
  ['real', 'real'],
  ['cambien', 'change'], ['meanstivamente', 'significantly'],
  ['prices alla o aca', 'prices there or here'],
  ['alla', 'there'], ['aca', 'here'],
  ['No uploads nor low', 'does not go up or down'],
  ['uploads', 'up'], ['low', 'down'],
  ['lo update', 'it is updated'], ['update', 'updated'],
  ['Administrator', 'administrator'],
  ['financiera', 'financial'],
  ['unordad Accountable', 'accounting unit'], ['unordad', 'unit'],
  ['Accountable', 'accounting'], ['comunortaria', 'community'],
  ['vale', 'is worth'], ['algo', 'something'],
  ['terminos', 'terms'], ['terminos Locales', 'local terms'],
  ['Locales', 'local'], ['locales', 'local'],
  ['same in All', 'same in all'], ['same in all', 'same in all'],
  ['Nodes of la Federation', 'nodes of the federation'],
  ['can be change', 'can only be changed'],
  ['through a Proposal federated', 'through a federated proposal'],
  ['Proposal federated', 'federated proposal'],
  ['aprobada per Consensus', 'approved by consensus'],
  ['Consensus', 'consensus'],
  ['Ve a', 'Go to'], ['ve a', 'go to'],
  ['propose o votar', 'propose or vote'], ['propose', 'propose'],
  ['votar Changes', 'vote on changes'], ['votar', 'vote'],
  ['Changes', 'changes'], ['changes', 'changes'],
  ['No se encontr', 'Could not find'], ['no se encontr', 'could not find'],
  ['Request of admisi', 'admission request'], ['request of admisi', 'admission request'],
  ['admission request', 'admission request'],
  ['are not', 'could not'], ['Are not', 'Could not'],
  ['found', 'found'],
  ['Federation', 'federation'], ['federation', 'federation'],
  ['seeds', 'sells'], ['seeds', 'sells'],
  ['seede', 'sells'], ['seede su', 'sells their'],
  ['seede', 'sells'],
  ['le seede', 'sells to'], ['le', 'to them'],
  ['paid', 'pays'], ['paid in', 'pays in'],
  ['ese', 'that'],
  ['compra', 'buys'], ['compra the', 'buys the'],
  ['needs', 'needs'],
  ['produce', 'produce'],
  ['No produce', 'does not produce'],
  ['No', 'not'], ['no', 'not'],
  ['o', 'or'], ['O', 'or'],
  ['y', 'and'], ['Y', 'And'],
  ['la', 'the'], ['La', 'The'],
  ['el', 'the'], ['El', 'The'],
  ['los', 'the'], ['Los', 'The'],
  ['las', 'the'], ['Las', 'The'],
  ['un', 'a'], ['Un', 'A'],
  ['una', 'a'], ['Una', 'A'],
  ['en', 'in'], ['En', 'In'],
  ['con', 'with'], ['Con', 'With'],
  ['de', 'of'], ['De', 'Of'],
  ['del', 'of the'], ['Del', 'Of the'],
  ['al', 'to the'], ['Al', 'To the'],
  ['se', 'is'], ['Se', 'Is'],
  ['su', 'its'], ['Su', 'Its'],
  ['sus', 'its'], ['Sus', 'Its'],
  ['es', 'is'], ['Es', 'Is'],
  ['son', 'are'], ['Son', 'Are'],
  ['fue', 'was'], ['Fue', 'Was'],
  ['ya', 'already'], ['Ya', 'Already'],
  ['a', 'to'], ['A', 'To'],
  ['que', 'that'], ['Que', 'That'],
  ['para', 'for'], ['Para', 'For'],
  ['por', 'by'], ['Por', 'By'],
  ['como', 'as'], ['Como', 'As'],
  ['sin', 'without'], ['Sin', 'Without'],
  ['sobre', 'on'], ['Sobre', 'On'],
  ['entre', 'between'], ['Entre', 'Between'],
  ['hasta', 'until'], ['Hasta', 'Until'],
  ['desde', 'from'], ['Desde', 'From'],
  ['this', 'this'], ['This', 'This'],
  ['that', 'that'], ['That', 'That'],
  ['when', 'when'], ['When', 'When'],
  ['where', 'where'], ['Where', 'Where'],
  ['what', 'what'], ['What', 'What'],
  ['each', 'each'], ['Each', 'Each'],
  ['all', 'all'], ['All', 'All'],
  ['any', 'any'], ['Any', 'Any'],
  ['some', 'some'], ['Some', 'Some'],
  ['no', 'no'], ['No', 'No'],
  ['not', 'not'], ['Not', 'Not'],
  ['can', 'can'], ['Can', 'Can'],
  ['cannot', 'cannot'], ['Cannot', 'Cannot'],
  ['has', 'has'], ['Has', 'Has'],
  ['have', 'have'], ['Have', 'Have'],
  ['is', 'is'], ['Is', 'Is'],
  ['are', 'are'], ['Are', 'Are'],
  ['was', 'was'], ['Was', 'Was'],
  ['were', 'were'], ['Were', 'Were'],
  ['will', 'will'], ['Will', 'Will'],
  ['would', 'would'], ['Would', 'Would'],
  ['should', 'should'], ['Should', 'Should'],
  ['must', 'must'], ['Must', 'Must'],
  ['may', 'may'], ['May', 'May'],
  ['might', 'might'], ['Might', 'Might'],
  ['could', 'could'], ['Could', 'Could'],
];

function applyReplacements(text) {
  let result = text;
  for (const [from, to] of replacements) {
    result = result.split(from).join(to);
  }
  return result;
}

const files = fs.readdirSync(enDir).filter(f => f.endsWith('.json'));
let totalChanged = 0;

for (const file of files) {
  const filePath = path.join(enDir, file);
  const content = fs.readFileSync(filePath, 'utf8');
  const newContent = applyReplacements(content);
  if (newContent !== content) {
    fs.writeFileSync(filePath, newContent, 'utf8');
    totalChanged++;
    console.log(`Fixed: ${file}`);
  }
}

console.log(`\nDone. ${totalChanged} files modified.`);
