const fs = require('fs');
const path = require('path');

const enDir = path.join(__dirname, 'web', 'src', 'locales', 'en');

// Replacements sorted by length (longest first) to avoid partial matches
const replacements = [
  // Mangled words from the automatic dictionary
  ['Cnetworkit', 'Credit'], ['cnetworkit', 'credit'], ['Cnetworkito', 'Credit'],
  ['communorty', 'community'], ['Communorty', 'Community'], ['communorties', 'communities'],
  ['organorzation', 'organization'], ['Organorzation', 'Organization'],
  ['organorzations', 'organizations'], ['Organorzations', 'Organizations'],
  ['organorzacion', 'organization'], ['organorzaciones', 'organizations'],
  ['Configurestion', 'Configuration'], ['configurestion', 'configuration'],
  ['configuresdo', 'configured'], ['configuresdos', 'configured'],
  ['configuresdas', 'configured'], ['configuresda', 'configured'],
  ['configurescion', 'configuration'], ['Configurescion', 'Configuration'],
  ['configuresdos', 'configured'], ['preconfigurescion', 'preset'],
  ['preconfiguresciones', 'presets'],
  ['createste', 'create'], ['Createste', 'Create'],
  ['createstedra', 'will be created'], ['createsting', 'creating'],
  ['createsdo', 'created'], ['createsnda', 'creating'], ['createsndo', 'creating'],
  ['createstes', 'creates'], ['createstea', 'create'],
  ['dgoecto', 'direct'], ['Dgoecto', 'Direct'], ['dgoectly', 'directly'],
  ['Dgoect', 'Direct'], ['dgoect', 'direct'],
  ['desactiveteds', 'deactivated'], ['desactiveted', 'deactivated'],
  ['activeteds', 'activated'], ['activeted', 'activated'],
  ['desenableds', 'disabled'], ['desenabled', 'disabled'],
  ['requinetwork', 'required'], ['registenetwork', 'registered'],
  ['expinetwork', 'expired'], ['transfernetwork', 'transferred'],
  ['unorque', 'unique'], ['Unorque', 'Unique'], ['unorts', 'units'],
  ['formto', 'format'], ['pyesterday', 'payer'], ['thego', 'their'],
  ['comonth', 'comes'], ['inortializing', 'initializing'],
  ['denored', 'denied'], ['browbe', 'browser'], ['scannorng', 'scanning'],
  ['proceswithoutg', 'processing'], ['Confgom', 'Confirm'], ['confgomas', 'confirm'],
  ['Eviewything', 'Everything'], ['bevices', 'services'], ['Bevices', 'Services'],
  ['bevice', 'service'], ['Bevice', 'Service'],
  ['networkgoects', 'redirects'], ['configjoinstwork', 'configured'],
  ['pre-configjoinstwork', 'pre-configured'],
  ['deliview', 'deliver'], ['WgoeGuard', 'WireGuard'],
  ['Requgoes', 'Requires'], ['requgoe', 'require'],
  ['uwithoutg', 'using'], ['savelos', 'save them'],
  ['manhavelos', 'keep them'], ['deletelos', 'delete them'],
  ['acnetworkitar', 'credit'], ['acnetworkita', 'credits'], ['acnetworkitos', 'credits'],
  ['Caalreadypa', 'Cayapa'], ['caalreadypas', 'cayapas'],
  ['calengiveio', 'calendar'], ['Calengiveio', 'Calendar'],
  ['biodinamico', 'biodynamic'], ['Biodinamico', 'Biodynamic'],
  ['Planorficacion', 'Planning'], ['planorficacion', 'planning'],
  ['Stangived', 'standard'], ['energetica', 'energy'], ['energeticas', 'energy'],
  ['Viewificar', 'Verify'], ['viewificar', 'verify'],
  ['Viewificando', 'Verifying'], ['viewifica', 'verify'],
  ['Rbet', 'Restart'], ['rbets', 'restarts'], ['rbetsn', 'restart'],
  ['rbetsra', 'will restart'],
  ['runnorng', 'running'], ['respondn', 'respond'],
  ['controleler', 'controller'], ['updatecion', 'update'],
  ['updateda', 'updated'], ['updatedra', 'will update'],
  ['Downloadr', 'Download'], ['Downloadndo', 'Downloading'],
  ['downloadda', 'downloaded'],
  ['Restre', 'Restore'], ['restaurada', 'restored'], ['restauracion', 'restoration'],
  ['Loadsndo', 'Loading'], ['loadsndo', 'loading'],
  ['Esperado', 'Expected'], ['fallo', 'failed'],
  ['Is notpeculativa', 'non-speculative'], ['liquigive', 'liquidate'],
  ['Withdrawse', 'Withdrawal'], ['withdrawse', 'withdrawal'],
  ['descapitalizar', 'decapitalize'], ['Meall', 'Method'],
  ['cuotas', 'installments'], ['Monthsage', 'Message'], ['Monthsages', 'Messages'],
  ['Hourrios', 'Schedules'], ['hourrios', 'schedules'], ['hourrio', 'schedule'],
  ['medianorght', 'midnight'], ['sabatico', 'sabbath'], ['descanso', 'rest'],
  ['Ljoinss', 'Monday'], ['Viernes', 'Friday'], ['Sabado', 'Saturday'],
  ['domingo', 'Sunday'], ['Dias', 'Days'],
  ['Cnetworkito', 'Credit'], ['Debito', 'Debit'],
  ['cerrada', 'closed'], ['cerrado', 'closed'], ['Cerrado', 'Closed'],
  ['Comercio', 'Commerce'], ['comercio', 'commerce'],
  ['Trade', 'Commerce'], ['trade', 'commerce'],
  ['Arrancado', 'started'], ['arrancado', 'started'],
  ['detenordo', 'stopped'], ['detener', 'stop'],
  ['Minormum', 'Minimum'], ['minormum', 'minimum'],
  ['disponorbilidad', 'availability'], ['disponorbles', 'available'],
  ['disponorbles', 'available'],
  ['by/for', 'per'], ['By/for', 'Per'],
  ['about', 'about'], ['how often', 'how much'], ['How often', 'How much'],
  ['how often time', 'how often'], ['How often time', 'How often'],
  ['Tipico', 'Typical'], ['tipico', 'typical'],
  ['Asegurate', 'Make sure'], ['asegurate', 'make sure'],
  ['Antes', 'Before'], ['antes', 'before'],
  ['Guardalo', 'Save it'], ['guardalo', 'save it'],
  ['Guarda', 'Save'], ['guarda', 'save'],
  ['place sure', 'safe place'], ['Place sure', 'Safe place'],
  ['Frecuencia', 'Frequency'], ['frecuencia', 'frequency'],
  ['recomendada', 'recommended'], ['Recomendada', 'Recommended'],
  ['recomendado', 'recommended'], ['Recomendado', 'Recommended'],
  ['Tables', 'tables'], ['Tablas', 'tables'],
  ['Raises', 'Uploads'], ['raises', 'uploads'],
  ['Raises un', 'Uploads a'], ['raises un', 'uploads a'],
  ['No se duplican', 'are not duplicated'], ['No se', 'are not'],
  ['se addan', 'will be added'], ['se adda', 'will be added'],
  ['No exist', 'do not exist'], ['no exist', 'do not exist'],
  ['exist already', 'already exist'], ['ya exist', 'already exist'],
  ['No are', 'are not'], ['No se', 'are not'],
  ['oviewwritten', 'overwritten'], ['oview', 'over'],
  ['ON Conflict', 'ON CONFLICT'], ['Conflict', 'CONFLICT'],
  ['sure pero', 'safe but'], ['No replaces', 'does not replace'],
  ['Data currentes', 'current data'], ['data currentes', 'current data'],
  ['restauracion complete', 'complete restoration'],
  ['contacta', 'contact'], ['Adminorstrator', 'Administrator'],
  ['adminorstrador', 'administrator'], ['adminorstracion', 'administration'],
  ['Adminorstrative', 'Administrative'], ['adminorstrative', 'administrative'],
  ['oficina', 'office'], ['gestion', 'management'],
  ['metabolismo', 'metabolism'], ['basal', 'basal'],
  ['tools manuales', 'manual tools'], ['Tools manuales', 'Manual tools'],
  ['Esfuerzo', 'Effort'], ['esfuerzo', 'effort'],
  ['fisico', 'physical'], ['fisica', 'physical'],
  ['mental', 'mental'], ['sostenordo', 'sustained'],
  ['consumption metabolico', 'metabolic consumption'],
  ['metabolico', 'metabolic'], ['Consumption', 'Consumption'],
  ['kcal/h', 'kcal/h'], ['kWh/h', 'kWh/h'],
  ['construccion', 'construction'], ['loads', 'loads'],
  ['Alertr', 'Alert'], ['alertr', 'alert'],
  ['uso', 'usage'], ['tablets', 'tablets'], ['llegue', 'reaches'],
  ['Threshold', 'Threshold'], ['threshold', 'threshold'],
  ['blocked', 'blocked'], ['Blocked', 'Blocked'],
  ['y', 'and'], ['Y', 'And'],
  ['ven', 'see'], ['interfaz', 'interface'],
  ['Applies', 'Applies'], ['applies', 'applies'],
  ['contenedor', 'container'],
  ['recibidas', 'received'], ['appearan', 'appear'],
  ['cola', 'queue'], ['Cola', 'Queue'],
  ['Approval', 'Approval'], ['approval', 'approval'],
  ['Atest', 'Approve'], ['atest', 'approve'],
  ['Atencion', 'Attention'], ['atencion', 'attention'],
  ['Auditoria', 'Audit'], ['auditoria', 'audit'],
  ['Auto-aprobacion', 'Auto-approval'], ['activeda', 'activated'],
  ['Auto-Approve', 'Auto-approve'], ['without Revision Manual', 'without manual review'],
  ['Automaticos', 'Automatic'], ['automaticos', 'automatic'],
  ['savelos', 'save them'], ['Createste', 'Create'],
  ['how often time', 'how often'], ['manhavelos', 'keep them'],
  ['Before of', 'Before'], ['deletelos', 'delete them'],
  ['blockeds', 'locked'], ['Neview', 'Never'], ['neview', 'never'],
  ['deleted automaticamente', 'automatically deleted'],
  ['automaticamente', 'automatically'],
  ['Close', 'Close'], ['close', 'close'],
  ['Caalreadypa', 'Cayapa'], ['collective work', 'collective work'],
  ['Rotate Key', 'Rotate key'], ['rotate key', 'rotate key'],
  ['cada Transaction', 'each transaction'], ['Cada', 'Each'], ['cada', 'each'],
  ['only DESFgoe', 'only DESFire'], ['DESFgoe', 'DESFire'], ['Desfgoe', 'DESFire'],
  ['NTAG424', 'NTAG424'],
  ['Copy of Security', 'Backup'], ['copy of Security', 'backup'],
  ['copy of security', 'backup'], ['Copy of security', 'Backup'],
  ['correctamente', 'successfully'], ['createsdo', 'created'],
  ['funciones', 'functions'], ['estan', 'are'], ['Estan', 'Are'],
  ['downloadda', 'downloaded'], ['solicitado', 'requested'],
  ['proximos', 'next'], ['seconds', 'seconds'],
  ['sigue', 'continues'], ['Process', 'process'],
  ['Reloads', 'Reload'], ['unos minutes', 'a few minutes'],
  ['viewlo', 'see it'], ['Tariff base', 'Base rate'],
  ['Tariff', 'Tariff'], ['tariff', 'tariff'],
  ['Sum Total', 'Total sum'], ['sum total', 'total sum'],
  ['Basico', 'Basic'], ['basico', 'basic'],
  ['Types of dia', 'Day types'], ['dia', 'day'],
  ['activo', 'active'], ['Activo', 'Active'],
  ['Agricultural', 'Agricultural'], ['agricultural', 'agricultural'],
  ['basada', 'based'], ['Position', 'position'], ['position', 'position'],
  ['luna', 'moon'], ['constelaciones', 'constellations'],
  ['Constelaciones', 'Constellations'],
  ['raiz', 'root'], ['flor', 'flower'], ['hoja', 'leaf'], ['fruto', 'fruit'],
  ['Camphill', 'Camphill'], ['Findhorn', 'Findhorn'],
  ['practican', 'practice'], ['Agriculture', 'Agriculture'],
  ['Notas', 'Notes'], ['notas', 'notes'], ['about', 'about'],
  ['Practice', 'practice'], ['practice', 'practice'],
  ['Prstate', 'Loan'], ['prstate', 'loan'],
  ['Puede', 'Can'], ['puede', 'can'],
  ['have Card NFC', 'have NFC card'], ['View Audit', 'view audit'],
  ['Createste organorzations', 'create organizations'],
  ['Cancel', 'Cancel'], ['cancel', 'cancel'],
  ['Cancelando', 'Cancelling'], ['cancelando', 'cancelling'],
  ['cancelacion', 'cancellation'], ['Cancelacion', 'Cancellation'],
  ['enviada', 'sent'], ['dgoectly', 'directly'],
  ['Cannot connect', 'Cannot connect'], ['cannot connect', 'cannot connect'],
  ['esten', 'are'], ['Start', 'Start'], ['start', 'start'],
  ['Cannot Start', 'Cannot start'], ['cannot start', 'cannot start'],
  ['Mode of Card', 'Card mode'], ['mode of Card', 'card mode'],
  ['Only MIFARE', 'Only MIFARE'], ['only MIFARE', 'only MIFARE'],
  ['economicas', 'economical'], ['seguras', 'secure'],
  ['Dual', 'Dual'], ['dual', 'dual'], ['Recomendado', 'Recommended'],
  ['Type of Card', 'Card type'], ['type of Card', 'card type'],
  ['Configures that', 'Configure which'], ['configures that', 'configure which'],
  ['types of Card', 'card types'], ['accepts', 'accepts'],
  ['Venezuela', 'Venezuela'], ['venezuela', 'Venezuela'],
  ['cards normal', 'normal cards'], ['son mas', 'are more'],
  ['faciles', 'easier'], ['consegugo', 'obtain'],
  ['proteccion', 'protection'], ['against', 'against'],
  ['clonacion', 'cloning'], ['UID', 'UID'], ['uid', 'UID'],
  ['Categoria', 'Category'], ['categoria', 'category'],
  ['optional', 'optional'], ['Optional', 'Optional'],
  ['Caalreadypa', 'Cayapa'], ['Asistencia', 'Attendance'],
  ['asistencia', 'attendance'], ['jornadas', 'sessions'],
  ['Communorty work', 'community work'], ['communorty work', 'community work'],
  ['criptograficas', 'cryptographic'], ['Code QR', 'QR code'],
  ['alternativa', 'alternative'], ['without NFC', 'without NFC'],
  ['ambos', 'both'], ['tengas', 'have'], ['Available', 'available'],
  ['Deactivete', 'Deactivate'], ['deactivete', 'deactivate'],
  ['How works', 'How it works'], ['how works', 'how it works'],
  ['Coordinator', 'Coordinator'], ['coordinator', 'coordinator'],
  ['abre', 'opens'], ['check-in', 'check-in'],
  ['participantes', 'participants'], ['se registran', 'register'],
  ['acercando', 'approaching'], ['mostrando', 'showing'],
  ['manager', 'manager'], ['calcula', 'calculates'],
  ['hours', 'hours'], ['factor of esfuerzo', 'effort factor'],
  ['Change tariffs', 'Change tariffs'], ['change tariffs', 'change tariffs'],
  ['Proput', 'Propose'], ['proput', 'propose'],
  ['affects', 'affects'], ['se calcula', 'is calculated'],
  ['Value of the Work', 'value of work'], ['value of the Work', 'value of work'],
  ['Review', 'Review'], ['review', 'review'],
  ['Approval Up', 'approval queue'], ['approval Up', 'approval queue'],
  ['updates', 'updates'], ['Updates', 'Updates'],
  ['State/Stayour', 'Status'], ['state/Stayour', 'status'],
  ['Monthsage when', 'Message when'], ['Trade this Closed', 'Commerce is closed'],
  ['Trade this', 'Commerce is'], ['trade this', 'commerce is'],
  ['intenta', 'attempts'], ['transar', 'transact'],
  ['fuera', 'outside'], ['hourrio', 'schedule'],
  ['allowed', 'allowed'], ['Transactions', 'transactions'],
  ['estan closeds', 'are closed'], ['by/for descanso', 'for rest'],
  ['Cluster', 'Cluster'], ['cluster', 'cluster'],
  ['buen', 'good'], ['necesita', 'needs'], ['atencion', 'attention'],
  ['urpeoplemente', 'urgently'], ['nodes', 'nodes'],
  ['entidad collective', 'collective entity'], ['colectiva', 'collective'],
  ['Comercio cerrado', 'Commerce closed'], ['comercio cerrado', 'commerce closed'],
  ['Hourrios of Trade', 'Commerce schedules'], ['hourrios of Trade', 'commerce schedules'],
  ['is allowedn', 'are allowed'], ['Transactions in', 'transactions in'],
  ['bloquear', 'block'], ['dias completos', 'full days'],
  ['rangos hourrios', 'time ranges'], ['ventanas', 'windows'],
  ['cruzan', 'cross'], ['viernes', 'friday'],
  ['putse el sol', 'sunset'], ['sabado', 'saturday'],
  ['Work Comunortario', 'Community work'], ['work comunortario', 'community work'],
  ['Registra Sessions', 'Register sessions'], ['registra sessions', 'register sessions'],
  ['caalreadypas', 'cayapas'], ['mingas', 'mingas'], ['voluntariados', 'volunteer work'],
  ['Soporta', 'Supports'], ['soporta', 'supports'],
  ['valoracion', 'valuation'], ['in hours', 'in hours'],
  ['without valoracion', 'no valuation'], ['requgoe Approval', 'require approval'],
  ['evitar', 'prevent'], ['inflacion', 'inflation'],
  ['unorlateral', 'unilateral'], ['cnetworkitos', 'credits'],
  ['Configurescion', 'Configuration'], ['guardada', 'saved'],
  ['guardada correctamente', 'saved successfully'],
  ['Confgomas', 'Confirm'], ['confgomas', 'confirm'],
  ['Stop el Node', 'stop the node'], ['Rbet el Node', 'restart the node'],
  ['Conectando', 'Connecting'], ['conectando', 'connecting'],
  ['Could not Load', 'Could not load'], ['could not Load', 'could not load'],
  ['Could not viewificar', 'Could not verify'], ['could not viewificar', 'could not verify'],
  ['repository Remote', 'remote repository'], ['repository remote', 'remote repository'],
  ['Account for Quorum', 'Counts for quorum'], ['Account for', 'Counts for'],
  ['account for', 'counts for'], ['Minormum of Members', 'Minimum of members'],
  ['necessarys', 'necessary'], ['valigive', 'valid'], ['Voting', 'voting'],
  ['voting', 'voting'], ['CPU', 'CPU'], ['RAM', 'RAM'],
  ['Ahour', 'Now'], ['ahour', 'now'], ['profile', 'profile'], ['Profile', 'Profile'],
  ['new profile', 'new profile'], ['New profile', 'New profile'],
  ['sesion', 'session'], ['Sesion', 'Session'], ['session', 'session'],
  ['Creates org', 'Creates org'], ['Createsndo', 'Creating'], ['createsndo', 'creating'],
  ['exportando Tables', 'exporting tables'], ['exportando', 'exporting'],
  ['Cnetworkito', 'Credit'], ['Limit of Cnetworkit', 'Credit limit'],
  ['Limit of Debit', 'Debit limit'], ['How often puede', 'How much can'],
  ['How often', 'How much'], ['how often puede', 'how much can'],
  ['Duty', 'owe'], ['duty', 'owe'], ['Duty (Negative)', 'owe (negative)'],
  ['accumulate (Positive)', 'accumulate (positive)'],
  ['accumulate la', 'accumulate'], ['Duty la', 'owe'],
  ['Comercio nodes', 'Cross-node commerce'], ['comercio nodes', 'cross-node commerce'],
  ['Trade between Nodes', 'Commerce between nodes'],
  ['trade between Nodes', 'commerce between nodes'],
  ['Cruza medianorght', 'Crosses midnight'], ['cruza medianorght', 'crosses midnight'],
  ['viernes 18:00 until domingo 06:00', 'friday 18:00 until sunday 06:00'],
  ['cruza medianorght', 'crosses midnight'],
  ['Abreviatura', 'Abbreviation'], ['abreviatura', 'abbreviation'],
  ['Abreviatura corta', 'Short abbreviation'], ['corta', 'short'],
  ['Appears in', 'Appears in'], ['appears in', 'appears in'],
  ['balances', 'balances'], ['transfers', 'transfers'], ['prices', 'prices'],
  ['Barter/Barter', 'Barter'], ['barter/barter', 'barter'],
  ['Time', 'Hour'], ['time', 'hour'],
  ['Punto', 'Point'], ['punto', 'point'],
  ['texts explicativos', 'explanatory texts'], ['sitio Public', 'public site'],
  ['Commit current', 'Current commit'], ['commit current', 'current commit'],
  ['Commit installdo', 'Installed commit'], ['commit installdo', 'installed commit'],
  ['Profile Current', 'Current profile'], ['profile Current', 'current profile'],
  ['Custom', 'Custom'], ['custom', 'custom'],
  ['Sum total diaria', 'Daily total sum'], ['sum total diaria', 'daily total sum'],
  ['Database', 'Database'], ['database', 'database'],
  ['Dia', 'Day'], ['dia', 'day'],
  ['Dia of la week', 'Day of the week'], ['dia of la week', 'day of the week'],
  ['Dias by/for month', 'Days per month'], ['dias by/for month', 'days per month'],
  ['Dias of Work', 'Work days'], ['dias of Work', 'work days'],
  ['Income base', 'base income'], ['income base', 'base income'],
  ['funciones of Database', 'database functions'],
  ['only read', 'read-only'], ['Only read', 'Read-only'],
  ['Cannotn', 'Cannot'], ['cannotn', 'cannot'],
  ['modify Nodes', 'modify nodes'], ['Download scripts', 'download scripts'],
  ['Download', 'Download'], ['download', 'download'],
  ['mode demostracion', 'demo mode'], ['Mode demostracion', 'Demo mode'],
  ['inherited automaticamente', 'automatically inherited'],
  ['is inherited', 'is inherited'], ['inherited of', 'inherited from'],
  ['Node parent', 'parent node'], ['node parent', 'parent node'],
  ['Cannot modify', 'Cannot modify'], ['cannot modify', 'cannot modify'],
  ['changes of Domain', 'changes domain'], ['changes of domain', 'changes domain'],
  ['updatedra', 'will update'], ['proxima time', 'next time'],
  ['se restart', 'restarts'], ['se Restart', 'restarts'],
  ['dentro of', 'inside'], ['Dentro of', 'Inside'],
  ['estan desenableds', 'are disabled'],
  ['No usa', 'Does not use'], ['no usa', 'does not use'],
  ['Ube/Password', 'User/Password'], ['ube/Password', 'user/password'],
  ['su place', 'its place'], ['muestra buttons', 'shows buttons'],
  ['rolees disponorbles', 'available roles'],
  ['How works el Login', 'How demo login works'],
  ['enters dgoectly', 'enters directly'], ['ese role', 'that role'],
  ['Password', 'Password'], ['password', 'password'],
  ['gestionar', 'manage'], ['usa el', 'use the'],
  ['principal', 'main'], ['Principal', 'Main'],
  ['modificar', 'modify'], ['Name, la Currency', 'name, currency'],
  ['other Settings internal', 'other internal settings'],
  ['Domain this blocked', 'domain is locked'],
  ['is inherited of', 'is inherited from'],
  ['Changes rbetsn', 'changes restart'],
  ['Preconfigurescion of the demo', 'Demo preset'],
  ['preconfigurescion of the demo', 'demo preset'],
  ['Choose el Profile', 'Choose the profile'], ['choose el', 'choose the'],
  ['inortializesra', 'will initialize'], ['Cada Profile loads', 'each profile loads'],
  ['Data, hourrios y Rules', 'data, schedules and rules'],
  ['differents segun', 'different according to'],
  ['filosofia of la Communorty', 'community philosophy'],
  ['reset Node demo', 'reset demo node'], ['Reset Node demo', 'Reset demo node'],
  ['reinorciado', 'restarted'], ['Data se estan recreatesndo', 'data is being recreated'],
  ['preconfigurescion seleccionada', 'selected preset'],
  ['Junta Dgoectiva', 'Directive Board'], ['junta dgoectiva', 'directive board'],
  ['presidente', 'president'], ['vicepresidente', 'vice-president'],
  ['treasurer', 'treasurer'], ['secretary', 'secretary'], ['vocales', 'members'],
  ['farmeres', 'farmers'], ['productres', 'producers'], ['artesanos', 'artisans'],
  ['member new', 'new member'], ['Member new', 'New member'],
  ['cooperativa', 'cooperative'], ['panaderia', 'bakery'],
  ['Workshop', 'workshop'], ['tienda', 'store'], ['centro of health', 'health center'],
  ['access total', 'full access'], ['Rbet nor', 'restart nor'],
  ['Configure el', 'configure the'], ['from aqui', 'from here'],
  ['Vista of Demostracion', 'Demo view'], ['vista of demostracion', 'demo view'],
  ['Contabilidad departamental', 'Departmental accounting'],
  ['contabilidad departamental', 'departmental accounting'],
  ['Descripcion', 'Description'], ['descripcion', 'description'],
  ['Explica that means', 'Explains what means'], ['explica that', 'explains what'],
  ['Member pleno', 'full member'], ['member pleno', 'full member'],
  ['All the derechos', 'all rights'], ['all the derechos', 'all rights'],
  ['high seguridad', 'high security'], ['seguridad', 'security'],
  ['challenge-response', 'challenge-response'],
  ['RAM detectada', 'Detected RAM'], ['ram detectada', 'detected RAM'],
  ['Change dgoecto', 'Direct change'], ['change dgoecto', 'direct change'],
  ['authorizado', 'authorized'],
  ['Memogo', 'Memory'], ['memogo', 'memory'],
  ['escritura', 'writing'], ['Percentage of RAM', 'Percentage of RAM'],
  ['Write without', 'Write without'], ['write without', 'write without'],
  ['Without', 'Without'], ['without', 'without'],
  ['Y without Port', 'And without port'], ['y without Port', 'and without port'],
  ['Is used for', 'It is used for'], ['is used for', 'it is used for'],
  ['Federation, URLs publicas', 'federation, public URLs'],
  ['e identidad', 'and identity'], ['identidad of the Node', 'node identity'],
  ['changess el Domain', 'change the domain'], ['changes el', 'changes the'],
  ['Data Locales', 'local data'], ['data Locales', 'local data'],
  ['se conbevan', 'are preserved'], ['No se pierde nada', 'nothing is lost'],
  ['New Domain', 'new domain'], ['new Domain', 'new domain'],
  ['apunte a', 'points to'], ['this Beview', 'this server'],
  ['Before of Save', 'before saving'], ['before of Save', 'before saving'],
  ['Download Copy of Security', 'Download backup'],
  ['download Copy of Security', 'download backup'],
  ['Downloadr Backup', 'Download backup'], ['downloadr Backup', 'download backup'],
  ['File JSON', 'JSON file'], ['file JSON', 'JSON file'],
  ['All the Tables y Data', 'all tables and data'],
  ['Database of the Node', 'node database'], ['database of the Node', 'node database'],
  ['This incluye', 'This includes'], ['this incluye', 'this includes'],
  ['Ubes', 'Users'], ['ubes', 'users'], ['Products', 'products'],
  ['interchanges', 'exchanges'], ['Pages publicas', 'public pages'],
  ['pages publicas', 'public pages'],
  ['File in un place', 'file in a safe place'], ['file in un place', 'file in a safe place'],
  ['Factor of esfuerzo Agricultural', 'Agricultural effort factor'],
  ['factor of esfuerzo Agricultural', 'agricultural effort factor'],
  ['consumption metabolico agricultural', 'agricultural metabolic consumption'],
  ['normal', 'normal'], ['Normal', 'Normal'],
  ['mas by/for Work fisico', 'more for physical work'],
  ['Factores of esfuerzo', 'Effort factors'], ['factores of esfuerzo', 'effort factors'],
  ['Multiplican el Cost', 'Multiply the cost'], ['multiplican el Cost', 'multiply the cost'],
  ['Cost of the Work', 'cost of work'], ['cost of the Work', 'cost of work'],
  ['segun su dificultad', 'according to its difficulty'],
  ['dificultad fisica o mental', 'physical or mental difficulty'],
  ['esfuerzo base', 'base effort'], ['Mas High', 'Higher'], ['mas High', 'higher'],
  ['mas Hard', 'harder'], ['mas Payment', 'more pay'],
  ['Dia of fin', 'End day'], ['dia of fin', 'end day'],
  ['Dia of start', 'Start day'], ['dia of start', 'start day'],
  ['bloqueo va from', 'block goes from'],
  ['dia of start a la Time of start', 'start day at start time'],
  ['dia a la Time of fin', 'day at end time'],
  ['Time of fin', 'End time'], ['Time of start', 'Start time'],
  ['time of fin', 'end time'], ['time of start', 'start time'],
  ['Tariff Energetica', 'Energy tariff'], ['tariff Energetica', 'energy tariff'],
  ['Error to the', 'Error'], ['error to the', 'error'],
  ['Add Prohibition', 'add prohibition'], ['Approve', 'approve'],
  ['Remove Profile', 'remove profile'], ['remove Profile', 'remove profile'],
  ['request backup', 'request backup'], ['Request backup', 'Request backup'],
  ['saving Configurestion', 'saving configuration'],
  ['saving Monthsage', 'saving message'],
  ['Cada 24 hours', 'Every 24 hours'], ['cada 24 hours', 'every 24 hours'],
  ['Puente externo', 'External bridge'], ['puente externo', 'external bridge'],
  ['sharing Federated', 'federated sharing'], ['Sharing Federated', 'Federated sharing'],
  ['Nodes federateds', 'federated nodes'], ['nodes federateds', 'federated nodes'],
  ['same Profile', 'same profile'], ['compartn', 'share'],
  ['prohibitions of Products', 'product prohibitions'],
  ['Federacion', 'Federation'], ['federacion', 'federation'],
  ['Fetch', 'Fetch'], ['fetch', 'fetch'],
  ['git fetch fallo', 'git fetch failed'],
  ['review GIT_TOKEN', 'check GIT_TOKEN'],
  ['flor', 'flower'], ['manzanorlla', 'chamomile'], ['calendula', 'calendula'],
  ['Alimentacion', 'Food'], ['alimentacion', 'food'],
  ['Energy for producgo Food diaria', 'Energy to produce daily food'],
  ['energy for producgo Food diaria', 'energy to produce daily food'],
  ['Agroecological', 'Agroecological'], ['agroecological', 'agroecological'],
  ['Frecuencia (hours)', 'Frequency (hours)'], ['frecuencia (hours)', 'frequency (hours)'],
  ['FRNE', 'FRNE'], ['Exit Justa', 'Fair Exit'], ['exit Justa', 'fair exit'],
  ['Fago exit', 'Fair exit'], ['fago exit', 'fair exit'],
  ['resuelve how', 'resolves how'], ['liquigive', 'liquidate'],
  ['form Is notpeculativa', 'non-speculative way'],
  ['vivienda of un socio', 'a member\'s housing'],
  ['decides withdrawse', 'decides to withdraw'],
  ['without descapitalizar el Fund comun', 'without decapitalizing the common fund'],
  ['socio receives', 'member receives'], ['Value of su Contribution original', 'value of their original contribution'],
  ['mejoras', 'improvements'], ['No el Value speculative', 'not the speculative value'],
  ['Value speculative', 'speculative value'], ['value speculative', 'speculative value'],
  ['Property', 'property'], ['property', 'property'],
  ['pertenece a la Communorty', 'belongs to the community'],
  ['Total a Pay', 'Total to pay'], ['total a Pay', 'total to pay'],
  ['Contribution original', 'original contribution'], ['contribution original', 'original contribution'],
  ['Value of mejoras', 'value of improvements'], ['value of mejoras', 'value of improvements'],
  ['valorado by/for Assembly', 'valued by assembly'],
  ['No se paid', 'is not paid'], ['se paid', 'is paid'],
  ['Payment Unorque', 'Unique payment'], ['payment Unorque', 'unique payment'],
  ['Transfer a New socio', 'transfer to a new member'],
  ['transfer a New socio', 'transfer to a new member'],
  ['fruto', 'fruit'], ['tomate', 'tomato'], ['pimenton', 'bell pepper'],
  ['General', 'General'], ['general', 'general'],
  ['Go a Terminales NFC', 'Go to NFC terminals'], ['go a Terminales NFC', 'go to NFC terminals'],
  ['Gramos', 'Grams'], ['gramos', 'grams'],
  ['Tiene Voice', 'Has voice'], ['tiene Voice', 'has voice'],
  ['Puede speak y give su Opinoron', 'Can speak and give their opinion'],
  ['puede speak y give su Opinoron', 'can speak and give their opinion'],
  ['assemblys', 'assemblies'],
  ['Tiene Vote', 'Has vote'], ['tiene Vote', 'has vote'],
  ['Puede votar', 'Can vote'], ['puede votar', 'can vote'],
  ['the Members with Vote formn part of la Assembly', 'members with vote are part of the assembly'],
  ['hostname o IP', 'hostname or IP'],
  ['Hours by/for dia', 'Hours per day'], ['hours by/for dia', 'hours per day'],
  ['Hours of Work Stangived', 'Standard work hours'], ['hours of Work Stangived', 'standard work hours'],
  ['basket of 8 kWh', 'basket of 8 kWh'], ['Tariff base es', 'base rate is'],
  ['Vivienda/domonthtico', 'Housing/domestic'], ['vivienda/domonthtico', 'housing/domestic'],
  ['Energy amortizada', 'Amortized energy'], ['energy amortizada', 'amortized energy'],
  ['vivienda y cocina', 'housing and cooking'],
  ['How Add un Node', 'How to add a node'], ['how Add un Node', 'how to add a node'],
  ['Icono', 'Icon'], ['icono', 'icon'],
  ['ID y Name', 'ID and name'], ['id y Name', 'id and name'],
  ['Name e IP', 'Name and IP'], ['name e IP', 'name and IP'],
  ['Important', 'Important'], ['important', 'important'],
  ['Mejoras', 'Improvements'], ['mejoras', 'improvements'],
  ['New Rule of hourrio', 'New schedule rule'], ['new Rule of hourrio', 'new schedule rule'],
  ['New prestamo of Seeds', 'New seed loan'], ['new prestamo of Seeds', 'new seed loan'],
  ['New Session of Work', 'New work session'], ['new Session of Work', 'new work session'],
  ['Cards NFC', 'NFC cards'], ['cards NFC', 'nfc cards'],
  ['NFC habilitado', 'NFC enabled'], ['nfc habilitado', 'nfc enabled'],
  ['cards criptograficas', 'cryptographic cards'],
  ['Terminales NFC', 'NFC terminals'], ['terminales NFC', 'nfc terminals'],
  ['gestion of cards NFC', 'NFC card management'],
  ['has been unorficado', 'has been unified'],
  ['Page of', 'page of'], ['page of', 'page of'],
  ['Alli you can', 'There you can'], ['alli you can', 'there you can'],
  ['Register y provisionar', 'register and provision'],
  ['register y provisionar', 'register and provision'],
  ['cards of the 3 tipos soportados', '3 supported card types'],
  ['No Nodes adicionales', 'No additional nodes'], ['no Nodes adicionales', 'no additional nodes'],
  ['configuresdos', 'configured'], ['Only estas usando', 'You are only using'],
  ['only estas usando', 'you are only using'],
  ['Node principal', 'main node'], ['node principal', 'main node'],
  ['There is no backups', 'There are no backups'], ['there is no backups', 'there are no backups'],
  ['automaticos todavia', 'automatic backups yet'],
  ['No entrys', 'No entries'], ['no entrys', 'no entries'],
  ['Anade dias manually', 'Add days manually'], ['anade dias manually', 'add days manually'],
  ['se generaran automaticamente', 'they will be generated automatically'],
  ['No profilees of fe', 'No faith profiles configured'], ['no profilees of fe', 'no faith profiles configured'],
  ['configuresdos', 'configured'],
  ['No Requests of exit', 'No exit requests'], ['no Requests of exit', 'no exit requests'],
  ['registradas', 'registered'],
  ['No se encontro', 'Could not find'], ['no se encontro', 'could not find'],
  ['There is no prestamos', 'There are no loans'], ['there is no prestamos', 'there are no loans'],
  ['prestamos registrados', 'loans registered'],
  ['Without Logs', 'No logs'], ['without Logs', 'no logs'],
  ['disponorbles', 'available'],
  ['Cannotn obhave', 'Cannot get'], ['cannotn obhave', 'cannot get'],
  ['Logs', 'logs'], ['logs', 'logs'],
  ['No leveles', 'No levels'], ['no leveles', 'no levels'],
  ['leveles of Member', 'member levels'], ['leveles of Organorzation', 'organization levels'],
  ['configuresdos', 'configured'],
  ['Permission for change', 'permission to change'], ['permission for change', 'permission to change'],
  ['Permission for Update', 'permission to update'], ['permission for Update', 'permission to update'],
  ['Update el Node', 'update the node'], ['update el Node', 'update the node'],
  ['There is no prohibitions', 'There are no prohibitions'], ['there is no prohibitions', 'there are no prohibitions'],
  ['configuresdas', 'configured'],
  ['Without Region', 'No region'], ['without Region', 'no region'],
  ['No Rules', 'No rules'], ['no Rules', 'no rules'],
  ['All the Transactions', 'All transactions'], ['all the Transactions', 'all transactions'],
  ['estan permitidas', 'are allowed'],
  ['No Sessions', 'No sessions'], ['no Sessions', 'no sessions'],
  ['Communorty work registradas', 'community work sessions registered'],
  ['communorty work registradas', 'community work sessions registered'],
  ['Without valoracion', 'No valuation'], ['without valoracion', 'no valuation'],
  ['already this arrancado', 'is already started'], ['Already this', 'is already'],
  ['already this detenordo', 'is already stopped'],
  ['Console of the Node', 'Node console'], ['console of the Node', 'node console'],
  ['Node createsdo', 'Node created'], ['node createsdo', 'node created'],
  ['Download el Script', 'Download the script'], ['download el Script', 'download the script'],
  ['ejecutalo in el Beview Remote', 'run it on the remote server'],
  ['ejecutalo', 'run it'], ['Beview Remote', 'remote server'], ['beview Remote', 'remote server'],
  ['Dia node', 'Node day'], ['dia node', 'node day'],
  ['dias Node No se tralow la Land', 'node days do not move the land'],
  ['dias Node', 'node days'], ['tralow', 'move'], ['Land', 'land'], ['land', 'land'],
];

function applyReplacements(text) {
  let result = text;
  for (const [from, to] of replacements) {
    // Use split/join for literal string replacement (faster than regex for simple strings)
    result = result.split(from).join(to);
  }
  return result;
}

const files = fs.readdirSync(enDir).filter(f => f.endsWith('.json'));
let totalChanged = 0;

for (const file of files) {
  const filePath = path.join(enDir, file);
  const content = fs.readFileSync(filePath, 'utf8');
  const newContent = applyReplacements(content);
  if (newContent !== content) {
    fs.writeFileSync(filePath, newContent, 'utf8');
    totalChanged++;
    console.log(`Fixed: ${file}`);
  }
}

console.log(`\nDone. ${totalChanged} files modified.`);
