const fs = require('fs');
const path = require('path');

const enDir = path.join(__dirname, 'web', 'src', 'locales', 'en');

// Dictionary: [spanish_word, english_word] - will use word boundaries
const dict = {
  // Articles and prepositions
  'el':'the','la':'the','los':'the','las':'the','un':'a','una':'a','unos':'some','unas':'some',
  'de':'of','del':'of the','al':'to the','en':'in','con':'with','sin':'without',
  'por':'by','para':'for','sobre':'on','entre':'between','hasta':'until','desde':'from',
  'hacia':'towards','contra':'against','según':'according to','tras':'after',
  // Conjunctions
  'y':'and','o':'or','pero':'but','sino':'but rather','porque':'because','pues':'since',
  'aunque':'although','mientras':'while','si':'if','cuando':'when','donde':'where',
  'como':'as','que':'that','cual':'which','quien':'who','cuyo':'whose',
  // Pronouns
  'él':'he','ella':'she','ello':'it','ellos':'they','ellas':'they',
  'nosotros':'we','vosotros':'you','ustedes':'you','usted':'you',
  'me':'me','te':'you','se':'itself','le':'him','les':'them',
  'lo':'it','la':'it','los':'them','las':'them',
  'su':'its','sus':'its','mi':'my','mis':'my','tu':'your','tus':'your',
  'nuestro':'our','nuestra':'our','vuestro':'your','vuestra':'your',
  'este':'this','esta':'this','estos':'these','estas':'these',
  'ese':'that','esa':'that','esos':'those','esas':'those',
  'aquel':'that','aquella':'that','esto':'this','eso':'that','aquello':'that',
  // Common verbs
  'es':'is','son':'are','era':'was','eran':'were','fue':'was','fueron':'were',
  'será':'will be','serán':'will be','es':'is','está':'is','están':'are',
  'estaba':'was','estaban':'were','estará':'will be','estarán':'will be',
  'tiene':'has','tienen':'have','tengo':'have','tenemos':'have',
  'tenía':'had','tenían':'had','tendrá':'will have','tendrán':'will have',
  'puede':'can','pueden':'can','puedo':'can','podemos':'can',
  'podía':'could','podían':'could','podrá':'will be able','podrán':'will be able',
  'debe':'must','deben':'must','debo':'must','debemos':'must',
  'hace':'makes','hacen':'make','hago':'make','hacemos':'make',
  'ha':'has','han':'have','he':'have','hemos':'have',
  'se':'is','se':'itself',
  'va':'goes','van':'go','voy':'go','vamos':'go',
  'viene':'comes','vienen':'come','vengo':'come','venimos':'come',
  'crea':'creates','crean':'create','creo':'create','creamos':'create',
  'creó':'created','crearon':'created','creará':'will create','crearán':'will create',
  'guarda':'saves','guardan':'save','guardo':'save','guardamos':'save',
  'guardó':'saved','guardaron':'saved','guardará':'will save',
  'carga':'loads','cargan':'load','cargo':'load','cargamos':'load',
  'descarga':'downloads','descargan':'download','descargo':'download',
  'envía':'sends','envían':'send','envío':'send','enviamos':'send',
  'envió':'sent','enviaron':'sent','enviará':'will send',
  'recibe':'receives','reciben':'receive','recibo':'receive','recibimos':'receive',
  'recibió':'received','recibieron':'received','recibirá':'will receive',
  'muestra':'shows','muestran':'show','muestro':'show','mostramos':'show',
  'oculta':'hides','ocultan':'hide','oculto':'hide',
  'busca':'searches','buscan':'search','busco':'search','buscamos':'search',
  'encuentra':'finds','encuentran':'find','encuentro':'find',
  'agrega':'adds','agregan':'add','agrego':'add','agregamos':'add',
  'quita':'removes','quitan':'remove','quito':'remove',
  'selecciona':'selects','seleccionan':'select','selecciono':'select',
  'elige':'chooses','eligen':'choose','elijo':'choose',
  'decide':'decides','deciden':'decide','decido':'decide',
  'permite':'allows','permiten':'allow','permito':'allow',
  'prohíbe':'prohibits','prohíben':'prohibit',
  'requiere':'requires','requieren':'require','requiero':'require',
  'necesita':'needs','necesitan':'need','necesito':'need',
  'funciona':'works','funcionan':'work','funciono':'work',
  'aparece':'appears','aparecen':'appear','aparezco':'appear',
  'desaparece':'disappears','desaparecen':'disappear',
  'existe':'exists','existen':'exist','existo':'exist',
  'sucede':'happens','suceden':'happen','sucede':'happens',
  'ocurre':'occurs','ocurren':'occur',
  'llega':'arrives','llegan':'arrive','llego':'arrive',
  'sale':'exits','salen':'exit','salgo':'exit',
  'entra':'enters','entran':'enter','entro':'enter',
  'aumenta':'increases','aumentan':'increase','aumento':'increase',
  'disminuye':'decreases','disminuyen':'decrease',
  'crece':'grows','crecen':'grow','crezco':'grow',
  'mejora':'improves','mejoran':'improve','mejoro':'improve',
  'corregir':'correct','arreglar':'fix','resolver':'resolve','solucionar':'solve',
  'aceptar':'accept','rechazar':'reject','cancelar':'cancel',
  'verificar':'verify','revisar':'review','alertar':'alert',
  'avisar':'notify','comunicar':'communicate','informar':'inform',
  'reportar':'report','restaurar':'restore','exportar':'export','importar':'import',
  'probar':'test','ofrecer':'offer','proporcionar':'provide','entregar':'deliver',
  'comprar':'buy','vender':'sell','pagar':'pay','deber':'owe',
  'prestar':'lend','devolver':'return','retirar':'withdraw',
  'ahorrar':'save','invertir':'invest','gastar':'spend',
  'reclamar':'claim','solicitar':'request','crear':'create',
  'editar':'edit','borrar':'delete','eliminar':'delete','guardar':'save',
  'cargar':'load','descargar':'download','subir':'upload',
  'instalar':'install','configurar':'configure','activar':'activate',
  'desactivar':'deactivate','conectar':'connect','desconectar':'disconnect',
  'iniciar':'start','reiniciar':'restart','detener':'stop','continuar':'continue',
  'pausar':'pause','reanudar':'resume','comenzar':'begin','terminar':'end',
  'finalizar':'finish','completar':'complete','actualizar':'update','modificar':'modify',
  'cambiar':'change','mover':'move','copiar':'copy','abrir':'open','cerrar':'close',
  'ver':'view','mostrar':'show','usar':'use','aprender':'learn','enseñar':'teach',
  'comprender':'understand','entender':'understand','recordar':'remember',
  'olvidar':'forget','saber':'know','pensar':'think','creer':'believe',
  'hablar':'speak','decir':'say','escuchar':'listen','leer':'read','escribir':'write',
  // Common words
  'verdadero':'true','falso':'false','siempre':'always','nunca':'never',
  'hoy':'today','ayer':'yesterday','mañana':'tomorrow',
  'semana':'week','mes':'month','año':'year','día':'day','hora':'hour',
  'minuto':'minute','segundo':'second','tiempo':'time','vez':'time','veces':'times',
  'lugar':'place','forma':'form','manera':'way','parte':'part',
  'mundo':'world','vida':'life','país':'country','ciudad':'city','gente':'people',
  'persona':'person','familia':'family','casa':'house','hogar':'home',
  'trabajo':'work','dinero':'money','cuenta':'account','saldo':'balance',
  'crédito':'credit','débito':'debit','deuda':'debt',
  'impuesto':'tax','impuestos':'taxes','fondo':'fund','fondos':'funds',
  'presupuesto':'budget','gasto':'expense','gastos':'expenses',
  'ingreso':'income','ingresos':'income','costo':'cost',
  'precio':'price','precios':'prices','producto':'product','productos':'products',
  'servicio':'service','servicios':'services','usuario':'user','usuarios':'users',
  'miembro':'member','miembros':'members',
  'organización':'organization','organizaciones':'organizations',
  'comunidad':'community','comunidades':'communities',
  'asamblea':'assembly','sesión':'session','sesiones':'sessions',
  'propuesta':'proposal','propuestas':'proposals',
  'votación':'voting','voto':'vote','votos':'votes',
  'decisión':'decision','decisiones':'decisions',
  'regla':'rule','reglas':'rules','permiso':'permission','permisos':'permissions',
  'rol':'role','roles':'roles','nivel':'level','niveles':'levels',
  'sistema':'system','sistemas':'systems','nodo':'node','nodos':'nodes',
  'servidor':'server','base':'base','datos':'data',
  'archivo':'file','archivos':'files','configuración':'configuration',
  'opciones':'options','preferencias':'preferences','ajustes':'settings',
  'perfil':'profile','perfiles':'profiles','nombre':'name',
  'descripción':'description','estado':'state','estados':'states',
  'categoría':'category','categorías':'categories',
  'etiqueta':'tag','etiquetas':'tags','versión':'version',
  'historial':'history','registro':'record','registros':'records',
  'informe':'report','informes':'reports','estadísticas':'statistics',
  'gráfico':'chart','gráficos':'charts','tabla':'table','tablas':'tables',
  'lista':'list','listas':'lists','menú':'menu',
  'botón':'button','botones':'buttons','campo':'field','campos':'fields',
  'formulario':'form','formularios':'forms','página':'page','páginas':'pages',
  'sección':'section','secciones':'sections','enlace':'link','enlaces':'links',
  'imagen':'image','imágenes':'images','video':'video','audio':'audio',
  'texto':'text','título':'title','subtítulo':'subtitle',
  'contenido':'content','mensaje':'message','mensajes':'messages',
  'notificación':'notification','notificaciones':'notifications',
  'alerta':'alert','alertas':'alerts','error':'error','errores':'errors',
  'advertencia':'warning','advertencias':'warnings',
  'información':'information','ayuda':'help',
  'pregunta':'question','preguntas':'questions',
  'respuesta':'answer','respuestas':'answers',
  'comentario':'comment','comentarios':'comments',
  'actualización':'update','actualizaciones':'updates',
  'cambio':'change','cambios':'changes','modificación':'modification',
  'creación':'creation','eliminación':'deletion','borrado':'deletion',
  'restablecimiento':'reset','restauración':'restoration',
  'copia':'copy','respaldo':'backup','respaldos':'backups',
  'descarga':'download','descargas':'downloads','subida':'upload',
  'instalación':'installation','desinstalación':'uninstallation',
  'activación':'activation','desactivación':'deactivation',
  'conexión':'connection','desconexión':'disconnection',
  'inicio':'start','cierre':'close','acceso':'access',
  'salida':'exit','entrada':'entry',
  'autorización':'authorization','autenticación':'authentication',
  'verificación':'verification','confirmación':'confirmation',
  'aprobación':'approval','rechazo':'rejection',
  'aceptación':'acceptance','cancelación':'cancellation',
  'suspensión':'suspension','reactivación':'reactivation',
  'renovación':'renewal','expiración':'expiration','vencimiento':'expiration',
  'publicación':'publication','edición':'edition','revisión':'review',
  'traducción':'translation','idioma':'language','idiomas':'languages',
  'palabra':'word','palabras':'words','frase':'phrase','frases':'phrases',
  'documento':'document','documentos':'documents',
  'carpeta':'folder','carpetas':'folders','directorio':'directory',
  'ruta':'path','rutas':'paths','dominio':'domain','subdominio':'subdomain',
  'host':'host','puerto':'port','protocolo':'protocol',
  'certificado':'certificate','certificados':'certificates',
  'clave':'key','claves':'keys','contraseña':'password',
  'administrador':'administrator','administradores':'administrators',
  'superusuario':'superuser','invitado':'guest','visitante':'visitor',
  'colaborador':'collaborator','colaboradores':'collaborators',
  'editor':'editor','editores':'editors','autor':'author','autores':'authors',
  'lector':'reader','lectores':'readers','moderador':'moderator',
  'supervisor':'supervisor','auditor':'auditor','tesorero':'treasurer',
  'secretario':'secretary','coordinador':'coordinator',
  'representante':'representative','delegado':'delegate','vocero':'spokesperson',
  'líder':'leader','líderes':'leaders','jefe':'boss','director':'director',
  'gerente':'manager','encargado':'manager','responsable':'responsible',
  // Domain terms
  'trueque':'barter','trueques':'barter units',
  'intercambio':'exchange','intercambios':'exchanges',
  'federada':'federated','federado':'federated','federados':'federated',
  'red':'network','redes':'networks',
  'transacción':'transaction','transacciones':'transactions',
  'operación':'operation','operaciones':'operations',
  'transferir':'transfer','transferencia':'transfer',
  'enviar':'send','envío':'send','enviado':'sent',
  'recibir':'receive','recibido':'received',
  'pago':'payment','pagos':'payments',
  'préstamo':'loan','semilla':'seed','semillas':'seeds',
  'banco':'bank','agricultor':'farmer','siembra':'sowing',
  'cosecha':'harvest','cosechar':'harvest',
  'energía':'energy','tarifa':'tariff','objetivo':'objective',
  'justo':'fair','calcular':'calculate','cálculo':'calculation',
  'total':'total','mantener':'keep','viva':'alive','canasta':'basket',
  'vital':'vital','dividir':'divide','obtener':'obtain',
  'necesario':'necessary','consumo':'consumption',
  'herramientas':'tools','eléctricas':'electric',
  'agrícola':'agricultural','agroecológica':'agroecological',
  'técnico':'technical','administrativo':'administrative',
  // Adjectives
  'disponible':'available','disponibles':'available',
  'accesible':'accessible','inaccesible':'inaccessible',
  'visible':'visible','habilitada':'enabled','deshabilitada':'disabled',
  'vacía':'empty','vacío':'empty','vieja':'old','actual':'current',
  'previa':'previous','siguiente':'next','primera':'first','última':'last',
  'fácil':'easy','difícil':'hard','única':'unique','individual':'individual',
  'colectiva':'collective','comunitaria':'community',
  'social':'social','económica':'economic','política':'political',
  'cultural':'cultural','educativa':'educational','productiva':'productive',
  'saludable':'healthy','limpia':'clean','verde':'green',
  'local':'local','regional':'regional','nacional':'national','internacional':'international',
  'global':'global','mundial':'worldwide','abierta':'open','cerrada':'closed',
  'completa':'complete','parcial':'partial','máxima':'maximum','máximo':'maximum',
  'básica':'basic','avanzada':'advanced','intermedia':'intermediate',
  'superior':'superior','inferior':'inferior','mayor':'greater','menor':'lesser',
  'grande':'big','pequeña':'small','pequeño':'small','mediana':'medium',
  'baja':'low','bajo':'low','alto':'high','rápida':'fast','rápido':'fast',
  'lenta':'slow','lento':'slow','activa':'active','inactiva':'inactive',
  'pendiente':'pending','vencida':'expired','expirada':'expired',
  'obligatoria':'mandatory','requerida':'required',
  // Adverbs
  'automáticamente':'automatically','directamente':'directly',
  'manualmente':'manually','desde':'from','hasta':'until',
  'ya':'already','aún':'still','todavía':'still','así':'thus',
  'allí':'there','allá':'there','aquí':'here','entonces':'then',
  'luego':'then','mientras':'while','durante':'during',
  // More common words
  'cada':'each','todo':'all','todos':'all','toda':'all','todas':'all',
  'esto':'this','eso':'that','nada':'nothing','algo':'something',
  'alguien':'someone','nadie':'nobody','también':'also','tampoco':'neither',
  'solo':'only','solamente':'only','además':'besides','incluso':'even',
  'excepto':'except','salvo':'except','incluso':'even',
  'más':'more','menos':'less','muy':'very','bastante':'quite',
  'demasiado':'too','suficiente':'enough','tanto':'so much','tanta':'so much',
  'otro':'other','otra':'other','otros':'other','otras':'other',
  'mismo':'same','misma':'same','mismos':'same','mismas':'same',
  'cierto':'certain','cierta':'certain','verdadero':'true','falso':'false',
  'importante':'important','necesario':'necessary','útil':'useful',
  'posible':'possible','imposible':'impossible','seguro':'safe',
  'público':'public','pública':'public','privado':'private','privada':'private',
  'nuevo':'new','nueva':'new','nuevos':'new','nuevas':'new',
  'viejo':'old','vieja':'old','antiguo':'old','antigua':'old',
  'primer':'first','primera':'first','último':'last','última':'last',
  'principal':'main','principal':'main','secundario':'secondary',
  'completo':'complete','completa':'complete','incompleto':'incomplete',
  'correcto':'correct','correcta':'correct','incorrecto':'incorrect',
  'válido':'valid','inválido':'invalid','legal':'legal','ilegal':'illegal',
  'normal':'normal','anormal':'abnormal','común':'common','común':'common',
  'raro':'rare','frecuente':'frequent','habitual':'usual','usual':'usual',
  'actual':'current','actualmente':'currently','ahora':'now','hoy':'today',
  'siempre':'always','nunca':'never','jamás':'never',
  'pronto':'soon','tarde':'late','temprano':'early',
  // Numbers and quantities
  'cero':'zero','uno':'one','dos':'two','tres':'three','cuatro':'four',
  'cinco':'five','seis':'six','siete':'seven','ocho':'eight','nueve':'nine',
  'diez':'ten','primero':'first','segundo':'second','tercero':'third',
  'cantidad':'quantity','número':'number','números':'numbers',
  'porcentaje':'percentage','total':'total','suma':'sum',
  'mínimo':'minimum','máximo':'maximum','promedio':'average',
  // More domain terms
  'asamblea':'assembly','votar':'vote','aprobar':'approve','rechazar':'reject',
  'proponer':'propose','propuesta':'proposal','consenso':'consensus',
  'quórum':'quorum','debate':'debate','discusión':'discussion',
  'federación':'federation','federar':'federate','federados':'federated',
  'intercambio':'exchange','trueque':'barter','moneda':'currency',
  'saldo':'balance','transferir':'transfer','transferencia':'transfer',
  'transacción':'transaction','operación':'operation',
  'crédito':'credit','débito':'debit','límite':'limit','límites':'limits',
  'tope':'cap','techo':'ceiling','piso':'floor',
  'comisión':'commission','impuesto':'tax','tasa':'rate',
  'tarifa':'tariff','tarifas':'tariffs',
  'precio':'price','precios':'prices','valor':'value','valores':'values',
  'costo':'cost','costos':'costs','gasto':'expense','gastos':'expenses',
  'presupuesto':'budget','fondo':'fund','fondos':'funds',
  'ahorro':'savings','inversión':'investment','deuda':'debt',
  'préstamo':'loan','interés':'interest',
  'producto':'product','productos':'products','catálogo':'catalog',
  'servicio':'service','servicios':'services',
  'organización':'organization','organizaciones':'organizations',
  'departamento':'department','departamentos':'departments',
  'comunidad':'community','comunidades':'communities',
  'miembro':'member','miembros':'members','socio':'member','socios':'members',
  'asamblea':'assembly','reunión':'meeting','reuniones':'meetings',
  'sesión':'session','sesiones':'sessions',
  // Technical terms
  'servidor':'server','servidores':'servers','cliente':'client','clientes':'clients',
  'nodo':'node','nodos':'nodes','cluster':'cluster','contenedor':'container',
  'contenedores':'containers','imagen':'image','imágenes':'images',
  'volumen':'volume','volúmenes':'volumes','red':'network','redes':'networks',
  'puerto':'port','puertos':'ports','hostname':'hostname','dominio':'domain',
  'subdominio':'subdomain','ruta':'path','rutas':'paths',
  'archivo':'file','archivos':'files','directorio':'directory',
  'carpeta':'folder','carpetas':'folders',
  'base de datos':'database','base':'base','datos':'data',
  'tabla':'table','tablas':'tables','registro':'record','registros':'records',
  'clave':'key','claves':'keys','valor':'value','valores':'values',
  'consulta':'query','consultas':'queries','búsqueda':'search',
  'filtro':'filter','filtros':'filters','orden':'order',
  'configuración':'configuration','configurar':'configure',
  'opción':'option','opciones':'options','parámetro':'parameter',
  'parámetros':'parameters','ajuste':'setting','ajustes':'settings',
  'preferencia':'preference','preferencias':'preferences',
  // UI terms
  'botón':'button','botones':'buttons','campo':'field','campos':'fields',
  'formulario':'form','formularios':'forms','etiqueta':'label','etiquetas':'labels',
  'menú':'menu','submenú':'submenu','pestaña':'tab','pestañas':'tabs',
  'enlace':'link','enlaces':'links','icono':'icon','iconos':'icons',
  'ventana':'window','ventanas':'windows','modal':'modal','diálogo':'dialog',
  'notificación':'notification','notificaciones':'notifications',
  'alerta':'alert','alertas':'alerts','mensaje':'message','mensajes':'messages',
  'error':'error','errores':'errors','advertencia':'warning','advertencias':'warnings',
  'información':'information','ayuda':'help','tooltip':'tooltip',
  'placeholder':'placeholder','título':'title','subtítulo':'subtitle',
  'descripción':'description','texto':'text','contenido':'content',
  // Status
  'activo':'active','activa':'active','inactivo':'inactive','inactiva':'inactive',
  'habilitado':'enabled','habilitada':'enabled','deshabilitado':'disabled','deshabilitada':'disabled',
  'pendiente':'pending','aprobado':'approved','aprobada':'approved',
  'rechazado':'rejected','rechazada':'rejected',
  'completado':'completed','completada':'completed',
  'cancelado':'cancelled','cancelada':'cancelled',
  'exitoso':'successful','exitosa':'successful','éxito':'success',
  'fallido':'failed','fallida':'failed','fallo':'failure','error':'error',
  'correcto':'correct','correcta':'correct','incorrecto':'incorrect',
  'válido':'valid','inválido':'invalid',
  'disponible':'available','no disponible':'unavailable',
  'bloqueado':'blocked','bloqueada':'blocked','desbloqueado':'unblocked',
  // Actions
  'guardar':'save','cargar':'load','descargar':'download','subir':'upload',
  'crear':'create','editar':'edit','borrar':'delete','eliminar':'delete',
  'agregar':'add','quitar':'remove','seleccionar':'select','elegir':'choose',
  'buscar':'search','encontrar':'find','filtrar':'filter','ordenar':'sort',
  'importar':'import','exportar':'export','compartir':'share','copiar':'copy',
  'pegar':'paste','cortar':'cut','deshacer':'undo','rehacer':'redo',
  'actualizar':'update','refrescar':'refresh','recargar':'reload',
  'iniciar':'start','detener':'stop','pausar':'pause','reanudar':'resume',
  'reiniciar':'restart','restablecer':'reset','restaurar':'restore',
  'instalar':'install','desinstalar':'uninstall',
  'activar':'activate','desactivar':'deactivate',
  'conectar':'connect','desconectar':'disconnect',
  'abrir':'open','cerrar':'close','ver':'view','mostrar':'show','ocultar':'hide',
  'enviar':'send','recibir':'receive','aceptar':'accept','rechazar':'reject',
  'aprobar':'approve','denegar':'deny','permitir':'allow','prohibir':'prohibit',
  'verificar':'verify','confirmar':'confirm','validar':'validate','revisar':'review',
  // More words
  'quien':'who','cómo':'how','cuál':'which','cuáles':'which',
  'cuánto':'how much','cuánta':'how much','cuántos':'how many','cuántas':'how many',
  'por qué':'why','para qué':'what for','dónde':'where','cuándo':'when',
  'qué':'what','cuál':'which',
  'porque':'because','por eso':'therefore','por lo tanto':'therefore',
  'sin embargo':'however','no obstante':'nevertheless','a pesar de':'despite',
  'en cambio':'instead','además':'besides','también':'also',
  'por ejemplo':'for example','es decir':'that is','en otras palabras':'in other words',
  'por lo general':'generally','en general':'in general','en particular':'in particular',
  'en realidad':'actually','de hecho':'in fact','por supuesto':'of course',
  'al menos':'at least','al final':'at the end','al principio':'at the beginning',
  'a través de':'through','mediante':'through','usando':'using',
  'según':'according to','de acuerdo con':'according to',
  'con respecto a':'regarding','en cuanto a':'regarding',
  'se refiere a':'refers to','depende de':'depends on',
  'consiste en':'consists of','se basa en':'is based on','se trata de':'is about',
  'no hay':'there is no','no existe':'does not exist','no tiene':'does not have',
  'se ha':'has been','se han':'have been',
  'se puede':'can be','se pueden':'can be','se debe':'must be','se deben':'must be',
  'se requiere':'is required','se necesitan':'are needed',
  'se utilizan':'are used','se usa':'is used',
  'se muestra':'is shown','se muestran':'are shown',
  'se aplica':'applies','se aplican':'apply',
  'se descuenta':'is deducted','se envía':'is sent','se recibe':'is received',
  'se crea':'is created','se eliminan':'are deleted','se guardan':'are saved',
  'se carga':'is loaded','se descarga':'is downloaded',
  'se bloquean':'are blocked','se permite':'is allowed','se prohibe':'is prohibited',
  'se configura':'is configured','se activa':'is activated','se desactiva':'is deactivated',
  'se reinicia':'restarts','se actualiza':'is updated','se restaura':'is restored',
  'se hereda':'is inherited','se une':'joins','se cae':'goes down',
  'se replican':'replicate','se identifican':'identify','se inicializa':'initializes',
  'se borran':'are deleted','se recrean':'are recreated',
  'se apruebe':'is approved','se aprueban':'are approved',
  'se rechazan':'are rejected','se reportaron':'were reported',
  'se descargará':'will be downloaded','se reconstruirá':'will be rebuilt',
  'se reiniciará':'will restart','se enviará':'will be sent',
  'se creará':'will be created','se sobreescriben':'are overwritten',
  'surtan efecto':'take effect','toma efecto':'takes effect','entra en vigor':'takes effect',
  'aún':'still','todavía':'still','así':'thus','allí':'there','allá':'there',
  'aquí':'here','entonces':'then','luego':'then',
  'por':'by','para':'for','con':'with','sin':'without','sobre':'on',
  'entre':'between','hasta':'until','desde':'from','hacia':'towards',
  'contra':'against','según':'according to','tras':'after',
  'aunque':'although','porque':'because','pues':'since','sino':'but rather',
  'tampoco':'neither','apenas':'barely',
};

function translate(text) {
  if (!text || typeof text !== 'string') return text;
  let result = text;
  // Sort keys by length (longest first) to avoid partial replacements
  const keys = Object.keys(dict).sort((a, b) => b.length - a.length);
  for (const es of keys) {
    const en = dict[es];
    // Use word boundaries, case-insensitive
    const regex = new RegExp('\\b' + es.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b', 'gi');
    result = result.replace(regex, (match) => {
      if (match === match.charAt(0).toUpperCase() + match.slice(1)) {
        return en.charAt(0).toUpperCase() + en.slice(1);
      }
      if (match === match.toUpperCase()) {
        return en.toUpperCase();
      }
      return en;
    });
  }
  return result;
}

function processObject(obj) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      result[key] = translate(value);
    } else if (typeof value === 'object' && value !== null) {
      result[key] = processObject(value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

const files = fs.readdirSync(enDir).filter(f => f.endsWith('.json'));
let totalChanged = 0;

for (const file of files) {
  const filePath = path.join(enDir, file);
  const content = fs.readFileSync(filePath, 'utf8');
  const json = JSON.parse(content);
  const translated = processObject(json);
  const newContent = JSON.stringify(translated, null, 2);
  const originalContent = JSON.stringify(json, null, 2);
  if (newContent !== originalContent) {
    fs.writeFileSync(filePath, newContent + '\n', 'utf8');
    totalChanged++;
    console.log(`Translated: ${file}`);
  }
}

console.log(`\nDone. ${totalChanged} files modified.`);
