const fs = require('fs')
const path = require('path')

const localesEn = path.join(__dirname, 'web/src/locales/en')

// Dictionary of common Spanish->English translations for this project
const dict = {
  // Articles & prepositions
  'que': 'that', 'de': 'of', 'en': 'in', 'con': 'with', 'por': 'by/for',
  'para': 'for', 'los': 'the', 'las': 'the', 'una': 'a', 'uno': 'one',
  'este': 'this', 'esta': 'this', 'como': 'how', 'cuando': 'when',
  'donde': 'where', 'sin': 'without', 'sobre': 'about', 'entre': 'between',
  'No': 'No', 'Si': 'Yes', 'del': 'of the', 'al': 'to the',
  
  // Common UI words
  'Guardar': 'Save', 'Cancelar': 'Cancel', 'Cerrar': 'Close', 'Eliminar': 'Delete',
  'Editar': 'Edit', 'Crear': 'Create', 'Agregar': 'Add', 'Buscar': 'Search',
  'Cargar': 'Load', 'Descargar': 'Download', 'Subir': 'Upload',
  'Error': 'Error', 'Exito': 'Success', 'Cargando': 'Loading', 'Guardando': 'Saving',
  'Confirmar': 'Confirm', 'Aplicar': 'Apply', 'Restablecer': 'Reset',
  'Habilitar': 'Enable', 'Deshabilitar': 'Disable', 'Activar': 'Activate',
  'Desactivar': 'Deactivate', 'Ver': 'View', 'Ocultar': 'Hide',
  'Nuevo': 'New', 'Nueva': 'New', 'Viejo': 'Old',
  'Nombre': 'Name', 'Descripcion': 'Description', 'Titulo': 'Title',
  'Fecha': 'Date', 'Hora': 'Time', 'Monto': 'Amount', 'Estado': 'Status',
  'Tipo': 'Type', 'Categoria': 'Category', 'Nivel': 'Level',
  'Usuario': 'User', 'Usuarios': 'Users', 'Miembro': 'Member', 'Miembros': 'Members',
  'Organizacion': 'Organization', 'Departamento': 'Department',
  'Propuesta': 'Proposal', 'Propuestas': 'Proposals', 'Votacion': 'Voting',
  'Asamblea': 'Assembly', 'Sesion': 'Session', 'Sesiones': 'Sessions',
  'Transferir': 'Transfer', 'Transferencia': 'Transfer', 'Billetera': 'Wallet',
  'Producto': 'Product', 'Productos': 'Products', 'Servicio': 'Service',
  'Nodo': 'Node', 'Nodos': 'Nodes', 'Red': 'Network',
  'Federacion': 'Federation', 'Federado': 'Federated',
  'Configuracion': 'Configuration', 'Configuraciones': 'Settings',
  'Notificacion': 'Notification', 'Notificaciones': 'Notifications',
  'Terminal': 'Terminal', 'Terminales': 'Terminals',
  'Cuenta': 'Account', 'Cuentas': 'Accounts', 'Saldo': 'Balance',
  'Credito': 'Credit', 'Debito': 'Debit', 'Impuesto': 'Tax', 'Impuestos': 'Taxes',
  'Fondo': 'Fund', 'Fondos': 'Funds', 'Presupuesto': 'Budget',
  'Junta': 'Board', 'Directiva': 'Directive',
  'Presidente': 'President', 'Vicepresidente': 'Vice President',
  'Secretario': 'Secretary', 'Tesorero': 'Treasurer',
  'Coordinador': 'Coordinator', 'Miembro': 'Member',
  'Ordinaria': 'Ordinary', 'Extraordinaria': 'Extraordinary', 'Urgente': 'Urgent',
  'Presencial': 'In-person', 'Remota': 'Remote',
  'Pendiente': 'Pending', 'Aprobado': 'Approved', 'Rechazado': 'Rejected',
  'Activo': 'Active', 'Inactivo': 'Inactive', 'Habilitado': 'Enabled',
  'Deshabilitado': 'Disabled', 'Vencido': 'Expired', 'Cerrado': 'Closed',
  'Abierto': 'Open', 'Completo': 'Complete', 'Incompleto': 'Incomplete',
  'Requerido': 'Required', 'Opcional': 'Optional',
  'Ayuda': 'Help', 'Informacion': 'Information', 'Info': 'Info',
  'Advertencia': 'Warning', 'Aviso': 'Notice',
  'Perfil': 'Profile', 'Datos': 'Data', 'Historial': 'History',
  'Movimiento': 'Movement', 'Movimientos': 'Movements',
  'Transaccion': 'Transaction', 'Transacciones': 'Transactions',
  'Comision': 'Commission', 'Comisiones': 'Commissions',
  'Limite': 'Limit', 'Limites': 'Limits',
  'Trueque': 'Trueque', 'Energia': 'Energy', 'Tarifa': 'Tariff', 'Rate': 'Rate',
  'Pagina': 'Page', 'Paginas': 'Pages', 'Publica': 'Public',
  'Admin': 'Admin', 'Administrador': 'Administrator',
  'Directivo': 'Director', 'Referente': 'Reference',
  'Basico': 'Basic', 'Iniciado': 'Initiate', 'Intermedio': 'Intermediate',
  'Avanzado': 'Advanced', 'Destacado': 'Outstanding',
  'Voz': 'Voice', 'Voto': 'Vote', 'Votos': 'Votes',
  'Quorum': 'Quorum', 'Consenso': 'Consensus',
  'A favor': 'In favor', 'En contra': 'Against', 'Abstencion': 'Abstention',
  'Abstener': 'Abstain', 'Ejecutar': 'Execute',
  'Convocatoria': 'Convocation', 'Convocar': 'Convene',
  'Frecuencia': 'Frequency', 'Mensual': 'Monthly', 'Trimestral': 'Quarterly',
  'Semestral': 'Semiannual', 'Anual': 'Annual',
  'Anticipacion': 'Anticipation', 'Notificar': 'Notify',
  'Asistencia': 'Attendance', 'Presente': 'Present', 'Ausente': 'Absent',
  'Minuta': 'Minutes', 'Acta': 'Record',
  'Permiso': 'Permission', 'Permisos': 'Permissions',
  'Clave': 'Key', 'Claves': 'Keys', 'Valor': 'Value', 'Valores': 'Values',
  'Idioma': 'Language', 'Idiomas': 'Languages',
  'Traduccion': 'Translation', 'Traducciones': 'Translations',
  'Default': 'Default', 'Por defecto': 'Default',
  'Ninguno': 'None', 'Todos': 'All', 'Todas': 'All',
  'Seleccionar': 'Select', 'Selecciona': 'Select',
  'Escribir': 'Write', 'Leer': 'Read',
  'Iniciar': 'Start', 'Detener': 'Stop', 'Reiniciar': 'Restart',
  'Actualizar': 'Update', 'Actualizado': 'Updated',
  'Instalar': 'Install', 'Instalado': 'Installed',
  'Generar': 'Generate', 'Generado': 'Generated',
  'Importar': 'Import', 'Exportar': 'Export',
  'Restaurar': 'Restore', 'Respaldar': 'Backup',
  'Copiar': 'Copy', 'Pegar': 'Paste', 'Cortar': 'Cut',
  'Reintentar': 'Retry', 'Continuar': 'Continue',
  'Volver': 'Return', 'Anterior': 'Previous', 'Siguiente': 'Next',
  'Primero': 'First', 'Ultimo': 'Last', 'Ultima': 'Last',
  'Arriba': 'Up', 'Abajo': 'Down', 'Izquierda': 'Left', 'Derecha': 'Right',
  'Encendido': 'On', 'Apagado': 'Off',
  'Conexion': 'Connection', 'Conectado': 'Connected', 'Desconectado': 'Disconnected',
  'Servidor': 'Server', 'Cliente': 'Client', 'Puerto': 'Port',
  'Direccion': 'Address', 'Dominio': 'Domain', 'URL': 'URL',
  'Seguridad': 'Security', 'Password': 'Password', 'Contrasena': 'Password',
  'Token': 'Token', 'Llave': 'Key', 'Firma': 'Signature',
  'Cifrado': 'Encryption', 'Encriptado': 'Encrypted',
  'Privado': 'Private', 'Publico': 'Public', 'Publica': 'Public',
  'Interno': 'Internal', 'Externo': 'External',
  'Local': 'Local', 'Remoto': 'Remote', 'Global': 'Global',
  'Sincronizar': 'Synchronize', 'Sincronizado': 'Synchronized',
  'Pendiente': 'Pending', 'Pendientes': 'Pending',
  'Revision': 'Review', 'Revisar': 'Review',
  'Aprobar': 'Approve', 'Aprobacion': 'Approval',
  'Rechazar': 'Reject', 'Rechazo': 'Rejection',
  'Expulsar': 'Expel', 'Expulsion': 'Expulsion',
  'Admitir': 'Admit', 'Admision': 'Admission',
  'Invitar': 'Invite', 'Invitacion': 'Invitation',
  'Bienvenido': 'Welcome', 'Bienvenida': 'Welcome',
  'Hola': 'Hello', 'Gracias': 'Thank you', 'Por favor': 'Please',
  'Disculpa': 'Sorry', 'Perdon': 'Sorry',
  'Hoy': 'Today', 'Ayer': 'Yesterday', 'Manana': 'Tomorrow',
  'Ahora': 'Now', 'Despues': 'Later', 'Antes': 'Before',
  'Siempre': 'Always', 'Nunca': 'Never', 'A veces': 'Sometimes',
  'Rapido': 'Fast', 'Lento': 'Slow',
  'Grande': 'Big', 'Pequeno': 'Small', 'Mediano': 'Medium',
  'Alto': 'High', 'Bajo': 'Low', 'Medio': 'Medium',
  'Maximo': 'Maximum', 'Minimo': 'Minimum',
  'Total': 'Total', 'Parcial': 'Partial',
  'Incrementar': 'Increase', 'Disminuir': 'Decrease',
  'Agregar': 'Add', 'Quitar': 'Remove', 'Remover': 'Remove',
  'Mostrar': 'Show', 'Ocultar': 'Hide',
  'Expandir': 'Expand', 'Contraer': 'Collapse',
  'Abrir': 'Open', 'Cerrar': 'Close',
  'Encender': 'Turn on', 'Apagar': 'Turn off',
  'Comenzar': 'Begin', 'Finalizar': 'End', 'Terminar': 'Finish',
  'Disponible': 'Available', 'No disponible': 'Unavailable',
  'Acceso': 'Access', 'Acceder': 'Access', 'Login': 'Login',
  'Cerrar sesion': 'Logout', 'Iniciar sesion': 'Login',
  'Registrar': 'Register', 'Registro': 'Register',
  'Solicitud': 'Request', 'Solicitudes': 'Requests',
  'Enviar': 'Send', 'Recibir': 'Receive',
  'Mensaje': 'Message', 'Mensajes': 'Messages',
  'Correo': 'Email', 'Telefono': 'Phone',
  'Ubicacion': 'Location', 'Direccion': 'Address',
  'Ciudad': 'City', 'Pais': 'Country', 'Region': 'Region',
  'Codigo': 'Code', 'Numero': 'Number',
  'Texto': 'Text', 'Numero': 'Number', 'Booleano': 'Boolean',
  'Color': 'Color', 'Tamano': 'Size', 'Estilo': 'Style',
  'Icono': 'Icon', 'Imagen': 'Image', 'Foto': 'Photo',
  'Archivo': 'File', 'Archivos': 'Files', 'Carpeta': 'Folder',
  'Enlace': 'Link', 'Boton': 'Button', 'Campo': 'Field', 'Campos': 'Fields',
  'Formulario': 'Form', 'Tabla': 'Table', 'Lista': 'List',
  'Menu': 'Menu', 'Navegacion': 'Navigation', 'Barra': 'Bar',
  'Pestana': 'Tab', 'Pestanas': 'Tabs', 'Panel': 'Panel',
  'Ventana': 'Window', 'Modal': 'Modal', 'Dialogo': 'Dialog',
  'Alerta': 'Alert', 'Notificacion': 'Notification',
  'Etiqueta': 'Label', 'Etiquetas': 'Labels',
  'Placeholder': 'Placeholder', 'Placeholder': 'Placeholder',
  'Vaciar': 'Empty', 'Vacio': 'Empty',
  'Llenar': 'Fill', 'Completo': 'Complete',
  'Filtrar': 'Filter', 'Ordenar': 'Sort',
  'Ascendente': 'Ascending', 'Descendente': 'Descending',
  'Columna': 'Column', 'Fila': 'Row',
  'Encabezado': 'Header', 'Pie': 'Footer',
  'Cuerpo': 'Body', 'Lateral': 'Sidebar',
  'Contenido': 'Content', 'Resumen': 'Summary',
  'Detalle': 'Detail', 'Detalles': 'Details',
  'Version': 'Version', 'Revision': 'Revision',
  'Cambios': 'Changes', 'Cambio': 'Change',
  'Nuevo': 'New', 'Viejo': 'Old', 'Actual': 'Current',
  'Previo': 'Previous', 'Siguiente': 'Next',
  'Destino': 'Destination', 'Origen': 'Source',
  'Remitente': 'Sender', 'Destinatario': 'Recipient',
  'Comprobante': 'Receipt', 'Recibo': 'Receipt',
  'Factura': 'Invoice', 'Pago': 'Payment', 'Pagos': 'Payments',
  'Cobrar': 'Charge', 'Cobro': 'Charge',
  'Precio': 'Price', 'Costo': 'Cost',
  'Descuento': 'Discount', 'Recargo': 'Surcharge',
  'Subtotal': 'Subtotal', 'Total': 'Total',
  'Moneda': 'Currency', 'Local': 'Local',
  'Efectivo': 'Cash', 'Digital': 'Digital',
  'Tarjeta': 'Card', 'QR': 'QR', 'NFC': 'NFC',
  'Pos': 'POS', 'Caja': 'Cash register',
  'Turno': 'Shift', 'Turnos': 'Shifts',
  'Abrir turno': 'Open shift', 'Cerrar turno': 'Close shift',
  'Huella': 'Fingerprint', 'Biometrico': 'Biometric',
  'Dispositivo': 'Device', 'Dispositivos': 'Devices',
  'Movil': 'Mobile', 'Celular': 'Cellphone',
  'Computadora': 'Computer', 'PC': 'PC',
  'Android': 'Android', 'ESP32': 'ESP32',
  'Firmware': 'Firmware', 'Hardware': 'Hardware',
  'Software': 'Software', 'Driver': 'Driver', 'Drivers': 'Drivers',
  'Sistema': 'System', 'Sistemas': 'Systems',
  'Aplicacion': 'Application', 'App': 'App',
  'Web': 'Web', 'Online': 'Online', 'Offline': 'Offline',
  'Internet': 'Internet', 'Red': 'Network',
  'WiFi': 'WiFi', 'Bluetooth': 'Bluetooth',
  'Wireless': 'Wireless', 'Cable': 'Cable',
  'Antena': 'Antenna', 'Router': 'Router',
  'IP': 'IP', 'IPv6': 'IPv6', 'MAC': 'MAC',
  'DNS': 'DNS', 'DHCP': 'DHCP',
  'Firewall': 'Firewall', 'VPN': 'VPN',
  'WireGuard': 'WireGuard', 'OpenWrt': 'OpenWrt',
  'Satellite': 'Satellite', 'Satelite': 'Satellite',
  'Antena': 'Antenna', 'Dish': 'Dish',
  'Frecuencia': 'Frequency', 'Canal': 'Channel',
  'Senal': 'Signal', 'Potencia': 'Power',
  'Banda': 'Band', 'Ancho de banda': 'Bandwidth',
  'Velocidad': 'Speed', 'Latencia': 'Latency',
  'Ping': 'Ping', 'Jitter': 'Jitter',
  'Packet': 'Packet', 'Paquete': 'Packet',
  'Perdida': 'Loss', 'Perdida de paquetes': 'Packet loss',
  'Calidad': 'Quality', 'Estabilidad': 'Stability',
  'Performance': 'Performance', 'Rendimiento': 'Performance',
  'Optimizar': 'Optimize', 'Optimizado': 'Optimized',
  'Debug': 'Debug', 'Depurar': 'Debug',
  'Log': 'Log', 'Logs': 'Logs', 'Registro': 'Log',
  'Consola': 'Console', 'Terminal': 'Terminal',
  'Comando': 'Command', 'Comandos': 'Commands',
  'Script': 'Script', 'Codigo': 'Code',
  'Programa': 'Program', 'Programar': 'Program',
  'Compilar': 'Compile', 'Build': 'Build',
  'Desplegar': 'Deploy', 'Despliegue': 'Deployment',
  'Instalacion': 'Installation', 'Instalar': 'Install',
  'Actualizar': 'Update', 'Actualizacion': 'Update',
  'Version': 'Version', 'Versiones': 'Versions',
  'Compatible': 'Compatible', 'Compatibilidad': 'Compatibility',
  'Requisito': 'Requirement', 'Requisitos': 'Requirements',
  'Dependencia': 'Dependency', 'Dependencias': 'Dependencies',
  'Modulo': 'Module', 'Modulos': 'Modules',
  'Plugin': 'Plugin', 'Extension': 'Extension',
  'Tema': 'Theme', 'Temas': 'Themes',
  'Idioma': 'Language', 'Idiomas': 'Languages',
  'Locale': 'Locale', 'Locales': 'Locales',
  'Traducir': 'Translate', 'Traducido': 'Translated',
  'Sin traducir': 'Untranslated', 'Faltante': 'Missing',
  'Origen': 'Source', 'Destino': 'Target',
  'Base de datos': 'Database', 'BD': 'DB',
  'Tabla': 'Table', 'Tablas': 'Tables',
  'Registro': 'Record', 'Registros': 'Records',
  'Consulta': 'Query', 'Consultar': 'Query',
  'Insertar': 'Insert', 'Actualizar': 'Update',
  'Eliminar': 'Delete', 'Borrar': 'Delete',
  'Seleccionar': 'Select', 'Filtrar': 'Filter',
  'Ordenar': 'Sort', 'Agrupar': 'Group',
  'Contar': 'Count', 'Sumar': 'Sum',
  'Promedio': 'Average', 'Maximo': 'Max', 'Minimo': 'Min',
  'Estadisticas': 'Statistics', 'Stats': 'Stats',
  'Grafico': 'Chart', 'Grafica': 'Chart',
  'Reporte': 'Report', 'Informe': 'Report',
  'Auditoria': 'Audit', 'Auditar': 'Audit',
  'Seguimiento': 'Tracking', 'Monitor': 'Monitor',
  'Alerta': 'Alert', 'Alertas': 'Alerts',
  'Umbral': 'Threshold', 'Limite': 'Limit',
  'Notificar': 'Notify', 'Notificacion': 'Notification',
  'Email': 'Email', 'SMS': 'SMS', 'Push': 'Push',
  'Canal': 'Channel', 'Canales': 'Channels',
  'Preferencia': 'Preference', 'Preferencias': 'Preferences',
  'Ajuste': 'Setting', 'Ajustes': 'Settings',
  'Opcion': 'Option', 'Opciones': 'Options',
  'Configurar': 'Configure', 'Configuracion': 'Configuration',
  'Personalizar': 'Customize', 'Personalizado': 'Custom',
  'Avanzado': 'Advanced', 'Basico': 'Basic',
  'Simple': 'Simple', 'Complejo': 'Complex',
  'Facil': 'Easy', 'Dificil': 'Hard',
  'Automatico': 'Automatic', 'Manual': 'Manual',
  'Auto': 'Auto', 'Semi': 'Semi',
  'Hibrido': 'Hybrid', 'Mixto': 'Mixed',
  'Unico': 'Unique', 'Multiple': 'Multiple',
  'Individual': 'Individual', 'Grupal': 'Group',
  'Colectivo': 'Collective', 'Comunitario': 'Community',
  'Social': 'Social', 'Economico': 'Economic',
  'Politico': 'Political', 'Cultural': 'Cultural',
  'Educativo': 'Educational', 'Formativo': 'Formative',
  'Productivo': 'Productive', 'Reproductivo': 'Reproductive',
  'Sostenible': 'Sustainable', 'Soberano': 'Sovereign',
  'Autonomo': 'Autonomous', 'Independiente': 'Independent',
  'Federado': 'Federated', 'Confederado': 'Confederate',
  'Local': 'Local', 'Regional': 'Regional',
  'Nacional': 'National', 'Internacional': 'International',
  'Global': 'Global', 'Mundial': 'Worldwide',
  'Comunidad': 'Community', 'Comunidades': 'Communities',
  'Aldea': 'Village', 'Aldeas': 'Villages',
  'Conuco': 'Conuco (small farm)',
  'Finca': 'Farm', 'Parcela': 'Plot',
  'Tierra': 'Land', 'Territorio': 'Territory',
  'Semilla': 'Seed', 'Semillas': 'Seeds',
  'Cosecha': 'Harvest', 'Cultivo': 'Crop',
  'Agricultura': 'Agriculture', 'Agricola': 'Agricultural',
  'Agroecologia': 'Agroecology', 'Agroecologico': 'Agroecological',
  'Organico': 'Organic', 'Natural': 'Natural',
  'Biologico': 'Biological', 'Biodinamico': 'Biodynamic',
  'Ecologico': 'Ecological', 'Eco': 'Eco',
  'Verde': 'Green', 'Limpio': 'Clean',
  'Sano': 'Healthy', 'Saludable': 'Healthy',
  'Comida': 'Food', 'Alimento': 'Food',
  'Alimentacion': 'Nutrition', 'Alimentaria': 'Food-related',
  'Soberania alimentaria': 'Food sovereignty',
  'Intercambio': 'Exchange', 'Trueque': 'Barter/Trueque',
  'Comercio': 'Trade', 'Mercado': 'Market',
  'Feria': 'Fair/Market', 'Ventas': 'Sales',
  'Vender': 'Sell', 'Comprar': 'Buy',
  'Oferta': 'Offer', 'Demanda': 'Demand',
  'Productor': 'Producer', 'Consumidor': 'Consumer',
  'Artesano': 'Artisan', 'Taller': 'Workshop',
  'Cultura': 'Culture', 'Musica': 'Music',
  'Arte': 'Art', 'Poesia': 'Poetry',
  'Taller': 'Workshop', 'Curso': 'Course',
  'Capacitacion': 'Training', 'Formacion': 'Formation',
  'Educacion': 'Education', 'Ensenanza': 'Teaching',
  'Aprendizaje': 'Learning', 'Conocimiento': 'Knowledge',
  'Saberes': 'Knowledge', 'Sabiduria': 'Wisdom',
  'Experiencia': 'Experience', 'Practica': 'Practice',
  'Teoria': 'Theory', 'Metodo': 'Method',
  'Tecnica': 'Technique', 'Tecnologia': 'Technology',
  'Tecnologico': 'Technological', 'Digital': 'Digital',
  'Innovacion': 'Innovation', 'Investigacion': 'Research',
  'Desarrollo': 'Development', 'Progreso': 'Progress',
  'Evolucion': 'Evolution', 'Transformacion': 'Transformation',
  'Cambio': 'Change', 'Transicion': 'Transition',
  'Adaptacion': 'Adaptation', 'Resiliencia': 'Resilience',
  'Resistencia': 'Resistance', 'Lucha': 'Struggle',
  'Movimiento': 'Movement', 'Organizacion': 'Organization',
  'Estructura': 'Structure', 'Sistema': 'System',
  'Modelo': 'Model', 'Paradigma': 'Paradigm',
  'Enfoque': 'Approach', 'Perspectiva': 'Perspective',
  'Vision': 'Vision', 'Mision': 'Mission',
  'Objetivo': 'Objective', 'Meta': 'Goal',
  'Proposito': 'Purpose', 'Razon': 'Reason',
  'Principio': 'Principle', 'Valor': 'Value',
  'Etica': 'Ethics', 'Moral': 'Moral',
  'Derecho': 'Right', 'Deber': 'Duty',
  'Obligacion': 'Obligation', 'Responsabilidad': 'Responsibility',
  'Compromiso': 'Commitment', 'Participacion': 'Participation',
  'Colaboracion': 'Collaboration', 'Cooperacion': 'Cooperation',
  'Solidaridad': 'Solidarity', 'Reciprocidad': 'Reciprocity',
  'Mutualidad': 'Mutuality', 'Ayuda mutua': 'Mutual aid',
  'Cayapa': 'Cayapa (collective work)',
  'Trabajo': 'Work', 'Trabajo comunitario': 'Community work',
  'Voluntario': 'Volunteer', 'Voluntariado': 'Volunteering',
  'Aporte': 'Contribution', 'Aportar': 'Contribute',
  'Donar': 'Donate', 'Donacion': 'Donation',
  'Regalar': 'Gift', 'Regalo': 'Gift',
  'Compartir': 'Share', 'Compartido': 'Shared',
  'Intercambiar': 'Exchange', 'Intercambio': 'Exchange',
  'Reciproco': 'Reciprocal', 'Mutuo': 'Mutual',
  'Fondo': 'Fund', 'Fondo comunitario': 'Community fund',
  'Caja': 'Box/Cash', 'Caja chica': 'Petty cash',
  'Tesoro': 'Treasury', 'Tesorero': 'Treasurer',
  'Presupuesto': 'Budget', 'Gasto': 'Expense',
  'Ingreso': 'Income', 'Egreso': 'Expense',
  'Costo': 'Cost', 'Beneficio': 'Benefit',
  'Ganancia': 'Profit', 'Perdida': 'Loss',
  'Excedente': 'Surplus', 'Reserva': 'Reserve',
  'Ahorro': 'Savings', 'Inversion': 'Investment',
  'Capital': 'Capital', 'Patrimonio': 'Equity',
  'Activo': 'Asset', 'Pasivo': 'Liability',
  'Balance': 'Balance', 'Balanza': 'Balance',
  'Contabilidad': 'Accounting', 'Contable': 'Accountable',
  'Cuenta contable': 'Accounting account',
  'Partida doble': 'Double entry',
  'Suma cero': 'Zero sum',
  'Credito': 'Credit', 'Debito': 'Debit',
  'Saldo': 'Balance', 'Saldo negativo': 'Negative balance',
  'Saldo positivo': 'Positive balance',
  'Deuda': 'Debt', 'Pagar': 'Pay',
  'Saldar': 'Settle', 'Saldar deuda': 'Settle debt',
  'Transferencia': 'Transfer', 'Transferir': 'Transfer',
  'Remesa': 'Remittance', 'Envio': 'Send',
  'Recibir': 'Receive', 'Receptor': 'Receiver',
  'Emisor': 'Sender', 'Destinatario': 'Recipient',
  'Referencia': 'Reference', 'Concepto': 'Concept',
  'Nota': 'Note', 'Mensaje': 'Message',
  'Comentario': 'Comment', 'Observacion': 'Observation',
  'Descripcion': 'Description', 'Detalle': 'Detail',
  'Resumen': 'Summary', 'Sintesis': 'Synthesis',
  'Titulo': 'Title', 'Subtitulo': 'Subtitle',
  'Etiqueta': 'Label', 'Tag': 'Tag',
  'Categoria': 'Category', 'Subcategoria': 'Subcategory',
  'Grupo': 'Group', 'Subgrupo': 'Subgroup',
  'Tipo': 'Type', 'Subtipo': 'Subtype',
  'Clase': 'Class', 'Clasificacion': 'Classification',
  'Orden': 'Order', 'Ordenar': 'Sort',
  'Secuencia': 'Sequence', 'Serie': 'Series',
  'Numero': 'Number', 'Cantidad': 'Quantity',
  'Monto': 'Amount', 'Valor': 'Value',
  'Porcentaje': 'Percentage', 'Tasa': 'Rate',
  'Ratio': 'Ratio', 'Proporcion': 'Proportion',
  'Fraccion': 'Fraction', 'Decimal': 'Decimal',
  'Entero': 'Integer', 'Positivo': 'Positive',
  'Negativo': 'Negative', 'Cero': 'Zero',
  'Minimo': 'Minimum', 'Maximo': 'Maximum',
  'Promedio': 'Average', 'Mediana': 'Median',
  'Moda': 'Mode', 'Rango': 'Range',
  'Intervalo': 'Interval', 'Periodo': 'Period',
  'Ciclo': 'Cycle', 'Fase': 'Phase',
  'Etapa': 'Stage', 'Paso': 'Step',
  'Proceso': 'Process', 'Procedimiento': 'Procedure',
  'Flujo': 'Flow', 'Flujo de trabajo': 'Workflow',
  'Operacion': 'Operation', 'Accion': 'Action',
  'Funcion': 'Function', 'Funcionalidad': 'Feature',
  'Caracteristica': 'Feature', 'Propiedad': 'Property',
  'Atributo': 'Attribute', 'Parametro': 'Parameter',
  'Variable': 'Variable', 'Constante': 'Constant',
  'Estado': 'State/Status', 'Condicion': 'Condition',
  'Regla': 'Rule', 'Reglas': 'Rules',
  'Norma': 'Norm', 'Estandar': 'Standard',
  'Politica': 'Policy', 'Protocolo': 'Protocol',
  'Acuerdo': 'Agreement', 'Tratado': 'Treaty',
  'Convenio': 'Agreement', 'Pacto': 'Pact',
  'Contrato': 'Contract', 'Compromiso': 'Commitment',
  'Promesa': 'Promise', 'Juramento': 'Oath',
  'Declaracion': 'Declaration', 'Manifiesto': 'Manifesto',
  'Proclama': 'Proclamation', 'Edicto': 'Edict',
  'Decreto': 'Decree', 'Ley': 'Law',
  'Reglamento': 'Regulation', 'Estatuto': 'Statute',
  'Constitucion': 'Constitution', 'Carta': 'Charter',
  'Acta': 'Record/Minutes', 'Memoria': 'Memoir',
  'Resolucion': 'Resolution', 'Decision': 'Decision',
  'Deliberacion': 'Deliberation', 'Discusion': 'Discussion',
  'Debate': 'Debate', 'Argumento': 'Argument',
  'Opinion': 'Opinion', 'Postura': 'Position',
  'Posicion': 'Position', 'Voto': 'Vote',
  'Sufragio': 'Suffrage', 'Elecciones': 'Elections',
  'Eleccion': 'Election', 'Candidato': 'Candidate',
  'Candidata': 'Candidate', 'Postular': 'Run for',
  'Postulacion': 'Candidacy', 'Nominar': 'Nominate',
  'Nominacion': 'Nomination', 'Designar': 'Designate',
  'Asignar': 'Assign', 'Designacion': 'Designation',
  'Asignacion': 'Assignment', 'Nombramiento': 'Appointment',
  'Elevar': 'Elevate', 'Ascender': 'Promote',
  'Degradar': 'Demote', 'Destituir': 'Dismiss',
  'Revocar': 'Revoke', 'Anular': 'Annul',
  'Invalidar': 'Invalidate', 'Anular': 'Cancel',
  'Suspender': 'Suspend', 'Prohibir': 'Prohibit',
  'Permitir': 'Permit', 'Autorizar': 'Authorize',
  'Autorizacion': 'Authorization', 'Permiso': 'Permission',
  'Licencia': 'License', 'Concesion': 'Concession',
  'Privilegio': 'Privilege', 'Derecho': 'Right',
  'Prohibicion': 'Prohibition', 'Restriccion': 'Restriction',
  'Limitacion': 'Limitation', 'Condicion': 'Condition',
  'Requisito': 'Requirement', 'Criterio': 'Criterion',
  'Estandar': 'Standard', 'Meta': 'Goal',
  'Objetivo': 'Objective', 'Finalidad': 'Purpose',
  'Proposito': 'Purpose', 'Mision': 'Mission',
  'Vision': 'Vision', 'Valor': 'Value',
}

// Words that are false friends or shouldn't be translated
const keepAsIs = new Set([
  'Trueque', 'Trueques', 'TQ', 'kWh', 'Cayapa', 'Cayapas',
  'Conuco', 'Conucos', 'POS', 'NFC', 'QR', 'WiFi', 'IP', 'IPv6',
  'DNS', 'DHCP', 'VPN', 'WireGuard', 'OpenWrt', 'ESP32', 'Android',
  'JWT', 'API', 'URL', 'URI', 'JSON', 'XML', 'HTML', 'CSS',
  'Token', 'token', 'Backup', 'backup', 'Seed', 'seed',
  'Demo', 'demo', 'Node', 'node', 'Master', 'master',
  'Server', 'server', 'Client', 'client',
  'Admin', 'admin', 'Debug', 'debug', 'Log', 'log',
  'Build', 'build', 'Deploy', 'deploy',
  'Tag', 'tag', 'Placeholder', 'placeholder',
  'Default', 'default', 'Status', 'status',
  'Dashboard', 'dashboard', 'Profile', 'profile',
  'Wallet', 'wallet', 'Terminal', 'terminal',
  'Driver', 'driver', 'Firmware', 'firmware',
  'Hardware', 'hardware', 'Software', 'software',
  'Satellite', 'satellite', 'Firewall', 'firewall',
  'Router', 'router', 'Modem', 'modem',
  'VoIP', 'voip', 'SIP', 'sip', 'PSTN', 'pstn',
  'WebRTC', 'webrtc', 'TURN', 'turn', 'STUN', 'stun',
  'YugabyteDB', 'yugabytedb', 'PostgreSQL', 'postgresql',
  'Docker', 'docker', 'Git', 'git', 'GitHub', 'github',
])

function translateValue(val) {
  if (typeof val !== 'string') return val
  // Skip if no Spanish characters and no common Spanish words
  const hasSpanish = /[áéíóúñ¿¡]/.test(val)
  const hasSpanishWords = /\b(que|de|en|con|por|para|los|las|una|uno|este|esta|como|cuando|donde|sin|sobre|entre|del|al|sus|por|fue|son|sea|ser|tiene|tiene|puede|pueden|debe|deben|cada|todo|toda|todos|todas|otro|otra|otros|otras|mismo|misma|este|esta|estos|estas|aquel|aquella|esos|esas|nuestro|nuestra|vuestro|vuestra|su|sus|mi|mis|tu|tus|se|le|les|te|me|nos|os|se|yo|tu|el|ella|usted|nosotros|vosotros|ellos|ellas|ustedes)\b/i.test(val)
  
  if (!hasSpanish && !hasSpanishWords) return val
  
  // Don't translate if it's already in English
  if (!hasSpanish && !hasSpanishWords) return val
  
  let result = val
  
  // Replace common Spanish phrases first (longer phrases before shorter)
  const phrases = [
    ['No hay', 'No'], ['No tienes', 'You don\'t have'],
    ['Cerrar sesion', 'Logout'], ['Iniciar sesion', 'Login'],
    ['Por defecto', 'Default'], ['Por favor', 'Please'],
    ['A favor', 'In favor'], ['En contra', 'Against'],
    ['No se encontraron', 'No results found'],
    ['No se encontro', 'No result found'],
    ['es obligatorio', 'is required'], ['es obligatoria', 'is required'],
    ['son obligatorios', 'are required'], ['son obligatorias', 'are required'],
    ['debe ser positivo', 'must be positive'],
    ['debe ser un numero', 'must be a number'],
    ['Guardado correctamente', 'Saved successfully'],
    ['Eliminado correctamente', 'Deleted successfully'],
    ['Actualizado correctamente', 'Updated successfully'],
    ['Creado correctamente', 'Created successfully'],
    ['Error al guardar', 'Error saving'],
    ['Error al eliminar', 'Error deleting'],
    ['Error al actualizar', 'Error updating'],
    ['Error al crear', 'Error creating'],
    ['Error al cargar', 'Error loading'],
    ['Configuracion guardada', 'Configuration saved'],
    ['Configuracion actualizada', 'Configuration updated'],
    ['No hay propuestas', 'No proposals'],
    ['No hay sesiones', 'No sessions'],
    ['No hay miembros', 'No members'],
    ['No hay datos', 'No data'],
    ['No hay resultados', 'No results'],
    ['No hay configuracion', 'No configuration'],
    ['No hay niveles', 'No levels'],
    ['No hay organizaciones', 'No organizations'],
    ['No hay departamentos', 'No departments'],
    ['No hay productos', 'No products'],
    ['No hay transacciones', 'No transactions'],
    ['No hay movimientos', 'No movements'],
    ['No hay notificaciones', 'No notifications'],
    ['No hay terminales', 'No terminals'],
    ['No hay drivers', 'No drivers'],
    ['No hay nodos', 'No nodes'],
    ['No hay federados', 'No federated nodes'],
    ['No hay backups', 'No backups'],
    ['No hay claves', 'No keys'],
    ['No hay idiomas', 'No languages'],
    ['No hay traducciones', 'No translations'],
    ['No hay usuarios', 'No users'],
    ['No hay cuentas', 'No accounts'],
    ['No hay permisos', 'No permissions'],
    ['No hay reglas', 'No rules'],
    ['No hay solicitudes', 'No requests'],
    ['No hay pagos', 'No payments'],
    ['No hay ventas', 'No sales'],
    ['No hay compras', 'No purchases'],
    ['No hay saldo', 'No balance'],
    ['No hay historial', 'No history'],
    ['No hay actividad', 'No activity'],
    ['No hay conexion', 'No connection'],
    ['No hay acceso', 'No access'],
    ['No hay permiso', 'No permission'],
    ['No hay autorizacion', 'No authorization'],
    ['No hay fondos', 'No funds'],
    ['No hay presupuesto', 'No budget'],
    ['No hay informacion', 'No information'],
    ['No hay descripcion', 'No description'],
    ['No hay titulo', 'No title'],
    ['No hay nombre', 'No name'],
    ['No hay email', 'No email'],
    ['No hay telefono', 'No phone'],
    ['No hay ubicacion', 'No location'],
    ['No hay direccion', 'No address'],
    ['No hay fecha', 'No date'],
    ['No hay hora', 'No time'],
    ['No hay monto', 'No amount'],
    ['No hay tipo', 'No type'],
    ['No hay categoria', 'No category'],
    ['No hay nivel', 'No level'],
    ['No hay estado', 'No status'],
    ['No hay version', 'No version'],
    ['No hay cambios', 'No changes'],
    ['No hay actualizaciones', 'No updates'],
    ['No hay alertas', 'No alerts'],
    ['No hay errores', 'No errors'],
    ['No hay advertencias', 'No warnings'],
    ['No hay mensajes', 'No messages'],
    ['No hay comentarios', 'No comments'],
    ['No hay notas', 'No notes'],
    ['No hay observaciones', 'No observations'],
    ['No hay detalles', 'No details'],
    ['No hay resumen', 'No summary'],
    ['No hay estadisticas', 'No statistics'],
    ['No hay reportes', 'No reports'],
    ['No hay auditoria', 'No audit'],
    ['No hay seguimiento', 'No tracking'],
    ['No hay monitoreo', 'No monitoring'],
  ]
  
  for (const [spa, eng] of phrases) {
    result = result.split(spa).join(eng)
  }
  
  // Replace individual words using dictionary
  // Sort by length descending to replace longer words first
  const sortedDict = Object.entries(dict).sort((a, b) => b[0].length - a[0].length)
  for (const [spa, eng] of sortedDict) {
    const regex = new RegExp('\\b' + spa.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b', 'gi')
    result = result.replace(regex, eng)
  }
  
  // Fix common replacement issues
  result = result.replace(/\bthe the\b/gi, 'the')
  result = result.replace(/\bof of\b/gi, 'of')
  result = result.replace(/\bto to\b/gi, 'to')
  result = result.replace(/\bfor for\b/gi, 'for')
  result = result.replace(/\bwith with\b/gi, 'with')
  result = result.replace(/\bin in\b/gi, 'in')
  result = result.replace(/\bon on\b/gi, 'on')
  result = result.replace(/\bNo No\b/gi, 'No')
  result = result.replace(/\bNo No hay\b/gi, 'No')
  
  // Capitalize first letter
  if (result.length > 0) {
    result = result.charAt(0).toUpperCase() + result.slice(1)
  }
  
  return result
}

// Process all en/*.json files
const files = fs.readdirSync(localesEn).filter(f => f.endsWith('.json'))
let totalTranslated = 0
let totalUnchanged = 0

for (const file of files) {
  const filePath = path.join(localesEn, file)
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'))
  
  function processObj(obj) {
    let changed = 0
    for (const key of Object.keys(obj)) {
      if (typeof obj[key] === 'string') {
        const original = obj[key]
        const translated = translateValue(original)
        if (translated !== original) {
          obj[key] = translated
          changed++
        }
      } else if (typeof obj[key] === 'object' && obj[key] !== null) {
        changed += processObj(obj[key])
      }
    }
    return changed
  }
  
  const changed = processObj(data)
  if (changed > 0) {
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8')
    console.log(`${file}: ${changed} values translated`)
    totalTranslated += changed
  } else {
    totalUnchanged++
  }
}

console.log(`\nTotal: ${totalTranslated} values translated, ${totalUnchanged} files unchanged`)
