const fs = require('fs');
const path = require('path');

const enDir = path.join(__dirname, 'web', 'src', 'locales', 'en');

// Dictionary sorted by length (longest first) to avoid partial replacements
const dict = [
  // Phrases (longest first)
  ['por cada', 'for each'], ['todo el dia', 'all day'], ['todo el día', 'all day'],
  ['dejar vacío', 'leave empty'], ['dejar Empty', 'leave empty'],
  ['en segundo plano', 'in the background'],
  ['No se puede', 'Cannot'], ['no se puede', 'cannot'],
  ['No se pudo', 'Could not'], ['no se pudo', 'could not'],
  ['automáticamente', 'automatically'], ['directamente', 'directly'],
  ['manualmente', 'manually'], ['desde cero', 'from scratch'],
  ['desde Zero', 'from scratch'], ['por defecto', 'by default'],
  ['a través de', 'through'], ['mediante', 'through'],
  ['sobre todo', 'especially'], ['además de', 'besides'],
  ['después de', 'after'], ['antes de', 'before'],
  ['por supuesto', 'of course'], ['es decir', 'that is'],
  ['por ejemplo', 'for example'], ['en cambio', 'instead'],
  ['al final', 'at the end'], ['al principio', 'at the beginning'],
  ['por lo menos', 'at least'], ['por lo tanto', 'therefore'],
  ['por eso', 'therefore'], ['sin embargo', 'however'],
  ['a pesar de', 'despite'], ['en caso de', 'in case of'],
  ['en lugar de', 'instead of'], ['a causa de', 'because of'],
  ['gracias a', 'thanks to'], ['debido a', 'due to'],
  ['con el fin de', 'in order to'], ['para que', 'so that'],
  ['hasta que', 'until'], ['mientras tanto', 'meanwhile'],
  ['en general', 'in general'], ['en particular', 'in particular'],
  ['en realidad', 'actually'], ['de hecho', 'in fact'],
  ['por lo general', 'generally'], ['de acuerdo con', 'according to'],
  ['con respecto a', 'regarding'], ['en cuanto a', 'regarding'],
  ['se refiere a', 'refers to'], ['depende de', 'depends on'],
  ['consiste en', 'consists of'], ['se basa en', 'is based on'],
  ['se trata de', 'is about'], ['no hay', 'there is no'],
  ['no existe', 'does not exist'], ['no tiene', 'does not have'],
  ['no es', 'is not'], ['no son', 'are not'], ['no está', 'is not'],
  ['no están', 'are not'], ['se ha', 'has been'], ['se han', 'have been'],
  ['se puede', 'can be'], ['se pueden', 'can be'],
  ['se debe', 'must be'], ['se deben', 'must be'],
  ['se requiere', 'is required'], ['se necesitan', 'are needed'],
  ['se utilizan', 'are used'], ['se usa', 'is used'],
  ['se muestra', 'is shown'], ['se muestran', 'are shown'],
  ['se aplica', 'applies'], ['se aplican', 'apply'],
  ['se descuenta', 'is deducted'], ['se envía', 'is sent'],
  ['se recibe', 'is received'], ['se crea', 'is created'],
  ['se eliminan', 'are deleted'], ['se guardan', 'are saved'],
  ['se carga', 'is loaded'], ['se descarga', 'is downloaded'],
  ['se bloquean', 'are blocked'], ['se permite', 'is allowed'],
  ['se prohibe', 'is prohibited'], ['se configura', 'is configured'],
  ['se activa', 'is activated'], ['se desactiva', 'is deactivated'],
  ['se reinicia', 'restarts'], ['se actualiza', 'is updated'],
  ['se restaura', 'is restored'], ['se hereda', 'is inherited'],
  ['se une', 'joins'], ['se cae', 'goes down'], ['se replican', 'replicate'],
  ['se identifican', 'identify'], ['se inicializa', 'initializes'],
  ['se borran', 'are deleted'], ['se recrean', 'are recreated'],
  ['se apruebe', 'is approved'], ['se aprueban', 'are approved'],
  ['se rechazan', 'are rejected'], ['se reportaron', 'were reported'],
  ['se descargará', 'will be downloaded'], ['se reconstruirá', 'will be rebuilt'],
  ['se reiniciará', 'will restart'], ['se enviará', 'will be sent'],
  ['se creará', 'will be created'], ['se borraran', 'will be deleted'],
  ['se recrearan', 'will be recreated'], ['se agregará', 'will be added'],
  ['se sobreescriben', 'are overwritten'], ['surtan efecto', 'take effect'],
  ['toma efecto', 'takes effect'], ['entra en vigor', 'takes effect'],
  ['aún', 'still'], ['todavía', 'still'], ['ya', 'already'],
  ['así', 'thus'], ['allí', 'there'], ['allá', 'there'],
  ['aquí', 'here'], ['entonces', 'then'], ['luego', 'then'],
  ['mientras', 'while'], ['durante', 'during'], ['sin', 'without'],
  ['sobre', 'over'], ['entre', 'between'], ['hasta', 'until'],
  ['desde', 'from'], ['hacia', 'towards'], ['contra', 'against'],
  ['según', 'according to'], ['tras', 'after'], ['aunque', 'although'],
  ['porque', 'because'], ['pues', 'since'], ['sino', 'but rather'],
  ['tampoco', 'neither'], ['apenas', 'barely'],
  // Common words
  ['verdadero', 'true'], ['falso', 'false'],
  ['siempre', 'always'], ['nunca', 'never'], ['jamás', 'never'],
  ['hoy', 'today'], ['ayer', 'yesterday'], ['mañana', 'tomorrow'],
  ['tarde', 'afternoon'], ['noche', 'night'],
  ['semana', 'week'], ['mes', 'month'], ['meses', 'months'],
  ['año', 'year'], ['años', 'years'], ['día', 'day'], ['días', 'days'],
  ['hora', 'hour'], ['horas', 'hours'], ['minuto', 'minute'], ['minutos', 'minutes'],
  ['segundo', 'second'], ['segundos', 'seconds'], ['tiempo', 'time'],
  ['veces', 'times'], ['vez', 'time'], ['lugar', 'place'],
  ['forma', 'form'], ['manera', 'way'], ['parte', 'part'],
  ['mundo', 'world'], ['vida', 'life'], ['país', 'country'], ['países', 'countries'],
  ['ciudad', 'city'], ['pueblo', 'town'], ['gente', 'people'],
  ['persona', 'person'], ['personas', 'people'], ['hombre', 'man'], ['mujer', 'woman'],
  ['niño', 'child'], ['niña', 'child'], ['familia', 'family'],
  ['casa', 'house'], ['hogar', 'home'], ['trabajo', 'work'], ['dinero', 'money'],
  ['cuenta', 'account'], ['cuentas', 'accounts'], ['saldo', 'balance'],
  ['crédito', 'credit'], ['débito', 'debit'], ['deuda', 'debt'],
  ['impuesto', 'tax'], ['impuestos', 'taxes'], ['fondo', 'fund'], ['fondos', 'funds'],
  ['presupuesto', 'budget'], ['gasto', 'expense'], ['gastos', 'expenses'],
  ['ingreso', 'income'], ['ingresos', 'income'], ['costo', 'cost'],
  ['precio', 'price'], ['precios', 'prices'], ['producto', 'product'], ['productos', 'products'],
  ['servicio', 'service'], ['servicios', 'services'], ['usuario', 'user'], ['usuarios', 'users'],
  ['miembro', 'member'], ['miembros', 'members'],
  ['organización', 'organization'], ['organizaciones', 'organizations'],
  ['comunidad', 'community'], ['comunidades', 'communities'],
  ['asamblea', 'assembly'], ['sesión', 'session'], ['sesiones', 'sessions'],
  ['propuesta', 'proposal'], ['propuestas', 'proposals'],
  ['votación', 'voting'], ['voto', 'vote'], ['votos', 'votes'],
  ['decisión', 'decision'], ['decisiones', 'decisions'],
  ['regla', 'rule'], ['reglas', 'rules'], ['permiso', 'permission'], ['permisos', 'permissions'],
  ['rol', 'role'], ['roles', 'roles'], ['nivel', 'level'], ['niveles', 'levels'],
  ['sistema', 'system'], ['sistemas', 'systems'], ['nodo', 'node'], ['nodos', 'nodes'],
  ['servidor', 'server'], ['servidores', 'servers'], ['base', 'base'], ['datos', 'data'],
  ['archivo', 'file'], ['archivos', 'files'], ['configuración', 'configuration'],
  ['opciones', 'options'], ['preferencias', 'preferences'], ['ajustes', 'settings'],
  ['perfil', 'profile'], ['perfiles', 'profiles'], ['nombre', 'name'],
  ['descripción', 'description'], ['estado', 'state'], ['estados', 'states'],
  ['categoría', 'category'], ['categorías', 'categories'],
  ['etiqueta', 'tag'], ['etiquetas', 'tags'], ['versión', 'version'],
  ['historial', 'history'], ['registro', 'record'], ['registros', 'records'],
  ['informe', 'report'], ['informes', 'reports'], ['estadísticas', 'statistics'],
  ['gráfico', 'chart'], ['gráficos', 'charts'], ['tabla', 'table'], ['tablas', 'tables'],
  ['lista', 'list'], ['listas', 'lists'], ['menú', 'menu'],
  ['botón', 'button'], ['botones', 'buttons'], ['campo', 'field'], ['campos', 'fields'],
  ['formulario', 'form'], ['formularios', 'forms'], ['página', 'page'], ['páginas', 'pages'],
  ['sección', 'section'], ['secciones', 'sections'], ['enlace', 'link'], ['enlaces', 'links'],
  ['imagen', 'image'], ['imágenes', 'images'], ['video', 'video'], ['videos', 'videos'],
  ['audio', 'audio'], ['texto', 'text'], ['título', 'title'], ['subtítulo', 'subtitle'],
  ['contenido', 'content'], ['mensaje', 'message'], ['mensajes', 'messages'],
  ['notificación', 'notification'], ['notificaciones', 'notifications'],
  ['alerta', 'alert'], ['alertas', 'alerts'], ['error', 'error'], ['errores', 'errors'],
  ['advertencia', 'warning'], ['advertencias', 'warnings'],
  ['información', 'information'], ['ayuda', 'help'],
  ['pregunta', 'question'], ['preguntas', 'questions'],
  ['respuesta', 'answer'], ['respuestas', 'answers'],
  ['comentario', 'comment'], ['comentarios', 'comments'],
  ['opinión', 'opinion'], ['opiniones', 'opinions'],
  ['idea', 'idea'], ['ideas', 'ideas'], ['sugerencia', 'suggestion'], ['sugerencias', 'suggestions'],
  ['reclamación', 'claim'], ['reclamaciones', 'claims'],
  ['reporte', 'report'], ['reportes', 'reports'], ['novedad', 'news'], ['novedades', 'news'],
  ['actualización', 'update'], ['actualizaciones', 'updates'],
  ['cambio', 'change'], ['cambios', 'changes'], ['modificación', 'modification'],
  ['creación', 'creation'], ['eliminación', 'deletion'], ['borrado', 'deletion'],
  ['restablecimiento', 'reset'], ['restauración', 'restoration'],
  ['copia', 'copy'], ['respaldo', 'backup'], ['respaldos', 'backups'],
  ['descarga', 'download'], ['descargas', 'downloads'], ['subida', 'upload'],
  ['instalación', 'installation'], ['desinstalación', 'uninstallation'],
  ['activación', 'activation'], ['desactivación', 'deactivation'],
  ['conexión', 'connection'], ['desconexión', 'disconnection'],
  ['inicio', 'start'], ['cierre', 'close'], ['acceso', 'access'],
  ['salida', 'exit'], ['entrada', 'entry'],
  ['autorización', 'authorization'], ['autenticación', 'authentication'],
  ['verificación', 'verification'], ['confirmación', 'confirmation'],
  ['aprobación', 'approval'], ['rechazo', 'rejection'],
  ['aceptación', 'acceptance'], ['cancelación', 'cancellation'],
  ['suspensión', 'suspension'], ['reactivación', 'reactivation'],
  ['renovación', 'renewal'], ['expiración', 'expiration'], ['vencimiento', 'expiration'],
  ['publicación', 'publication'], ['edición', 'edition'], ['revisión', 'review'],
  ['traducción', 'translation'], ['idioma', 'language'], ['idiomas', 'languages'],
  ['palabra', 'word'], ['palabras', 'words'], ['frase', 'phrase'], ['frases', 'phrases'],
  ['documento', 'document'], ['documentos', 'documents'],
  ['carpeta', 'folder'], ['carpetas', 'folders'], ['directorio', 'directory'],
  ['ruta', 'path'], ['rutas', 'paths'], ['dominio', 'domain'], ['subdominio', 'subdomain'],
  ['host', 'host'], ['puerto', 'port'], ['protocolo', 'protocol'],
  ['certificado', 'certificate'], ['certificados', 'certificates'],
  ['clave', 'key'], ['claves', 'keys'], ['contraseña', 'password'],
  ['administrador', 'administrator'], ['administradores', 'administrators'],
  ['superusuario', 'superuser'], ['invitado', 'guest'], ['visitante', 'visitor'],
  ['colaborador', 'collaborator'], ['colaboradores', 'collaborators'],
  ['editor', 'editor'], ['editores', 'editors'], ['autor', 'author'], ['autores', 'authors'],
  ['lector', 'reader'], ['lectores', 'readers'], ['moderador', 'moderator'],
  ['supervisor', 'supervisor'], ['auditor', 'auditor'], ['tesorero', 'treasurer'],
  ['secretario', 'secretary'], ['coordinador', 'coordinator'],
  ['representante', 'representative'], ['delegado', 'delegate'], ['vocero', 'spokesperson'],
  ['líder', 'leader'], ['líderes', 'leaders'], ['jefe', 'boss'], ['director', 'director'],
  ['gerente', 'manager'], ['encargado', 'manager'], ['responsable', 'responsible'],
  // Domain terms
  ['trueque', 'barter'], ['trueques', 'barter units'],
  ['intercambio', 'exchange'], ['intercambios', 'exchanges'],
  ['federada', 'federated'], ['federado', 'federated'], ['federados', 'federated'],
  ['red', 'network'], ['redes', 'networks'],
  ['transacción', 'transaction'], ['transacciones', 'transactions'],
  ['operación', 'operation'], ['operaciones', 'operations'],
  ['transferir', 'transfer'], ['transferencia', 'transfer'],
  ['enviar', 'send'], ['envío', 'send'], ['enviado', 'sent'],
  ['recibir', 'receive'], ['recibido', 'received'],
  ['pagar', 'pay'], ['pago', 'payment'], ['pagos', 'payments'],
  ['deber', 'owe'], ['debes', 'owe'], ['prestar', 'lend'], ['préstamo', 'loan'],
  ['devolver', 'return'], ['devolución', 'return'], ['retirar', 'withdraw'],
  ['ahorrar', 'save'], ['ahorro', 'savings'], ['invertir', 'invest'],
  ['gastar', 'spend'], ['reclamar', 'claim'], ['solicitar', 'request'],
  ['solicitud', 'request'], ['solicitudes', 'requests'],
  ['crear', 'create'], ['editar', 'edit'], ['borrar', 'delete'], ['eliminar', 'delete'],
  ['guardar', 'save'], ['cargar', 'load'], ['descargar', 'download'], ['subir', 'upload'],
  ['instalar', 'install'], ['configurar', 'configure'], ['activar', 'activate'],
  ['desactivar', 'deactivate'], ['conectar', 'connect'], ['desconectar', 'disconnect'],
  ['iniciar', 'start'], ['reiniciar', 'restart'], ['detener', 'stop'],
  ['continuar', 'continue'], ['pausar', 'pause'], ['reanudar', 'resume'],
  ['comenzar', 'begin'], ['terminar', 'end'], ['finalizar', 'finish'],
  ['completar', 'complete'], ['actualizar', 'update'], ['modificar', 'modify'],
  ['cambiar', 'change'], ['mover', 'move'], ['copiar', 'copy'],
  ['abrir', 'open'], ['cerrar', 'close'], ['ver', 'view'], ['mostrar', 'show'],
  ['ocultar', 'hide'], ['buscar', 'search'], ['encontrar', 'find'],
  ['agregar', 'add'], ['quitar', 'remove'], ['seleccionar', 'select'],
  ['elegir', 'choose'], ['decidir', 'decide'], ['permitir', 'allow'],
  ['prohibir', 'prohibit'], ['requerir', 'require'], ['necesitar', 'need'],
  ['tener', 'have'], ['ser', 'be'], ['estar', 'be'], ['ir', 'go'], ['venir', 'come'],
  ['dar', 'give'], ['tomar', 'take'], ['dejar', 'leave'], ['poner', 'put'],
  ['saber', 'know'], ['pensar', 'think'], ['creer', 'believe'],
  ['hablar', 'speak'], ['decir', 'say'], ['escuchar', 'listen'], ['oír', 'hear'],
  ['leer', 'read'], ['escribir', 'write'], ['aprender', 'learn'], ['enseñar', 'teach'],
  ['comprender', 'understand'], ['entender', 'understand'],
  ['recordar', 'remember'], ['olvidar', 'forget'], ['usar', 'use'],
  ['funcionar', 'work'], ['aparecer', 'appear'], ['desaparecer', 'disappear'],
  ['existir', 'exist'], ['suceder', 'happen'], ['ocurrir', 'occur'],
  ['llegar', 'arrive'], ['salir', 'exit'], ['entrar', 'enter'],
  ['aumentar', 'increase'], ['disminuir', 'decrease'], ['crecer', 'grow'],
  ['mejorar', 'improve'], ['corregir', 'correct'], ['arreglar', 'fix'],
  ['resolver', 'resolve'], ['solucionar', 'solve'], ['aceptar', 'accept'],
  ['rechazar', 'reject'], ['cancelar', 'cancel'], ['resetear', 'reset'],
  ['verificar', 'verify'], ['revisar', 'review'], ['alertar', 'alert'],
  ['avisar', 'notify'], ['comunicar', 'communicate'], ['informar', 'inform'],
  ['reportar', 'report'], ['restaurar', 'restore'], ['exportar', 'export'],
  ['importar', 'import'], ['probar', 'test'], ['ofrecer', 'offer'],
  ['proporcionar', 'provide'], ['entregar', 'deliver'], ['comprar', 'buy'],
  ['vender', 'sell'], ['semilla', 'seed'], ['semillas', 'seeds'],
  ['banco', 'bank'], ['agricultor', 'farmer'], ['siembra', 'sowing'],
  ['cosechar', 'harvest'], ['cosecha', 'harvest'], ['energía', 'energy'],
  ['tarifa', 'tariff'], ['objetivo', 'objective'], ['justo', 'fair'],
  ['calcular', 'calculate'], ['cálculo', 'calculation'], ['total', 'total'],
  ['mantener', 'keep'], ['viva', 'alive'], ['canasta', 'basket'], ['vital', 'vital'],
  ['dividir', 'divide'], ['obtener', 'obtain'], ['necesario', 'necessary'],
  ['consumo', 'consumption'], ['metabólico', 'metabolic'], ['metabolica', 'metabolic'],
  ['herramientas', 'tools'], ['eléctricas', 'electric'],
  ['agrícola', 'agricultural'], ['agricola', 'agricultural'],
  ['agroecológica', 'agroecological'], ['técnico', 'technical'],
  ['administrativo', 'administrative'], ['afecta', 'affects'],
  ['valores', 'values'], ['configura', 'configures'], ['quien', 'who'],
  ['directo', 'direct'], ['identifica', 'identifies'], ['formato', 'format'],
  ['opcional', 'optional'], ['acompaña', 'accompanies'], ['motivo', 'motive'],
  ['aparece', 'appears'], ['comisión', 'commission'], ['descuenta', 'deducts'],
  ['recibe', 'receives'], ['envía', 'sends'], ['permite', 'allows'],
  ['negativo', 'negative'], ['positivo', 'positive'], ['significa', 'means'],
  ['crea', 'creates'], ['suma', 'sum'], ['cero', 'zero'],
  ['importante', 'important'], ['soportan', 'support'], ['pueden', 'can'],
  ['federar', 'federate'], ['reemplaza', 'replaces'], ['plataforma', 'platform'],
  ['privada', 'private'], ['controlas', 'you control'], ['tus', 'your'],
  ['instalador', 'installer'], ['requiere', 'requires'],
  ['pública', 'public'], ['decide', 'decides'], ['departamentos', 'departments'],
  ['federan', 'federate'], ['configuran', 'configure'], ['clientes', 'clients'],
  ['cliente', 'client'], ['celular', 'cellphone'], ['computadora', 'computer'],
  ['chatear', 'chat'], ['alguien', 'someone'], ['agrega', 'adds'],
  ['correo', 'email'], ['aldea', 'village'], ['software', 'software'],
  ['adapta', 'adapts'], ['filosofía', 'philosophy'],
  ['religiosa', 'religious'], ['religioso', 'religious'],
  ['determina', 'determines'], ['permiten', 'allow'], ['prohiben', 'prohibit'],
  ['recibirás', 'you will receive'], ['marque', 'marks'],
  ['prohibido', 'prohibited'], ['revisa', 'review'], ['aprueba', 'approve'],
  ['rechaza', 'reject'], ['reportadas', 'reported'], ['fueron', 'were'],
  ['estos', 'these'], ['prohibiciones', 'prohibitions'],
  ['compartida', 'shared'], ['salud', 'health'], ['cambios', 'changes'],
  ['aplicarán', 'will apply'], ['públicas', 'public'], ['desactivadas', 'deactivated'],
  ['accesibles', 'accessible'], ['aparecen', 'appear'], ['público', 'public'],
  ['quieras', 'you want'], ['borrará', 'will delete'], ['recreará', 'will recreate'],
  ['útil', 'useful'], ['hay', 'there are'], ['seguro', 'sure'],
  ['quieres', 'you want'], ['borrarán', 'will be deleted'],
  ['recrearan', 'will be recreated'], ['verifica', 'verify'],
  ['nueva', 'new'], ['repositorio', 'repository'], ['actualiza', 'update'],
  ['clic', 'click'], ['código', 'code'], ['reconstruye', 'rebuilds'],
  ['tardar', 'take'], ['varios', 'several'], ['proceso', 'process'],
  ['breve', 'brief'], ['descargará', 'will be downloaded'],
  ['reconstruirá', 'will be rebuilt'], ['vía', 'via'],
  ['trabajando', 'working'], ['plano', 'background'], ['esperando', 'waiting'],
  ['inicie', 'start'], ['rechazó', 'rejected'], ['podrá', 'could not'],
  ['reconectar', 'reconnect'], ['contenedores', 'containers'],
  ['corriendo', 'running'], ['empezar', 'start'], ['ni', 'nor'],
  ['responde', 'respond'], ['pudo', 'could'], ['reseteado', 'reset'],
  ['puedes', 'you can'], ['cancelada', 'cancelled'], ['presiona', 'press'],
  ['reintentar', 'retry'], ['script', 'script'], ['copias', 'copy'],
  ['ejecutas', 'execute'], ['une', 'joins'], ['cluster', 'cluster'],
  ['correr', 'run'], ['múltiples', 'multiple'], ['mismo', 'same'],
  ['replican', 'replicate'], ['todos', 'all'], ['otros', 'other'],
  ['siguen', 'continue'], ['funcionando', 'working'], ['seguros', 'safe'],
  ['agregas', 'add'], ['descargas', 'download'], ['nuevo', 'new'],
  ['alta', 'high'], ['disponibilidad', 'availability'],
  ['distinto', 'different'], ['distintos', 'different'], ['eficiente', 'efficient'],
  ['sube', 'raises'], ['límite', 'limit'], ['tabletas', 'tablets'],
  ['agregando', 'adding'], ['hostname', 'hostname'], ['puertos', 'ports'],
  ['diferentes', 'different'], ['instala', 'install'], ['unelo', 'join it'],
  ['resto', 'rest'], ['queda', 'remains'], ['backend', 'backend'],
  ['frontend', 'frontend'], ['operativo', 'operating'], ['efecto', 'effect'],
  ['flag', 'flag'], ['existan', 'exist'], ['sobreescriben', 'overwrite'],
  ['existentes', 'existing'], ['conflict', 'conflict'], ['nothing', 'nothing'],
  ['esto', 'this'], ['acción', 'action'], ['deshacer', 'undo'],
  ['resultado', 'result'], ['catálogo', 'catalog'], ['productoras', 'producer'],
  ['adaptaciones', 'adaptations'], ['bloqueado', 'blocked'],
  ['automáticos', 'automatic'], ['guardarlos', 'save them'],
  ['cuanto', 'how often'], ['hacerlo', 'do it'], ['rotar', 'rotate'],
  ['solo', 'only'], ['tarjeta', 'card'], ['auditoría', 'audit'],
  ['tipos', 'types'], ['acepta', 'accepts'], ['tarjetas', 'cards'],
  ['normales', 'normal'], ['fáciles', 'easier'], ['conseguir', 'get'],
  ['cuánto', 'how much'], ['acumular', 'accumulate'],
  ['hereda', 'inherits'], ['padre', 'parent'], ['cambia', 'changes'],
  ['botón', 'button'], ['entra', 'enters'], ['moneda', 'currency'],
  ['internos', 'internal'], ['elige', 'choose'],
  ['inicializará', 'will initialize'], ['carga', 'loads'],
  ['horarios', 'schedules'], ['pestaña', 'tab'], ['lectura', 'read'],
  ['modo', 'mode'], ['demostración', 'demonstration'],
  ['reiniciable', 'restartable'], ['configurable', 'configurable'],
  ['activado', 'activated'], ['bloquean', 'block'],
  ['desactivado', 'deactivated'], ['permitido', 'allowed'],
  ['funciona', 'works'], ['devuelve', 'returns'], ['cantidad', 'quantity'],
  ['mínimo', 'minimum'], ['especulativo', 'speculative'], ['paga', 'paid'],
  ['vacío', 'empty'], ['completado', 'completed'], ['registro', 'log'],
  ['arriba', 'above'], ['iniciada', 'started'], ['actualizador', 'updater'],
  ['controlador', 'controller'], ['responden', 'respond'],
  ['disponible', 'available'], ['disponibles', 'available'],
  ['accesible', 'accessible'], ['inaccesible', 'inaccessible'],
  ['visible', 'visible'], ['habilitada', 'enabled'], ['deshabilitada', 'disabled'],
  ['vacía', 'empty'], ['vieja', 'old'], ['actual', 'current'],
  ['previa', 'previous'], ['siguiente', 'next'], ['primera', 'first'],
  ['última', 'last'], ['fácil', 'easy'], ['difícil', 'hard'],
  ['única', 'unique'], ['individual', 'individual'],
  ['colectiva', 'collective'], ['comunitaria', 'community'],
  ['social', 'social'], ['económica', 'economic'], ['política', 'political'],
  ['cultural', 'cultural'], ['educativa', 'educational'],
  ['productiva', 'productive'], ['saludable', 'healthy'],
  ['limpia', 'clean'], ['verde', 'green'], ['local', 'local'],
  ['regional', 'regional'], ['nacional', 'national'], ['internacional', 'international'],
  ['global', 'global'], ['mundial', 'worldwide'], ['abierta', 'open'],
  ['cerrada', 'closed'], ['completa', 'complete'], ['parcial', 'partial'],
  ['máxima', 'maximum'], ['máximo', 'maximum'], ['básica', 'basic'],
  ['avanzada', 'advanced'], ['intermedia', 'intermediate'],
  ['superior', 'superior'], ['inferior', 'inferior'],
  ['mayor', 'greater'], ['menor', 'lesser'], ['grande', 'big'],
  ['pequeña', 'small'], ['pequeño', 'small'], ['mediana', 'medium'],
  ['baja', 'low'], ['bajo', 'low'], ['alto', 'high'],
  ['rápida', 'fast'], ['rápido', 'fast'], ['lenta', 'slow'], ['lento', 'slow'],
  ['activa', 'active'], ['inactiva', 'inactive'], ['pendiente', 'pending'],
  ['vencida', 'expired'], ['expirada', 'expired'],
  ['obligatoria', 'mandatory'], ['requerida', 'required'],
  ['demo', 'demo'], ['según', 'according to'],
];

function translate(text) {
  if (!text || typeof text !== 'string') return text;
  let result = text;
  for (const [es, en] of dict) {
    // Case-insensitive replacement, preserving case of first letter
    const regex = new RegExp(es.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    result = result.replace(regex, (match) => {
      if (match === match.charAt(0).toUpperCase() + match.slice(1)) {
        return en.charAt(0).toUpperCase() + en.slice(1);
      }
      return en;
    });
  }
  return result;
}

function processObject(obj) {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      result[key] = translate(value);
    } else if (typeof value === 'object' && value !== null) {
      result[key] = processObject(value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

const files = fs.readdirSync(enDir).filter(f => f.endsWith('.json'));
let totalChanged = 0;

for (const file of files) {
  const filePath = path.join(enDir, file);
  const content = fs.readFileSync(filePath, 'utf8');
  const json = JSON.parse(content);
  const translated = processObject(json);
  const newContent = JSON.stringify(translated, null, 2);
  const originalContent = JSON.stringify(json, null, 2);
  if (newContent !== originalContent) {
    fs.writeFileSync(filePath, newContent + '\n', 'utf8');
    totalChanged++;
    console.log(`Translated: ${file}`);
  }
}

console.log(`\nDone. ${totalChanged} files modified.`);
