-- 064_user_documents_and_countries.sql

-- Tabla de paises del mundo (ISO 3166-1)
CREATE TABLE IF NOT EXISTS countries (
    id SERIAL PRIMARY KEY,
    iso2 CHAR(2) UNIQUE NOT NULL,
    iso3 CHAR(3) UNIQUE NOT NULL,
    name TEXT UNIQUE NOT NULL,
    spanish_name TEXT UNIQUE NOT NULL,
    phone_code TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar todos los paises del mundo (~195)
INSERT INTO countries (iso2, iso3, name, spanish_name, phone_code) VALUES
('AF','AFG','Afghanistan','Afganistan','+93'),
('AL','ALB','Albania','Albania','+355'),
('DZ','DZA','Algeria','Argelia','+213'),
('AD','AND','Andorra','Andorra','+376'),
('AO','AGO','Angola','Angola','+244'),
('AG','ATG','Antigua and Barbuda','Antigua y Barbuda','+1-268'),
('AR','ARG','Argentina','Argentina','+54'),
('AM','ARM','Armenia','Armenia','+374'),
('AU','AUS','Australia','Australia','+61'),
('AT','AUT','Austria','Austria','+43'),
('AZ','AZE','Azerbaijan','Azerbaiyan','+994'),
('BS','BHS','Bahamas','Bahamas','+1-242'),
('BH','BHR','Bahrain','Bahrein','+973'),
('BD','BGD','Bangladesh','Bangladesh','+880'),
('BB','BRB','Barbados','Barbados','+1-246'),
('BY','BLR','Belarus','Bielorrusia','+375'),
('BE','BEL','Belgium','Belgica','+32'),
('BZ','BLZ','Belize','Belice','+501'),
('BJ','BEN','Benin','Benin','+229'),
('BT','BTN','Bhutan','Butan','+975'),
('BO','BOL','Bolivia','Bolivia','+591'),
('BA','BIH','Bosnia and Herzegovina','Bosnia y Herzegovina','+387'),
('BW','BWA','Botswana','Botswana','+267'),
('BR','BRA','Brazil','Brasil','+55'),
('BN','BRN','Brunei','Brunei','+673'),
('BG','BGR','Bulgaria','Bulgaria','+359'),
('BF','BFA','Burkina Faso','Burkina Faso','+226'),
('BI','BDI','Burundi','Burundi','+257'),
('CV','CPV','Cabo Verde','Cabo Verde','+238'),
('KH','KHM','Cambodia','Camboya','+855'),
('CM','CMR','Cameroon','Camerun','+237'),
('CA','CAN','Canada','Canada','+1'),
('CF','CAF','Central African Republic','Republica Centroafricana','+236'),
('TD','TCD','Chad','Chad','+235'),
('CL','CHL','Chile','Chile','+56'),
('CN','CHN','China','China','+86'),
('CO','COL','Colombia','Colombia','+57'),
('KM','COM','Comoros','Comoras','+269'),
('CG','COG','Congo','Congo','+242'),
('CD','COD','Congo (DRC)','Republica Democratica del Congo','+243'),
('CR','CRI','Costa Rica','Costa Rica','+506'),
('CI','CIV','Cote d''Ivoire','Costa de Marfil','+225'),
('HR','HRV','Croatia','Croacia','+385'),
('CU','CUB','Cuba','Cuba','+53'),
('CY','CYP','Cyprus','Chipre','+357'),
('CZ','CZE','Czechia','Republica Checa','+420'),
('DK','DNK','Denmark','Dinamarca','+45'),
('DJ','DJI','Djibouti','Yibuti','+253'),
('DM','DMA','Dominica','Dominica','+1-767'),
('DO','DOM','Dominican Republic','Republica Dominicana','+1-809'),
('EC','ECU','Ecuador','Ecuador','+593'),
('EG','EGY','Egypt','Egipto','+20'),
('SV','SLV','El Salvador','El Salvador','+503'),
('GQ','GNQ','Equatorial Guinea','Guinea Ecuatorial','+240'),
('ER','ERI','Eritrea','Eritrea','+291'),
('EE','EST','Estonia','Estonia','+372'),
('SZ','SWZ','Eswatini','Esuatini','+268'),
('ET','ETH','Ethiopia','Etiopia','+251'),
('FJ','FJI','Fiji','Fiyi','+679'),
('FI','FIN','Finland','Finlandia','+358'),
('FR','FRA','France','Francia','+33'),
('GA','GAB','Gabon','Gabon','+241'),
('GM','GMB','Gambia','Gambia','+220'),
('GE','GEO','Georgia','Georgia','+995'),
('DE','DEU','Germany','Alemania','+49'),
('GH','GHA','Ghana','Ghana','+233'),
('GR','GRC','Greece','Grecia','+30'),
('GD','GRD','Grenada','Granada','+1-473'),
('GT','GTM','Guatemala','Guatemala','+502'),
('GN','GIN','Guinea','Guinea','+224'),
('GW','GNB','Guinea-Bissau','Guinea-Bissau','+245'),
('GY','GUY','Guyana','Guyana','+592'),
('HT','HTI','Haiti','Haiti','+509'),
('HN','HND','Honduras','Honduras','+504'),
('HU','HUN','Hungary','Hungria','+36'),
('IS','ISL','Iceland','Islandia','+354'),
('IN','IND','India','India','+91'),
('ID','IDN','Indonesia','Indonesia','+62'),
('IR','IRN','Iran','Iran','+98'),
('IQ','IRQ','Iraq','Irak','+964'),
('IE','IRL','Ireland','Irlanda','+353'),
('IL','ISR','Israel','Israel','+972'),
('IT','ITA','Italy','Italia','+39'),
('JM','JAM','Jamaica','Jamaica','+1-876'),
('JP','JPN','Japan','Japon','+81'),
('JO','JOR','Jordan','Jordania','+962'),
('KZ','KAZ','Kazakhstan','Kazajistan','+7'),
('KE','KEN','Kenya','Kenia','+254'),
('KI','KIR','Kiribati','Kiribati','+686'),
('KP','PRK','Korea (North)','Corea del Norte','+850'),
('KR','KOR','Korea (South)','Corea del Sur','+82'),
('KW','KWT','Kuwait','Kuwait','+965'),
('KG','KGZ','Kyrgyzstan','Kirguistan','+996'),
('LA','LAO','Laos','Laos','+856'),
('LV','LVA','Latvia','Letonia','+371'),
('LB','LBN','Lebanon','Libano','+961'),
('LS','LSO','Lesotho','Lesoto','+266'),
('LR','LBR','Liberia','Liberia','+231'),
('LY','LBY','Libya','Libia','+218'),
('LI','LIE','Liechtenstein','Liechtenstein','+423'),
('LT','LTU','Lithuania','Lituania','+370'),
('LU','LUX','Luxembourg','Luxemburgo','+352'),
('MG','MDG','Madagascar','Madagascar','+261'),
('MW','MWI','Malawi','Malaui','+265'),
('MY','MYS','Malaysia','Malasia','+60'),
('MV','MDV','Maldives','Maldivas','+960'),
('ML','MLI','Mali','Mali','+223'),
('MT','MLT','Malta','Malta','+356'),
('MH','MHL','Marshall Islands','Islas Marshall','+692'),
('MR','MRT','Mauritania','Mauritania','+222'),
('MU','MUS','Mauritius','Mauricio','+230'),
('MX','MEX','Mexico','Mexico','+52'),
('FM','FSM','Micronesia','Micronesia','+691'),
('MD','MDA','Moldova','Moldavia','+373'),
('MC','MCO','Monaco','Monaco','+377'),
('MN','MNG','Mongolia','Mongolia','+976'),
('ME','MNE','Montenegro','Montenegro','+382'),
('MA','MAR','Morocco','Marruecos','+212'),
('MZ','MOZ','Mozambique','Mozambique','+258'),
('MM','MMR','Myanmar','Myanmar','+95'),
('NA','NAM','Namibia','Namibia','+264'),
('NR','NRU','Nauru','Nauru','+674'),
('NP','NPL','Nepal','Nepal','+977'),
('NL','NLD','Netherlands','Paises Bajos','+31'),
('NZ','NZL','New Zealand','Nueva Zelanda','+64'),
('NI','NIC','Nicaragua','Nicaragua','+505'),
('NE','NER','Niger','Niger','+227'),
('NG','NGA','Nigeria','Nigeria','+234'),
('MK','MKD','North Macedonia','Macedonia del Norte','+389'),
('NO','NOR','Norway','Noruega','+47'),
('OM','OMN','Oman','Oman','+968'),
('PK','PAK','Pakistan','Pakistan','+92'),
('PW','PLW','Palau','Palau','+680'),
('PS','PSE','Palestine','Palestina','+970'),
('PA','PAN','Panama','Panama','+507'),
('PG','PNG','Papua New Guinea','Papua Nueva Guinea','+675'),
('PY','PRY','Paraguay','Paraguay','+595'),
('PE','PER','Peru','Peru','+51'),
('PH','PHL','Philippines','Filipinas','+63'),
('PL','POL','Poland','Polonia','+48'),
('PT','PRT','Portugal','Portugal','+351'),
('QA','QAT','Qatar','Catar','+974'),
('RO','ROU','Romania','Rumania','+40'),
('RU','RUS','Russia','Rusia','+7'),
('RW','RWA','Rwanda','Ruanda','+250'),
('KN','KNA','Saint Kitts and Nevis','San Cristobal y Nevis','+1-869'),
('LC','LCA','Saint Lucia','Santa Lucia','+1-758'),
('VC','VCT','Saint Vincent and the Grenadines','San Vicente y las Granadinas','+1-784'),
('WS','WSM','Samoa','Samoa','+685'),
('SM','SMR','San Marino','San Marino','+378'),
('ST','STP','Sao Tome and Principe','Santo Tome y Principe','+239'),
('SA','SAU','Saudi Arabia','Arabia Saudita','+966'),
('SN','SEN','Senegal','Senegal','+221'),
('RS','SRB','Serbia','Serbia','+381'),
('SC','SYC','Seychelles','Seychelles','+248'),
('SL','SLE','Sierra Leone','Sierra Leona','+232'),
('SG','SGP','Singapore','Singapur','+65'),
('SK','SVK','Slovakia','Eslovaquia','+421'),
('SI','SVN','Slovenia','Eslovenia','+386'),
('SB','SLB','Solomon Islands','Islas Salomon','+677'),
('SO','SOM','Somalia','Somalia','+252'),
('ZA','ZAF','South Africa','Sudafrica','+27'),
('SS','SSD','South Sudan','Sudan del Sur','+211'),
('ES','ESP','Spain','Espana','+34'),
('LK','LKA','Sri Lanka','Sri Lanka','+94'),
('SD','SDN','Sudan','Sudan','+249'),
('SR','SUR','Suriname','Surinam','+597'),
('SE','SWE','Sweden','Suecia','+46'),
('CH','CHE','Switzerland','Suiza','+41'),
('SY','SYR','Syria','Siria','+963'),
('TW','TWN','Taiwan','Taiwan','+886'),
('TJ','TJK','Tajikistan','Tayikistan','+992'),
('TZ','TZA','Tanzania','Tanzania','+255'),
('TH','THA','Thailand','Tailandia','+66'),
('TL','TLS','Timor-Leste','Timor Oriental','+670'),
('TG','TGO','Togo','Togo','+228'),
('TO','TON','Tonga','Tonga','+676'),
('TT','TTO','Trinidad and Tobago','Trinidad y Tobago','+1-868'),
('TN','TUN','Tunisia','Tunez','+216'),
('TR','TUR','Turkey','Turquia','+90'),
('TM','TKM','Turkmenistan','Turkmenistan','+993'),
('TV','TUV','Tuvalu','Tuvalu','+688'),
('UG','UGA','Uganda','Uganda','+256'),
('UA','UKR','Ukraine','Ucrania','+380'),
('AE','ARE','United Arab Emirates','Emiratos Arabes Unidos','+971'),
('GB','GBR','United Kingdom','Reino Unido','+44'),
('US','USA','United States','Estados Unidos','+1'),
('UY','URY','Uruguay','Uruguay','+598'),
('UZ','UZB','Uzbekistan','Uzbekistan','+998'),
('VU','VUT','Vanuatu','Vanuatu','+678'),
('VA','VAT','Vatican City','Ciudad del Vaticano','+379'),
('VE','VEN','Venezuela','Venezuela','+58'),
('VN','VNM','Vietnam','Vietnam','+84'),
('YE','YEM','Yemen','Yemen','+967'),
('ZM','ZMB','Zambia','Zambia','+260'),
('ZW','ZWE','Zimbabwe','Zimbabue','+263')
ON CONFLICT (iso2) DO NOTHING;

-- Tipos de documento
CREATE TABLE IF NOT EXISTS document_types (
    id SERIAL PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    spanish_name TEXT NOT NULL,
    is_international BOOLEAN DEFAULT false,
    sort_order INT DEFAULT 0
);

INSERT INTO document_types (code, name, spanish_name, is_international, sort_order) VALUES
('cedula','National ID','Cedula de identidad', false, 1),
('dni','DNI','Documento Nacional de Identidad', false, 2),
('pasaporte','Passport','Pasaporte', true, 3),
('rut','RUT','Registro Unico Tributario', false, 4),
('curp','CURP','Clave Unica de Registro de Poblacion', false, 5),
('carnet_conducir','Drivers License','Carnet de Conducir', false, 6),
('cedula_juridica','Legal Entity ID','Cedula Juridica', false, 7),
('residencia','Residence Permit','Permiso de Residencia', false, 8),
('refugiado','Refugee Document','Documento de Refugiado', false, 9),
('otro','Other','Otro', false, 99)
ON CONFLICT (code) DO NOTHING;

-- Tabla de documentos de usuario (un usuario puede tener varios)
CREATE TABLE IF NOT EXISTS user_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_type_code TEXT NOT NULL REFERENCES document_types(code),
    document_number TEXT NOT NULL,
    country_iso2 CHAR(2) REFERENCES countries(iso2),
    country_name TEXT DEFAULT '',
    photo_url TEXT DEFAULT '',
    is_verified BOOLEAN DEFAULT false,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, document_type_code, document_number, country_iso2)
);

-- Indice para busqueda rapida por tipo + numero (deteccion de duplicados)
CREATE INDEX IF NOT EXISTS idx_user_documents_type_number ON user_documents(document_type_code, document_number);
CREATE INDEX IF NOT EXISTS idx_user_documents_user ON user_documents(user_id);

-- Tambien para admission_requests
CREATE TABLE IF NOT EXISTS admission_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admission_request_id UUID NOT NULL REFERENCES admission_requests(id) ON DELETE CASCADE,
    document_type_code TEXT NOT NULL REFERENCES document_types(code),
    document_number TEXT NOT NULL,
    country_iso2 CHAR(2) REFERENCES countries(iso2),
    country_name TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(admission_request_id, document_type_code, document_number)
);

CREATE INDEX IF NOT EXISTS idx_admission_documents_request ON admission_documents(admission_request_id);
