-- Actualizar todas las imagenes de productos en la BD existente
-- Generado desde seed.go

UPDATE products SET image_url = '/images/products/servicios/jornal-agricola.jpg' WHERE name = 'Jornal Agricola';
UPDATE products SET image_url = '/images/products/servicios/jornada-agricola.jpg' WHERE name = 'Jornada Agricola Completa';
UPDATE products SET image_url = '/images/products/servicios/jornada-trabajo-general.jpg' WHERE name = 'Jornada de Trabajo General';
UPDATE products SET image_url = '/images/products/servicios/limpieza-espacios.jpg' WHERE name = 'Limpieza de Espacios';
UPDATE products SET image_url = '/images/products/servicios/trabajo-administrativo.jpg' WHERE name = 'Trabajo Administrativo y Gestion';
UPDATE products SET image_url = '/images/products/servicios/jornada-trabajo-tecnico.jpg' WHERE name = 'Jornada de Trabajo Tecnico';
UPDATE products SET image_url = '/images/products/servicios/albanileria.jpg' WHERE name = 'Albanileria y Obra Menor';
UPDATE products SET image_url = '/images/products/servicios/carpinteria.jpg' WHERE name = 'Carpinteria y Ebanisteria';
UPDATE products SET image_url = '/images/products/servicios/mecanica-general.jpg' WHERE name = 'Mecanica General';
UPDATE products SET image_url = '/images/products/servicios/electricidad.jpg' WHERE name = 'Electricidad y Electrotecnia';
UPDATE products SET image_url = '/images/products/servicios/plomeria.jpg' WHERE name = 'Plomeria y Fontaneria';
UPDATE products SET image_url = '/images/products/tecnologia/reparacion-computadoras.jpg' WHERE name = 'Reparacion de Computadoras';
UPDATE products SET image_url = '/images/products/tecnologia/reparacion-electrodomesticos.jpg' WHERE name = 'Reparacion de Electrodomesticos';
UPDATE products SET image_url = '/images/products/tecnologia/reparacion-telefonos.jpg' WHERE name = 'Reparacion de Telefonos';
UPDATE products SET image_url = '/images/products/energia/mantenimiento-solar.jpg' WHERE name = 'Mantenimiento de Sistemas Solares';
UPDATE products SET image_url = '/images/products/transporte/mantenimiento-vehiculos.jpg' WHERE name = 'Mantenimiento de Vehiculos';
UPDATE products SET image_url = '/images/products/salud/terapias-manuales.jpg' WHERE name = 'Terapias Manuales y Alternativas';
UPDATE products SET image_url = '/images/products/salud/consulta-medica.jpg' WHERE name = 'Consulta Medica y Odontologica';
UPDATE products SET image_url = '/images/products/servicios/clases-tutorias.jpg' WHERE name = 'Clases y Tutorias';
UPDATE products SET image_url = '/images/products/cultura/clases-musica.jpg' WHERE name = 'Clases de Musica';
UPDATE products SET image_url = '/images/products/educacion/talleres-oficios.jpg' WHERE name = 'Talleres de Oficios';
UPDATE products SET image_url = '/images/products/educacion/talleres-agroecologia.jpg' WHERE name = 'Talleres de Agroecologia';
UPDATE products SET image_url = '/images/products/educacion/talleres-salud.jpg' WHERE name = 'Talleres de Salud Comunitaria';
UPDATE products SET image_url = '/images/products/educacion/alfabetizacion.jpg' WHERE name = 'Alfabetizacion y Educacion Basica';
UPDATE products SET image_url = '/images/products/cultura/animacion-cuentacuentos.jpg' WHERE name = 'Animacion y Cuentacuentos';
UPDATE products SET image_url = '/images/products/servicios/transporte-carga.jpg' WHERE name = 'Transporte de Carga';
UPDATE products SET image_url = '/images/products/servicios/pasaje-personas.jpg' WHERE name = 'Pasaje de Personas';
UPDATE products SET image_url = '/images/products/transporte/servicio-arriero.jpg' WHERE name = 'Servicio de Arriero';
UPDATE products SET image_url = '/images/products/alimentacion/hojas-verdes.jpg' WHERE name = 'Hojas Verdes y Aromaticas';
UPDATE products SET image_url = '/images/products/alimentacion/tuberculos.jpg' WHERE name = 'Tuberculos Ancestrales y Platanos';
UPDATE products SET image_url = '/images/products/alimentacion/verduras-hortalizas.jpg' WHERE name = 'Verduras y Hortalizas de Conuco';
UPDATE products SET image_url = '/images/products/alimentacion/frutas-temporada.jpg' WHERE name = 'Frutas de Temporada';
UPDATE products SET image_url = '/images/products/alimentacion/raices-bulbos.jpg' WHERE name = 'Raices y Bulbos';
UPDATE products SET image_url = '/images/products/alimentacion/frutos-secos.jpg' WHERE name = 'Frutos Secos y Mani';
UPDATE products SET image_url = '/images/products/alimentacion/granos-basicos.jpg' WHERE name = 'Granos Basicos Criollos';
UPDATE products SET image_url = '/images/products/alimentacion/arroz-legumbres.jpg' WHERE name = 'Arroz y Legumbres';
UPDATE products SET image_url = '/images/products/alimentacion/harinas-integrales.jpg' WHERE name = 'Harinas Integrales';
UPDATE products SET image_url = '/images/products/alimentacion/panaderia.jpg' WHERE name = 'Panaderia y Masas Caseras';
UPDATE products SET image_url = '/images/products/alimentacion/dulces-conservas.jpg' WHERE name = 'Dulces y Conservas Tradicionales';
UPDATE products SET image_url = '/images/products/alimentacion/lacteos-artesanales.jpg' WHERE name = 'Lacteos Artesanales';
UPDATE products SET image_url = '/images/products/alimentacion/leche-fresca.jpg' WHERE name = 'Leche Fresca';
UPDATE products SET image_url = '/images/products/alimentacion/cacao-chocolate-cafe.jpg' WHERE name = 'Cacao, Chocolate y Cafe';
UPDATE products SET image_url = '/images/products/alimentacion/encurtidos-salsas.jpg' WHERE name = 'Encurtidos y Salsas';
UPDATE products SET image_url = '/images/products/alimentacion/miel-pura.jpg' WHERE name = 'Miel Pura de Abejas';
UPDATE products SET image_url = '/images/products/alimentacion/papelon-panela.jpg' WHERE name = 'Papelon y Panela';
UPDATE products SET image_url = '/images/products/alimentacion/carnes-pollo.jpg' WHERE name = 'Carnes de Pollo y Aves';
UPDATE products SET image_url = '/images/products/alimentacion/carnes-cerdo-chivo.jpg' WHERE name = 'Carnes de Cerdo y Chivo';
UPDATE products SET image_url = '/images/products/alimentacion/carnes-vacuno.jpg' WHERE name = 'Carnes de Vacuno';
UPDATE products SET image_url = '/images/products/alimentacion/pescados-mariscos.jpg' WHERE name = 'Pescados y Mariscos';
UPDATE products SET image_url = '/images/products/alimentacion/huevos-frescos.jpg' WHERE name = 'Huevos Frescos';
UPDATE products SET image_url = '/images/products/alimentacion/bebidas-fermentadas.jpg' WHERE name = 'Bebidas Fermentadas';
UPDATE products SET image_url = '/images/products/alimentacion/infusiones-tes.jpg' WHERE name = 'Infusiones y Tes';
UPDATE products SET image_url = '/images/products/alimentacion/zumos-jugos.jpg' WHERE name = 'Zumos y Jugos Naturales';
UPDATE products SET image_url = '/images/products/alimentacion/refrescos.jpg' WHERE name = 'Refrescos Efervescentes';
UPDATE products SET image_url = '/images/products/alimentacion/licores-destilados.jpg' WHERE name = 'Licores y Destilados';
UPDATE products SET image_url = '/images/products/alimentacion/bebidas-lacteas.jpg' WHERE name = 'Bebidas Lacteas';
UPDATE products SET image_url = '/images/products/alimentacion/aguas-hidratantes.jpg' WHERE name = 'Aguas y Bebidas Hidratantes';
UPDATE products SET image_url = '/images/products/alimentacion/especias-condimentos.jpg' WHERE name = 'Especias y Condimentos';
UPDATE products SET image_url = '/images/products/alimentacion/aceites-vinagres.jpg' WHERE name = 'Aceites y Vinagres';
UPDATE products SET image_url = '/images/products/alimentacion/canasta-basica.jpg' WHERE name = 'Canasta Basica Familiar Semanal';
UPDATE products SET image_url = '/images/products/agricultura/plantulas-medicinales.jpg' WHERE name = 'Plantulas Medicinales y Aromaticas';
UPDATE products SET image_url = '/images/products/agricultura/semillas-criollas.jpg' WHERE name = 'Semillas Criollas Adaptadas';
UPDATE products SET image_url = '/images/products/agricultura/estacas-esquejes.jpg' WHERE name = 'Estacas y Esquejes';
UPDATE products SET image_url = '/images/products/agricultura/abonos-organicos.jpg' WHERE name = 'Abonos Organicos';
UPDATE products SET image_url = '/images/products/agricultura/bioinsumos.jpg' WHERE name = 'Bioinsumos y Preparados';
UPDATE products SET image_url = '/images/products/agricultura/tierra-fertil.jpg' WHERE name = 'Tierra Fertil y Sustratos';
UPDATE products SET image_url = '/images/products/agricultura/manguera-riego.jpg' WHERE name = 'Manguera de Riego PVC 1m';
UPDATE products SET image_url = '/images/products/agricultura/aspersor-riego.jpg' WHERE name = 'Aspersor de Riego';
UPDATE products SET image_url = '/images/products/agricultura/gotero-riego.jpg' WHERE name = 'Gotero de Riego';
UPDATE products SET image_url = '/images/products/agricultura/bomba-manual-agua.jpg' WHERE name = 'Bomba Manual de Agua';
UPDATE products SET image_url = '/images/products/agricultura/tanque-agua-200l.jpg' WHERE name = 'Tanque de Agua 200L';
UPDATE products SET image_url = '/images/products/agricultura/tanque-agua-1000l.jpg' WHERE name = 'Tanque de Agua 1000L';
UPDATE products SET image_url = '/images/products/salud/tinturas-madres.jpg' WHERE name = 'Tinturas Madres y Botica Conuquera';
UPDATE products SET image_url = '/images/products/salud/cosmetica-natural.jpg' WHERE name = 'Cosmetica Natural sin Quimicos';
UPDATE products SET image_url = '/images/products/salud/hierbas-medicinales-secas.jpg' WHERE name = 'Hierbas Medicinales Secas';
UPDATE products SET image_url = '/images/products/salud/jabones-higiene.jpg' WHERE name = 'Jabones y Productos de Higiene';
UPDATE products SET image_url = '/images/products/salud/detergentes-naturales.jpg' WHERE name = 'Detergentes y Suavizantes Naturales';
UPDATE products SET image_url = '/images/products/salud/vendas-gasas.jpg' WHERE name = 'Vendas y Gasas (Paquete)';
UPDATE products SET image_url = '/images/products/salud/alcohol-medicinal.jpg' WHERE name = 'Alcohol Medicinal 1L';
UPDATE products SET image_url = '/images/products/salud/yodo.jpg' WHERE name = 'Yodo (Frasco 30ml)';
UPDATE products SET image_url = '/images/products/salud/tijeras-auxilios.jpg' WHERE name = 'Tijeras de Primeros Auxilios';
UPDATE products SET image_url = '/images/products/salud/apositos-tiritas.jpg' WHERE name = 'Apositos y Tiritas (Caja)';
UPDATE products SET image_url = '/images/products/textiles/tela-algodon.jpg' WHERE name = 'Tela de Algodon Cruda (kg)';
UPDATE products SET image_url = '/images/products/textiles/lana-cruda.jpg' WHERE name = 'Lana Cruda para Tejer (kg)';
UPDATE products SET image_url = '/images/products/textiles/hilo-algodon.jpg' WHERE name = 'Hilo de Algodon (rollo 100g)';
UPDATE products SET image_url = '/images/products/textiles/camisa-algodon.jpg' WHERE name = 'Camisa de Algodon Artesanal (0.3 kg)';
UPDATE products SET image_url = '/images/products/textiles/pantalon-algodon.jpg' WHERE name = 'Pantalon de Algodon Artesanal (0.5 kg)';
UPDATE products SET image_url = '/images/products/textiles/frazada-lana.jpg' WHERE name = 'Frazada de Lana Artesanal (1.5 kg)';
UPDATE products SET image_url = '/images/products/textiles/hamoca-canamo.jpg' WHERE name = 'Hamaca de Cañamo (1.2 kg)';
UPDATE products SET image_url = '/images/products/textiles/reparacion-prendas.jpg' WHERE name = 'Reparacion y Adaptacion de Prendas';
UPDATE products SET image_url = '/images/products/textiles/trabajo-costura.jpg' WHERE name = 'Trabajo de Costura (hora)';
UPDATE products SET image_url = '/images/products/artesania/arcilla-ceramica.jpg' WHERE name = 'Arcilla para Ceramica (cruda)';
UPDATE products SET image_url = '/images/products/artesania/madera-blanda.jpg' WHERE name = 'Madera Blanda para Tallado';
UPDATE products SET image_url = '/images/products/artesania/madera-dura.jpg' WHERE name = 'Madera Dura para Muebles';
UPDATE products SET image_url = '/images/products/artesania/fibra-vegetal.jpg' WHERE name = 'Fibra Vegetal para Cesteria';
UPDATE products SET image_url = '/images/products/artesania/taza-barro.jpg' WHERE name = 'Taza de Barro (0.3 kg)';
UPDATE products SET image_url = '/images/products/artesania/plato-barro.jpg' WHERE name = 'Plato de Barro (0.5 kg)';
UPDATE products SET image_url = '/images/products/artesania/olla-barro.jpg' WHERE name = 'Olla de Barro (2 kg)';
UPDATE products SET image_url = '/images/products/artesania/cantarola-barro.jpg' WHERE name = 'Cantarola de Barro (5 kg)';
UPDATE products SET image_url = '/images/products/artesania/maceta-arcilla-pequena.jpg' WHERE name = 'Maceta de Arcilla Pequena (0.5 kg)';
UPDATE products SET image_url = '/images/products/artesania/maceta-arcilla-mediana.jpg' WHERE name = 'Maceta de Arcilla Mediana (2 kg)';
UPDATE products SET image_url = '/images/products/artesania/maceta-arcilla-grande.jpg' WHERE name = 'Maceta de Arcilla Grande (5 kg)';
UPDATE products SET image_url = '/images/products/artesania/cuchara-palo.jpg' WHERE name = 'Cuchara de Palo (0.1 kg)';
UPDATE products SET image_url = '/images/products/artesania/mortero-madera.jpg' WHERE name = 'Mortero de Madera (1 kg)';
UPDATE products SET image_url = '/images/products/artesania/silla-madera.jpg' WHERE name = 'Silla Rustica de Madera (8 kg)';
UPDATE products SET image_url = '/images/products/artesania/mesa-madera.jpg' WHERE name = 'Mesa Rustica de Madera (20 kg)';
UPDATE products SET image_url = '/images/products/artesania/banco-madera.jpg' WHERE name = 'Banco Rustico de Madera (12 kg)';
UPDATE products SET image_url = '/images/products/artesania/cama-madera.jpg' WHERE name = 'Cama Rustica de Madera (35 kg)';
UPDATE products SET image_url = '/images/products/artesania/canasto-pequeno.jpg' WHERE name = 'Canasto Pequeno (0.3 kg)';
UPDATE products SET image_url = '/images/products/artesania/cesta-mediana.jpg' WHERE name = 'Cesta Mediana (1 kg)';
UPDATE products SET image_url = '/images/products/artesania/sombrero-paja.jpg' WHERE name = 'Sombrero de Paja (0.2 kg)';
UPDATE products SET image_url = '/images/products/artesania/trabajo-alfareria.jpg' WHERE name = 'Trabajo de Alfareria (hora)';
UPDATE products SET image_url = '/images/products/artesania/trabajo-carpinteria.jpg' WHERE name = 'Trabajo de Carpinteria (hora)';
UPDATE products SET image_url = '/images/products/artesania/trabajo-cesteria.jpg' WHERE name = 'Trabajo de Cesteria (hora)';
UPDATE products SET image_url = '/images/products/artesania/coccion-ceramica.jpg' WHERE name = 'Coccion de Ceramica en Horno (carga)';
UPDATE products SET image_url = '/images/products/construccion/bloques-adobe.jpg' WHERE name = 'Bloques, Adobe y Bahareque';
UPDATE products SET image_url = '/images/products/construccion/madera-construccion.jpg' WHERE name = 'Madera de Construccion';
UPDATE products SET image_url = '/images/products/construccion/piedra-agregados.jpg' WHERE name = 'Piedra y Agregados';
UPDATE products SET image_url = '/images/products/construccion/hormigon.jpg' WHERE name = 'Hormigon Estructural';
UPDATE products SET image_url = '/images/products/construccion/ladrillo-arcilla.jpg' WHERE name = 'Ladrillo de Arcilla';
UPDATE products SET image_url = '/images/products/construccion/bloque-paja.jpg' WHERE name = 'Bloque de Paja';
UPDATE products SET image_url = '/images/products/construccion/pinturas-naturales.jpg' WHERE name = 'Pinturas y Recubrimientos Naturales';
UPDATE products SET image_url = '/images/products/construccion/acero-reciclado.jpg' WHERE name = 'Acero Reciclado';
UPDATE products SET image_url = '/images/products/construccion/acero-virgen.jpg' WHERE name = 'Acero Virgen';
UPDATE products SET image_url = '/images/products/construccion/aluminio.jpg' WHERE name = 'Aluminio';
UPDATE products SET image_url = '/images/products/construccion/vidrio-plano.jpg' WHERE name = 'Vidrio Plano';
UPDATE products SET image_url = '/images/products/construccion/tuberia-pvc.jpg' WHERE name = 'Tuberia PVC';
UPDATE products SET image_url = '/images/products/energia/panel-solar.jpg' WHERE name = 'Panel Solar Fotovoltaico';
UPDATE products SET image_url = '/images/products/energia/lena-seca.jpg' WHERE name = 'Lena Seca para Cocinar';
UPDATE products SET image_url = '/images/products/energia/carbon-vegetal.jpg' WHERE name = 'Carbon Vegetal';
UPDATE products SET image_url = '/images/products/energia/diesel-agricola.jpg' WHERE name = 'Diesel Agricola';
UPDATE products SET image_url = '/images/products/energia/gasolina.jpg' WHERE name = 'Gasolina';
UPDATE products SET image_url = '/images/products/energia/gas-glp.jpg' WHERE name = 'Gas GLP';
UPDATE products SET image_url = '/images/products/energia/biomasa-pellets.jpg' WHERE name = 'Biomasa Seca (Pellets)';
UPDATE products SET image_url = '/images/products/herramientas/machete.jpg' WHERE name = 'Machete';
UPDATE products SET image_url = '/images/products/herramientas/pala.jpg' WHERE name = 'Pala';
UPDATE products SET image_url = '/images/products/herramientas/pico.jpg' WHERE name = 'Pico';
UPDATE products SET image_url = '/images/products/herramientas/rastrillo.jpg' WHERE name = 'Rastrillo';
UPDATE products SET image_url = '/images/products/herramientas/azadon.jpg' WHERE name = 'Azadon';
UPDATE products SET image_url = '/images/products/herramientas/martillo.jpg' WHERE name = 'Martillo';
UPDATE products SET image_url = '/images/products/herramientas/serrucho.jpg' WHERE name = 'Serrucho';
UPDATE products SET image_url = '/images/products/herramientas/lima.jpg' WHERE name = 'Lima';
UPDATE products SET image_url = '/images/products/herramientas/destornillador.jpg' WHERE name = 'Destornillador';
UPDATE products SET image_url = '/images/products/herramientas/alicates.jpg' WHERE name = 'Alicates';
UPDATE products SET image_url = '/images/products/herramientas/afilar-herramientas.jpg' WHERE name = 'Afilar y Mantener Herramientas';
UPDATE products SET image_url = '/images/products/herramientas/taladro-electrico.jpg' WHERE name = 'Taladro Electrico';
UPDATE products SET image_url = '/images/products/herramientas/sierra-circular.jpg' WHERE name = 'Sierra Circular';
UPDATE products SET image_url = '/images/products/herramientas/amoladora.jpg' WHERE name = 'Amoladora';
UPDATE products SET image_url = '/images/products/herramientas/lijadora.jpg' WHERE name = 'Lijadora Electrica';
UPDATE products SET image_url = '/images/products/herramientas/soldadora.jpg' WHERE name = 'Soldadora Electrica';
UPDATE products SET image_url = '/images/products/tecnologia/telefono-inteligente.jpg' WHERE name = 'Telefono Inteligente';
UPDATE products SET image_url = '/images/products/tecnologia/computadora-portatil.jpg' WHERE name = 'Computadora Portatil';
UPDATE products SET image_url = '/images/products/tecnologia/computadora-sobremesa.jpg' WHERE name = 'Computadora de Sobremesa';
UPDATE products SET image_url = '/images/products/tecnologia/monitor-lcd.jpg' WHERE name = 'Monitor LCD';
UPDATE products SET image_url = '/images/products/tecnologia/lavadora.jpg' WHERE name = 'Lavadora Domestica';
UPDATE products SET image_url = '/images/products/tecnologia/refrigerador.jpg' WHERE name = 'Refrigerador Domestico';
UPDATE products SET image_url = '/images/products/tecnologia/cafetera-electrica.jpg' WHERE name = 'Cafetera Electrica';
UPDATE products SET image_url = '/images/products/tecnologia/secador-pelo.jpg' WHERE name = 'Secador de Pelo';
UPDATE products SET image_url = '/images/products/tecnologia/cable-electrico.jpg' WHERE name = 'Cable Electrico (metro)';
UPDATE products SET image_url = '/images/products/tecnologia/resistencias.jpg' WHERE name = 'Resistencias (Paquete 10)';
UPDATE products SET image_url = '/images/products/tecnologia/capacitores.jpg' WHERE name = 'Capacitores (Paquete 10)';
UPDATE products SET image_url = '/images/products/tecnologia/conectores.jpg' WHERE name = 'Conectores (Paquete)';
UPDATE products SET image_url = '/images/products/tecnologia/soldadura-electronica.jpg' WHERE name = 'Soldadura Electronica (Rollo)';
UPDATE products SET image_url = '/images/products/tecnologia/plaquetas-pcb.jpg' WHERE name = 'Plaquetas PCB (Unidad)';
UPDATE products SET image_url = '/images/products/tecnologia/fusibles.jpg' WHERE name = 'Fusibles (Paquete 10)';
UPDATE products SET image_url = '/images/products/transporte/bicicleta.jpg' WHERE name = 'Bicicleta Completa';
UPDATE products SET image_url = '/images/products/transporte/llanta-bicicleta.jpg' WHERE name = 'Llanta de Bicicleta';
UPDATE products SET image_url = '/images/products/transporte/cadena-bicicleta.jpg' WHERE name = 'Cadena de Bicicleta';
UPDATE products SET image_url = '/images/products/transporte/frenos-bicicleta.jpg' WHERE name = 'Frenos de Bicicleta';
UPDATE products SET image_url = '/images/products/transporte/caballo-silla.jpg' WHERE name = 'Caballo de Silla';
UPDATE products SET image_url = '/images/products/transporte/burro-carga.jpg' WHERE name = 'Burro de Carga';
UPDATE products SET image_url = '/images/products/transporte/mula-carga.jpg' WHERE name = 'Mula de Carga';
UPDATE products SET image_url = '/images/products/cultura/cuatro-venezolano.jpg' WHERE name = 'Cuatro Venezolano';
UPDATE products SET image_url = '/images/products/cultura/guitarra-artesanal.jpg' WHERE name = 'Guitarra Artesanal';
UPDATE products SET image_url = '/images/products/cultura/tambor.jpg' WHERE name = 'Tambor (Caja)';
UPDATE products SET image_url = '/images/products/cultura/maracas.jpg' WHERE name = 'Maracas (Par)';
UPDATE products SET image_url = '/images/products/cultura/flauta-cana.jpg' WHERE name = 'Flauta de Caña';
UPDATE products SET image_url = '/images/products/cultura/pintura-artes.jpg' WHERE name = 'Pintura y Artes Visuales';
UPDATE products SET image_url = '/images/products/recursos/agua-purificada.jpg' WHERE name = 'Agua Purificada';
UPDATE products SET image_url = '/images/products/agricultura/fertilizantes-organicos.jpg' WHERE name = 'Fertilizantes Organicos';
UPDATE products SET image_url = '/images/products/agricultura/plaguicidas-naturales.jpg' WHERE name = 'Plaguicidas Naturales';
UPDATE products SET image_url = '/images/products/agricultura/hongos-comestibles.jpg' WHERE name = 'Hongos Comestibles';
UPDATE products SET image_url = '/images/products/alimentacion/carne-res.jpg' WHERE name = 'Carne de Res';
UPDATE products SET image_url = '/images/products/alimentacion/cereales-avena.jpg' WHERE name = 'Cereales y Avena';
UPDATE products SET image_url = '/images/products/alimentacion/sal-mar.jpg' WHERE name = 'Sal de Mar';
UPDATE products SET image_url = '/images/products/alimentacion/mantequilla-queso.jpg' WHERE name = 'Mantequilla y Queso';
UPDATE products SET image_url = '/images/products/artesania/cuero-artesanal.jpg' WHERE name = 'Cuero Artesanal';
UPDATE products SET image_url = '/images/products/artesania/calzado-cuero.jpg' WHERE name = 'Calzado de Cuero';
UPDATE products SET image_url = '/images/products/artesania/metal-forjado.jpg' WHERE name = 'Metal Forjado';
UPDATE products SET image_url = '/images/products/artesania/vidrio-soplado.jpg' WHERE name = 'Vidrio Soplado';
UPDATE products SET image_url = '/images/products/construccion/impermeabilizantes.jpg' WHERE name = 'Impermeabilizantes';
UPDATE products SET image_url = '/images/products/construccion/revestimientos.jpg' WHERE name = 'Revestimientos y Estucos';
UPDATE products SET image_url = '/images/products/construccion/carpinteria-obra.jpg' WHERE name = 'Carpinteria de Obra';
UPDATE products SET image_url = '/images/products/cultura/taller-teatro.jpg' WHERE name = 'Taller de Teatro';
UPDATE products SET image_url = '/images/products/cultura/danza-tradicional.jpg' WHERE name = 'Danza Tradicional';
UPDATE products SET image_url = '/images/products/cultura/taller-literatura.jpg' WHERE name = 'Taller de Literatura';
UPDATE products SET image_url = '/images/products/cultura/produccion-audiovisual.jpg' WHERE name = 'Produccion Audiovisual';
UPDATE products SET image_url = '/images/products/educacion/matematicas.jpg' WHERE name = 'Matematicas y Numeracion';
UPDATE products SET image_url = '/images/products/educacion/tecnologia-computacion.jpg' WHERE name = 'Tecnologia y Computacion';
UPDATE products SET image_url = '/images/products/educacion/idiomas.jpg' WHERE name = 'Idiomas';
UPDATE products SET image_url = '/images/products/energia/energia-eolica.jpg' WHERE name = 'Energia Eolica';
UPDATE products SET image_url = '/images/products/energia/energia-hidraulica.jpg' WHERE name = 'Energia Hidraulica';
UPDATE products SET image_url = '/images/products/herramientas/instrumentos-medicion.jpg' WHERE name = 'Instrumentos de Medicion';
UPDATE products SET image_url = '/images/products/herramientas/herramientas-corte.jpg' WHERE name = 'Herramientas de Corte';
UPDATE products SET image_url = '/images/products/salud/apiterapia.jpg' WHERE name = 'Apiterapia';
UPDATE products SET image_url = '/images/products/salud/homeopatia.jpg' WHERE name = 'Homeopatia y Flores de Bach';
UPDATE products SET image_url = '/images/products/servicios/peluqueria-barberia.jpg' WHERE name = 'Peluqueria y Barberia';
UPDATE products SET image_url = '/images/products/servicios/costura-confeccion.jpg' WHERE name = 'Costura y Confeccion';
UPDATE products SET image_url = '/images/products/tecnologia/equipos-red.jpg' WHERE name = 'Equipos de Red';
UPDATE products SET image_url = '/images/products/tecnologia/software-soporte.jpg' WHERE name = 'Software y Soporte';
UPDATE products SET image_url = '/images/products/textiles/calzado-textil.jpg' WHERE name = 'Calzado Textil';
UPDATE products SET image_url = '/images/products/textiles/sombreros-gorros.jpg' WHERE name = 'Sombreros y Gorros';
UPDATE products SET image_url = '/images/products/transporte/carga-animal.jpg' WHERE name = 'Carga Animal';
UPDATE products SET image_url = '/images/products/transporte/combustibles-transporte.jpg' WHERE name = 'Combustibles para Transporte';
UPDATE products SET image_url = '/images/products/embalaje/vasos-hoja-platano.jpg' WHERE name = 'Vasos de Hoja de Platano';
UPDATE products SET image_url = '/images/products/embalaje/vasos-bagazo.jpg' WHERE name = 'Vasos de Bagazo de Caña';
UPDATE products SET image_url = '/images/products/embalaje/vasos-pla.jpg' WHERE name = 'Vasos de PLA (Maiz)';
UPDATE products SET image_url = '/images/products/embalaje/vasos-totuma.jpg' WHERE name = 'Vasos de Totuma/Calabaza';
UPDATE products SET image_url = '/images/products/embalaje/vasos-coco.jpg' WHERE name = 'Vasos de Coco';
UPDATE products SET image_url = '/images/products/embalaje/vasos-barro.jpg' WHERE name = 'Vasos de Barro/Ceramica';
UPDATE products SET image_url = '/images/products/embalaje/platos-hoja-platano.jpg' WHERE name = 'Platos de Hoja de Platano';
UPDATE products SET image_url = '/images/products/embalaje/platos-bagazo.jpg' WHERE name = 'Platos de Bagazo';
UPDATE products SET image_url = '/images/products/embalaje/platos-bambu.jpg' WHERE name = 'Platos de Fibra de Bambu';
UPDATE products SET image_url = '/images/products/embalaje/platos-hoja-palma.jpg' WHERE name = 'Platos de Hoja de Palma';
UPDATE products SET image_url = '/images/products/embalaje/contenedores-bagazo.jpg' WHERE name = 'Contenedores de Bagazo con Tapa';
UPDATE products SET image_url = '/images/products/embalaje/contenedores-bambu.jpg' WHERE name = 'Contenedores de Fibra de Bambu';
UPDATE products SET image_url = '/images/products/embalaje/contenedores-hoja-platano.jpg' WHERE name = 'Contenedores de Hoja de Platano';
UPDATE products SET image_url = '/images/products/embalaje/bolsas-algodon.jpg' WHERE name = 'Bolsas de Tela de Algodón';
UPDATE products SET image_url = '/images/products/embalaje/bolsas-yute.jpg' WHERE name = 'Bolsas de Tela de Yute';
UPDATE products SET image_url = '/images/products/embalaje/bolsas-papel.jpg' WHERE name = 'Bolsas de Papel Reciclado';
UPDATE products SET image_url = '/images/products/embalaje/bolsas-almidon.jpg' WHERE name = 'Bolsas Biodegradables de Almidon';
UPDATE products SET image_url = '/images/products/embalaje/envoltura-cera.jpg' WHERE name = 'Envoltura de Cera de Abejas';
UPDATE products SET image_url = '/images/products/embalaje/envoltura-hoja-platano.jpg' WHERE name = 'Envoltura de Hoja de Platano';
UPDATE products SET image_url = '/images/products/embalaje/envoltura-papel.jpg' WHERE name = 'Envoltura de Papel Encerado';
UPDATE products SET image_url = '/images/products/embalaje/cubiertos-madera.jpg' WHERE name = 'Cubiertos de Madera';
UPDATE products SET image_url = '/images/products/embalaje/cubiertos-bambu.jpg' WHERE name = 'Cubiertos de Bambu';
UPDATE products SET image_url = '/images/products/embalaje/pajitas-cana.jpg' WHERE name = 'Pajitas de Caña Natural';
UPDATE products SET image_url = '/images/products/embalaje/pajitas-papel.jpg' WHERE name = 'Pajitas de Papel';

-- Actualizar imagenes de paginas
UPDATE pages SET content = REPLACE(content, '/images/products/commons-photo-1592417817098-8f3d69102a5e.jpg', '/images/pages/asambleas-gobernanza.jpg') WHERE content LIKE '%/images/products/commons-photo-1592417817098-8f3d69102a5e.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1540420773420-3366772f4999.jpg', '/images/pages/mercado-productores.jpg') WHERE content LIKE '%/images/products/photo-1540420773420-3366772f4999.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1559526324-4b87b5e36e44.jpg', '/images/pages/trueque-tq.jpg') WHERE content LIKE '%/images/products/photo-1559526324-4b87b5e36e44.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1509440159596-0249088772ff.jpg', '/images/pages/stats-agroecologia.jpg') WHERE content LIKE '%/images/products/photo-1509440159596-0249088772ff.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1500937386664-56d1dfef3854.jpg', '/images/pages/conuco-horizonte.jpg') WHERE content LIKE '%/images/products/photo-1500937386664-56d1dfef3854.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1516253593875-bd7ba052fbc5.jpg', '/images/pages/habitat-rural.jpg') WHERE content LIKE '%/images/products/photo-1516253593875-bd7ba052fbc5.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1610348725531-843dff563e2c.jpg', '/images/pages/stats-feria.jpg') WHERE content LIKE '%/images/products/photo-1610348725531-843dff563e2c.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1595974482597-4b8da8879bc5.jpg', '/images/pages/stats-trueque.jpg') WHERE content LIKE '%/images/products/photo-1595974482597-4b8da8879bc5.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1746474072546-9fbda10daffe.jpg', '/images/pages/semillas-libertad.jpg') WHERE content LIKE '%/images/products/photo-1746474072546-9fbda10daffe.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1466637574441-749b8f19452f.jpg', '/images/pages/saberes-ancestrales.jpg') WHERE content LIKE '%/images/products/photo-1466637574441-749b8f19452f.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1500382017468-9049fed747ef.jpg', '/images/pages/feria-organizacion.jpg') WHERE content LIKE '%/images/products/photo-1500382017468-9049fed747ef.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1466611653911-95081537e5b7.jpg', '/images/pages/sistema-precios.jpg') WHERE content LIKE '%/images/products/photo-1466611653911-95081537e5b7.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1529156069898-49953e39b3ac.jpg', '/images/pages/talleres-cultura.jpg') WHERE content LIKE '%/images/products/photo-1529156069898-49953e39b3ac.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1521737604893-d14cc237f11d.jpg', '/images/pages/preguntas-frecuentes.jpg') WHERE content LIKE '%/images/products/photo-1521737604893-d14cc237f11d.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1542838132-92c53300491e.jpg', '/images/pages/hero-feria-conuquera.jpg') WHERE content LIKE '%/images/products/photo-1542838132-92c53300491e.jpg%';
UPDATE pages SET content = REPLACE(content, '/images/products/photo-1597848212624-a19eb35e2651.jpg', '/images/pages/stats-productores.jpg') WHERE content LIKE '%/images/products/photo-1597848212624-a19eb35e2651.jpg%';

-- Reemplazar cualquier URL de Unsplash restante
UPDATE products SET image_url = '/placeholder.svg' WHERE image_url LIKE '%unsplash%';

-- Reemplazar placeholder.svg con las nuevas imagenes locales
